---
title: Adductor Muscle Group
---

# Overview

| Muscle group  | [Primary Muscles](#primary-adductors) | [Secondary Muscles](#secondary-adductors) |
|------|--------|-------|
| [Hip Adductors]({{< var ref-hip-adductor-muscle-group.path >}}) | {{< var ref-hip-adductor-muscle-group.primary >}} | {{< var ref-hip-adductor-muscle-group.secondary >}} |
: {.striped .hover}


# Primary Adductors {#primary}

Pectineus, adductor longus, gracilis, adductor brevis, and adductor magnus are considered the "primary adductors" of the hip @neumannKinesiologyMusculoskeletalSystem2017. 

| Muscle  | Origin | Insertion | Nerve | Action |
|-------|--------|-------|------|--------|
| [Pectineus]({{< var ref-pectineus.path >}}) | {{< var ref-pectineus.origin >}} | {{< var ref-pectineus.insertion >}} | {{< var ref-pectineus.nerve >}} | {{< var ref-pectineus.action >}} |
| [Gracilis]({{< var ref-gracilis.path >}}) | {{< var ref-gracilis.origin >}} | {{< var ref-gracilis.insertion >}} | {{< var ref-gracilis.nerve >}} | {{< var ref-gracilis.action >}} |
| [Adductor Longus]({{< var ref-adductor-longus.path >}}) | {{< var ref-adductor-longus.origin >}} | {{< var ref-adductor-longus.insertion >}} | {{< var ref-adductor-longus.nerve >}} | {{< var ref-adductor-longus.action >}} |
| [Adductor Brevis]({{< var ref-adductor-brevis.path >}}) | {{< var ref-adductor-brevis.origin >}} | {{< var ref-adductor-brevis.insertion >}} | {{< var ref-adductor-brevis.nerve >}} | {{< var ref-adductor-brevis.action >}} |
| [Adductor Magnus]({{< var ref-adductor-magnus.path >}}) | {{< var ref-adductor-magnus.origin >}} | {{< var ref-adductor-magnus.insertion >}} | {{< var ref-adductor-magnus.nerve >}} | {{< var ref-adductor-magnus.action >}} |
: Primary Adductors of the Hip @neumannKinesiologyMusculoskeletalSystem2017 {.striped .hover}

# Secondary Adductors {#secondary}

Secondary adductors are the biceps femoris (long head), the gluteus maximus, especially the inferior (posterior) fibers, the quadratus femoris, and the obturator externus.  @neumannKinesiologyMusculoskeletalSystem2017 

| Muscle  | Origin | Insertion | Nerve | Action |
|------|--------|-------|----------|--------|
| [Gluteus Maximus]({{< var ref-gluteus-maximus.path >}}) | {{< var ref-gluteus-maximus.origin >}} | {{< var ref-gluteus-maximus.insertion >}} | {{< var ref-gluteus-maximus.nerve >}} | {{< var ref-gluteus-maximus.action >}} |
| [Quadratus Femoris]({{< var ref-quadratus-femoris.path >}}) | {{< var ref-quadratus-femoris.origin >}} | {{< var ref-quadratus-femoris.insertion >}} | {{< var ref-quadratus-femoris.nerve >}} | {{< var ref-quadratus-femoris.action >}} |
| [Obturator Externus]({{< var ref-obturator-externus.path >}}) | {{< var ref-obturator-externus.origin >}} | {{< var ref-obturator-externus.insertion >}} | {{< var ref-obturator-externus.nerve >}} | {{< var ref-obturator-externus.action >}} |
| [Biceps Femoris Long Head]({{< var ref-biceps-femoris-long-head.path >}}) | {{< var ref-biceps-femoris-long-head.origin >}} | {{< var ref-biceps-femoris-long-head.insertion >}} | {{< var ref-biceps-femoris-long-head.nerve >}} | {{< var ref-biceps-femoris-long-head.action >}} |
: Secondary Adductors of the Hip @neumannKinesiologyMusculoskeletalSystem2017 {.striped .hover}

# Anatomy

“The adductor muscle group occupies the medial quadrant of the thigh. Topographically, the adductor muscles are organized into three layers (Fig. 12.32). The pectineus, adductor longus, and gracilis occupy the superficial layer. Proximally, these muscles attach along the superior and inferior pubic ramus and adja­cent body of the pubis. Distally, the pectineus and the adduc­tor longus attach to the posterior surface of the femur—near and along varying regions of the linea aspera. The long and slender gracilis attaches distally to the medial side of the proximal tibia (see Fig. 13.7). The middle layer of the adductor group is occupied by the triangular ­shaped adductor brevis. The adductor brevis attaches to the pelvis on the inferior pubic ramus and to the femur along the proximal one­third of the linea aspera.” @neumannKinesiologyMusculoskeletalSystem2017 
“The deep layer of the adductor group is occupied by the massive, triangular adductor	 magnus (see Fig. 12.26, left side, and Fig. 12.39, right side). As its name implies, the adductor magnus is the largest of the adductor muscles, accounting for 60% of the total cross­sectional area of the entire adductor muscle group.222 As a whole, the adductor magnus attaches proximally to the pelvis from two heads: an anterior head from the ischial ramus and a posterior head from the ischial tuberosity. Realize, however, that other anatomic classifications have been suggested.222 The anterior head	of	the	adductor	magnus has two sets of fibers: horizontal and oblique. The relatively small (and often poorly defined) set of horizontally directed fibers crosses from the inferior pubic ramus to the extreme proximal end of the linea aspera, often called the adductor minimus. The larger obliquely directed fibers run from the ischial ramus to nearly the entire length of the linea aspera, as far distally as the medial supracondylar line. Both parts of the anterior head are innervated by the obturator nerve, which is typical of the adductor muscles.222” @neumannKinesiologyMusculoskeletalSystem2017 

# Function
## Overall Function
“Overall Function The lines of force of the adductors approach the hip from many different orientations. Functionally, therefore, the adductor muscles produce torques in all three planes at the hip.57,79,159,222 The following section considers the primary actions of the adduc­ tors in the frontal and sagittal planes. The action of these muscles as secondary internal rotators is discussed later in this chapter. Understanding that the adductor muscles produce torques in all three planes of motion helps justify their large size and possibly their vulnerability to strain­ related injury.” @neumannKinesiologyMusculoskeletalSystem2017 

## Frontal Plane Function
“Frontal Plane Function The most obvious function of the adductor muscles is production of adduction torque. This torque controls the kinematics of both femoral­on­pelvic and pelvic­on­femoral hip adduction. Fig. 12.33 shows an example of selected adductor muscles contracting bilaterally to control both forms of motion. On the right side, several adductors are shown accelerating the femur to strike the soccer ball. Adding to the forcefulness of this action is the down­ ward rotation or lowering of the right iliac crest—a motion occur­ ring by pelvic­on­femoral adduction of the left hip. Although only the adductor magnus is shown on the left side, other adductor muscles assist in this action. The overall adduction of the planted left hip typically incorporates eccentric activation of the gluteus medius to help decelerate and thus help control the kinematics of pelvic­on­femoral motion. Weakness of the hip abductors during a soccer kick may place excessive valgus strain on the planted knee, which has been theorized to increase the risk of injury to the anterior cruciate ligament in female soccer players.” @neumannKinesiologyMusculoskeletalSystem2017 

## Sagittal Plane Function
“Regardless of hip position, the posterior fibers of the adductor magnus are powerful extensors of the hip, similar to the hamstring muscles.222 Of interest, however, is that within an arc of about 40 to 70 degrees of hip flexion, the line of force of most of the other adductor muscles runs directly	through	or	close	to the medial­lateral axis of rotation of the hip. At this point, the adductor muscles, as a group, lose much of their potential to produce torque in the sagittal plane.103 When outside the 40­ to 70­degree flexed posi­ tion, however, the individual adductor muscles regain leverage as significant flexors or extensors of the hip.57,103 Consider, for example, the adductor longus as a representative adductor muscle during a fast sprint (Fig. 12.34A). From a position of about 100 degrees of hip flexion, the line of force of the adductor longus is well posterior to the medial­lateral axis of the joint. At this position the adductor longus has an extensor moment arm and is capable of generating an extension torque—similar to the posterior head of the adductor magnus. From a hip position of near extension, however, the line of force of the adductor longus is well anterior to the medial­lateral axis of rotation (see Fig. 12.34B). The adduc­ tor longus now has a flexor moment arm and generates a flexion torque qualitatively similar to that of the rectus femoris, for example. The adductor muscles therefore provide a useful source of flexion and extension torque at the hip. The bidirectional torques are useful during high­power, cyclic motions such as sprinting, cycling, running up a steep hill, and descending and rising from a deep squat. When the hip is near full flexion, the adductors are most mechanically prepared to augment the exten­ sors. In contrast, when the hip is near full extension, they are most mechanically prepared to augment the flexors. This utilitarian function of the adductors may partially explain their relatively high susceptibility to soreness or strain injury during running and jumping, especially while quickly changing directions.” @neumannKinesiologyMusculoskeletalSystem2017 

# Internal Rotation Biomechanics

See Hip IR?
