---
title: Posterior Cruciate Ligament (PCL)
---

# Cruciate Ligament

"The two central intra-articular cruciate ligaments derive their name from the Latin word crucere (cross) because they cross each other (Fig. 20-1). Both the ACL and the PCL lie in the center of the joint, and each is named according to their attachment sites on the tibia.1 The cruciate ligaments, which differ from those of other joints in that they restrict normal, rather than abnormal, motion, are the main stabilizing ligaments of the knee and restrain against anterior (ACL) and posterior (PCL) translations of the tibia on the femur. They also restrain against excessive internal and external rotation and varus/valgus movements of the tibia." @duttonDuttonOrthopaedicExamination2020


"The blood supply to the cruciate ligaments is largely provided from the middle and inferior geniculate branches of the popliteal artery. The cruciate ligaments are innervated by the posterior articular nerve, a branch of the posterior tibial nerve.1 The function of this nerve supply is questionable although it may serve as proprioceptive in nature. In addition, the cruciate ligaments contain mechanoreceptors, suggesting that disruption of the ligament structure can produce partial deafferentation of the joint.10 Evidence of a proprioceptive function of the ACL comes from extensive histologic observations demonstrating that the ACL appears to contain proprioceptive nerve endings.1 Although these cruciate ligaments function together, they are described separately." @duttonDuttonOrthopaedicExamination2020

# Info


"Posterior cruciate (see Fig. 20-1). It provides the primary restraint to posterior translation and medial rotation of the tibia on the femur and is a secondary restraint to valgus and varus rotation of the tibia." @duttonDuttonOrthopaedicExamination2020


# Anatomy

"The PCL attaches posteriorly to the insertion of the posterior horns of the lateral and medial menisci on the posterior part of the posterior intercondylar fossa of the tibia.1 From here, the PCL extends obliquely medially, anteriorly, and superiorly to attach to the lateral surface of the medial femoral condyle (see Fig. 20-1). Overall, the ligament is wider at its femoral origin and narrowest near the tibial insertion.1 The PCL is covered by synovial lining and is therefore considered to be extrasynovial yet intra-articular." @duttonDuttonOrthopaedicExamination2020


# Biomechanics

"Information regarding the biomechanical function of the PCL is scant compared with that of the ACL. It is known that the PCL is 50% thicker and has twice the tensile strength of the ACL.1 The PCL is more vertical in extension and horizontal in flexion. Like the ACL, the PCL consists of two bundles: anterior lateral and posterior medial. Overall, the ligament is most taut with further flexion of the knee.14 Specifically, the anterior lateral bundle is taut in flexion, while the posterior medial bundle is taut in extension. " @duttonDuttonOrthopaedicExamination2020

# Function

"The PCL provides the vast majority of the total restraint to posterior translation of the tibia on the femur, with the remainder being provided by the collateral ligaments, posterior portion of the medial and lateral capsules, and the popliteus tendon. The contribution percentage resisting posterior translation decreases as the knee extends. The PCL also restrains internal rotation of the tibia on the femur and helps prevent posteromedial instability at the knee.14" @duttonDuttonOrthopaedicExamination2020 


"Other functions of the PCL include acting as a secondary restraint to external rotation of the tibia on the femur at 90 degrees of flexion, assisting with a rolling/gliding mechanism of the tibiofemoral joint, and resisting varus/valgus forces at the knee after the collateral ligaments have failed.14" @duttonDuttonOrthopaedicExamination2020 


"In concert with the PCL are the anterior and posterior meniscofemoral ligaments. Although these ligaments arise from the common PCL origin, they are distinct structures having different insertion sites.18 Both are named with respect to the orientation to the PCL (see “Lateral Meniscus” section). Since the insertion site of the meniscofemoral ligaments is different from that of the PCL, if a midsubstance tear of the PCL occurs, it is possible that one or both of the meniscofemoral ligaments may remain intact." @duttonDuttonOrthopaedicExamination2020

# Dysfunction

"A significant force is needed to tear the PCL. Thus, tears of the PCL are usually the result of severe contact injuries that often occur in traumatic situations, such as a dashboard injury during a motor vehicle accident." @duttonDuttonOrthopaedicExamination2020


