---
title: Lateral Meniscus
---

"The lateral meniscus, which forms a C-shaped incomplete circle,25 sits atop the convex lateral tibial plateau (see Fig. 20-2). It occupies a larger portion (approximately 80%) of the articular surface than the medial meniscus (approximately 60%) and is more mobile than its medial counterpart.23 Both horns of the lateral meniscus are attached to the tibia.23 " @duttonDuttonOrthopaedicExamination2020

"The periphery of the lateral meniscus attaches to the tibia, the capsule, and the coronary ligament, but not to the LCL. The posterior horn of the lateral meniscus attaches to the inner aspect of the medial femoral condyle via the anterior and posterior meniscofemoral ligaments of Humphrey and Wrisberg, respectively23:" @duttonDuttonOrthopaedicExamination2020

- "The ligament of Humphrey, also known as the anterior meniscofemoral ligament, runs anteriorly to the PCL and inserts on the posterior aspect of the lateral meniscus.18" @duttonDuttonOrthopaedicExamination2020 
- "The ligament of Wrisberg, also known as the posterior meniscofemoral ligament, runs posteriorly to the PCL to insert either into the superior/lateral aspect of the tibia, the posterior aspect of the lateral meniscus, or the posterior capsule." @duttonDuttonOrthopaedicExamination2020 

# Stabilization

"The meniscofemoral ligaments become taut with internal rotation of the tibia and help with stabilization of the meniscus.1" @duttonDuttonOrthopaedicExamination2020


# Dysfunction

:::{.callout-note}
"The lateral meniscus often is associated with the appearance of synovial-filled cysts, which may occur following a minor injury to the meniscus and produce a small internal tear. As fluid begins to congregate within this tear, it is pushed deeper and deeper into the meniscus. The swelling eventually produces a small bulge on the lateral aspect of the meniscus." @duttonDuttonOrthopaedicExamination2020
:::

# Relationship to other structures

"The lateral meniscus has an interesting relationship with the popliteus tendon, which supports it during knee extension and separates it from the joint (see later discussion).1" @duttonDuttonOrthopaedicExamination2020

