---
title: Lumbar Lateral Recess Stenosis
---


"Lateral stenosis is characterized by the encroachment of the spinal nerve in the lateral recess of the spinal canal or in the intervertebral foramen. Initially the depth of the canal that constituted narrowing was identified as an anteroposterior measurement, but more recently the lateral width of the spinal canal has been studied.38 " @duttonDuttonOrthopaedicExamination2020

# Causes

Lumbar Lateral Recess Stenosis is primarily caused by facet joint hypertrophy, loss of IVD height, IVD bulging, and spondylolisthesis

## Degenerative Disk Disease (DDD) {#ddd}

Lumbar lateral recess stenosis is associated with Degenerative Disk Disease (DDD) @duttonDuttonOrthopaedicExamination2020

## Degenerative Spinal Stenosis

- More often observed in elderly patients @duttonDuttonOrthopaedicExamination2020
- Commonly associated with lumbar spine surgery in patients older than 60 years @duttonDuttonOrthopaedicExamination2020. 



# Positional Preferences

Elderly patients with lateral recess spinal stenosis or spinal stenosis will find relief when sitting or forward bending, but aggravated by walking @duttonDuttonOrthopaedicExamination2020.

Supine with both knees held against the chest tends to be a comfortable position for patients with *Lateral recess stenosis* since it posteriorly rotates the pelvis, which widens the lumbar intervertebral foramina @duttonDuttonOrthopaedicExamination2020.

# Predictors

Independent predictors @duttonDuttonOrthopaedicExamination2020

1. Older age @duttonDuttonOrthopaedicExamination2020
1. pain with standing/walking @duttonDuttonOrthopaedicExamination2020
1. Relief with sitting/bending @duttonDuttonOrthopaedicExamination2020

# Tests

- [Special Tests](#special-tests)
    - [Bilateral Straight leg Raise (bSLR)](#b-slr)

## Special Tests

### Bilateral SLR {#b-slr}

"Because a central protrusion may mimic a lateral recess stenosis, a differentiation test is needed. The bicycle test of van Gelderen is advocated. The patient is appropriately positioned on a bicycle and asked to pedal against resistance." @duttonDuttonOrthopaedicExamination2020

A patient with lateral recess stenosis should not have a significant change in symptoms @duttonDuttonOrthopaedicExamination2020.
Whereas a patient with intermittent claudication in their lower extremities would experience an increase in symptoms due to the vascular pressure change due to gravity @duttonDuttonOrthopaedicExamination2020.



# Stretching Interventions

A patient with *Lumbar lateral recess stenosis* who responds well to lumbar flexion exercises are indicated for stretching exercises such as hip flexors and rectus femoris while protecting the lumbar spine from excessive lordosis @duttonDuttonOrthopaedicExamination2020.

