---
title: Index of Bones
---


### Bones of the Skull

#### Neurocranium

- Ethmoid bone (cribriform plate)
- Frontal bone
- Occipital bone
- Parietal bone
- Sphenoid bone
- Temporal bone (petrous and squamous parts)

#### Visccerocranium

- Ethmoid bone
- Hyoid bone
- Inferior nasal concha
- Lacrimal bone
- Mandible
- Maxilla
- Nasal bone
- Palatine bone
- Sphenoid bone (pterygoid process)
- Temporal bone
- Vomer

::: {.callout-note collapse="true"}
# Neurocranium vs Viscerocranium
Most of the ethmoid bone is in the viscerocranium; most of the sphenoid bone is in the neurocranium. The temporal bone is divided between the two @gilroyAtlasAnatomy2020
:::

- Sphenoid Bone
    - [Foramen ovale]({{< var ref-foramen-ovale-sphenoid-bone.path >}}) (of the sphenoid bone)
- [Meckel's Cave]({{< var ref-meckels-cave.path >}})

### Upper extremity bones

- [Scapula]({{< var ref-scapula-bone.path >}})
- [Clavicle]({{< var ref-clavicle-bone.path >}})
- [Humerus]({{< var ref-humerus-bone.path >}})
- [Radius]({{< var ref-radius-bone.path >}})
- [Ulna]({{< var ref-ulna-bone.path >}})
- Carpal bones
- 2nd Carpal row
- Metacarpals
- Proximal Phalanges
- Middle Phalanges
- Distal Phalanges