---
title: Acetabular Labrum
---




- Fibrocartilage

# Function

- Deepens acetabulum
- &#8595; stress by inc contact area


# Dutton

"The acetabular labrum (Fig. 19-3) is a semicircular ring consisting of fibrocartilage and dense connective tissue24 that encases the femoral head and is attached to the acetabular margin. The labrum, which varies greatly in form and thickness, has a triangular cross section: an internal articular surface, an external surface contacting the joint capsule, and a basal surface attached to the acetabular bone and transverse ligaments.4 Most of the labrum is composed of thick, type I collagen fiber bundles principally arranged parallel to the acetabular rim, with some fibers scattered throughout this layer running obliquely to the predominant fiber orientation.25 The normal microvasculature of the acetabular labrum consists of a group of small vessels located in the substance of the labrum traveling circumferentially around the labrum at its attachment site on the outer surface of the bony acetabular extension.26 In addition, the labrum is surrounded by highly vascularized synovium that is present in the capsular recess.26 The central portion is contiguous with the cartilaginous surface of the acetabulum, and the periphery is continuous with the hip capsule.17 The majority of the acetabular labrum on the articular side is avascular except for the outer third. In addition, cadaver studies have shown it to contain sensory innervations with penetration only into the outer one-third of the substance of the labrum.24 Nerve-endings and sensory end organs in the superficial layers of the labrum participate in nociceptive and proprioceptive mechanisms.27,28 The acetabular labrum of the hip, to a large extent, is analogous to the meniscus of the knee (see Chapter 20) and the labrum of the glenohumeral joint (see Chapter 16) in that it enhances joint stability by deepening the socket by 21%,29 and decreases the forces transmitted to the articular cartilage, by absorbing up to 28% of hip joint forces.29,30 The osseous acetabulum in the hip also provides substantial static stability to the hip joint. Deepening of the socket that is provided by the labrum would, therefore, appear to be less important at the hip." @duttonDuttonOrthopaedicExamination2020 

"In addition, the labrum functions as a force distributor and shock absorber.17 Another proposed function of the labrum is to improve the mobility of the hip by providing an elastic alternative to the bony rim." @duttonDuttonOrthopaedicExamination2020


# Injury

"Injuries to the acetabular labrum can occur through a variety of mechanisms1: ▶ The posterior aspect of the labrum undergoes the greatest circumferential strain, with peak force in hip flexion. ▶ The anterior aspect of the labrum undergoes the greatest force in combined hip flexion and adduction." @duttonDuttonOrthopaedicExamination2020 


## Compensation

"The hip external and internal rotators’role in stabilization may become more crucial when the acetabular labrum is torn secondary to the subsequent loss of passive rotational stability.44" @duttonDuttonOrthopaedicExamination2020