---
title: Iliotibial Band (IT Band)
---


"The ITB or tract begins as a wide covering of the superior and lateral aspects of the pelvis and thigh in continuity with the fascia latae (Figs. 20-4 and 19-5). It inserts distal and lateral to the patella at the tubercle of Gerdy on the lateral condyle of the tibia. Anteriorly, it attaches to the lateral border of the patellar. Posteriorly, it is attached to the tendon of the biceps femoris. Laterally, it blends with an aponeurotic expansion from the VL (see Chapter 19)." @duttonDuttonOrthopaedicExamination2020 


"Like the patellar tendon, the ITB can be viewed as a ligament or a tendon. Its location adjacent to the center of rotation of the knee allows it to function as an anterolateral stabilizer of the knee in the frontal plane and to both flex and extend the knee.1 During stationary standing, the primary function of the ITB is to maintain knee and hip extension, providing the thigh muscles an opportunity to rest. While walking or running, the ITB helps maintain flexion of the hip and is a major support of the knee in squatting from full extension until 30 degrees of flexion. In knee flexion greater than 30 degrees, the iliotibial tract becomes a weak knee flexor, as well as an external rotator of the tibia." @duttonDuttonOrthopaedicExamination2020 