---
title: Golf Swing
---

![How triplanar pelvic position affects overall system tension. When pelvic pronation occurs, the trunk and pelvis spiral across 3 planes, moving the left side of the pelvis forward and downward toward the stable right lower extremity. The pelvic drop, coupled with this forward and downward motion, forces the right hip into adduction and internal rotation. As the left knee moves from a position of stability towards knee valgus the musculoskeletal tension throughout the entire system is now compromised @dischiaviRethinkingDynamicKnee2019](\The Archive/Performance Training/Golf/images/golfer rubber band.png)

<q>
The golf swing is an example of how system tension could affect the lower extremity. Consider a golfer preparing to strike a ball. As the backswing is completed, the left hip and knee maintain alignment with trunk positioning and stability (arrows in panel A of the FIGURE), which in turn maintains system tension (represented here by an imaginary rubber band wrapped around the golfer) @dischiaviRethinkingDynamicKnee2019.

The rubber band represents the interconnected muscular pathways coursing through the anterior and posterior kinetic chains @dischiaviRethinkingDynamicKnee2019.
Panel B of the FIGURE depicts the left lower extremity undergoing medial collapse, demonstrating dynamic knee valgus.
These coupled motions have now resulted in the loss of system tension that was maintained when the golfer could keep the left hemi-pelvis stable @dischiaviRethinkingDynamicKnee2019. 

</q>