---
title: Pelvis Bone
---


The pelvis refers to a bony ring made up of the two innominates and the sacrum @neumannKinesiologyMusculoskeletalSystem2017.


# Functions

The pelvis has 3 main functions:

1. Serve as a common attachment point for muscles @neumannKinesiologyMusculoskeletalSystem2017
1. Transmit BW forces when in standing or sitting @neumannKinesiologyMusculoskeletalSystem2017
1. Support the organs via the pelvic floor @neumannKinesiologyMusculoskeletalSystem2017


## Muscular attachments

The pelvis serves as a common attachment point for muscles @neumannKinesiologyMusculoskeletalSystem2017

## BW transmission

The pelvis transmits the weight of the upperbody and trunk when in sitting or standing @neumannKinesiologyMusculoskeletalSystem2017.
When in sitting, the load is primarily transmitted through the ischial tuberosities @neumannKinesiologyMusculoskeletalSystem2017.
When in standing, the forces from one's bodyweight is transmitted through the pelvis to the lower extremity @neumannKinesiologyMusculoskeletalSystem2017.

## Support the organs

The pelvis, along with the pelvic floor musculature and connective tissue serves to support organs involved in bowel, bladder, and reproductive function @neumannKinesiologyMusculoskeletalSystem2017.

