---
title: Lion's Mane Mushroom (*Hericium erinaceus*)
---

*Hericium erinaceus* commonly known as "Lion's Mane," is an edible mushroom  @dochertyAcuteChronicEffects2023 


# Scientific Classification

| Type | Lion's Mane |
|-|-|
|Family |Hericiaceae @dochertyAcuteChronicEffects2023 |
|Order | Russulales @dochertyAcuteChronicEffects2023  |
| Class | Agaricomycete @dochertyAcuteChronicEffects2023  |
|Phylum| Basidiomycota @dochertyAcuteChronicEffects2023 |
: {.hover .striped}


# Medicinal properties

- Antioxidant @dochertyAcuteChronicEffects2023
- Antimicrobial @dochertyAcuteChronicEffects2023
- Anticancer effects @dochertyAcuteChronicEffects2023

# Neuroprotective Properties

# Neuroregenerative Properties

# Mechanism

"These are likely underpinned by the numerous bioactive components identified within the mycelia and fruiting bodies of H. erinaceus, including polysaccharides, phenolic acids and terpenoids, specifically hericenones and erinacines [6,9]. Interestingly, both hericenones and erinacines can easily cross the blood–brain barrier [10]; promote nerve growth factor synthesis and secretion [11,12]; and, in animal models, have been shown to exert anti-neuroinflammatory and neuroprotective properties and promising cognition-enhancing effects" @dochertyAcuteChronicEffects2023

"Additionally, an increase in circulating pro-brain-derived neurotrophic factor (BDNF) has been observed following hericene A (isolated from H. erinaceus) administration in mice [18]." @dochertyAcuteChronicEffects2023 