---
title: Central Sensitization 
---

Central sensitization referes to increase in the excitability and responsiveness of neurons in the spinal cord. Central sensitization may explain the persistence of pain beyond the removal or resolution of the initiating stimulus @ballantyneBonicaManagementPain2019




# Clinical Indicators

## Subjective

- Disproportionate, non-mechanical, unpredictable pattern of pain provocation in response to multiple/non-specific aggravating/easing factors @smartMechanismsbasedClassificationsMusculoskeletal2012.
- Pain persisting beyond expected tissue healing/pathology recovery times @smartMechanismsbasedClassificationsMusculoskeletal2012.
- Pain disproportionate to the nature and extent of injury or pathology @smartMechanismsbasedClassificationsMusculoskeletal2012.
- Widespread, non-anatomical distribution of pain @smartMechanismsbasedClassificationsMusculoskeletal2012.
- History of failed interventions (medical/surgical/therapeutic) @smartMechanismsbasedClassificationsMusculoskeletal2012.
- Strong association with maladaptive psychosocial factors (e.g. negative emotions, poor selfefficacy, maladaptive beliefs and pain behaviours, altered family/work/social life, medical conflict) @smartMechanismsbasedClassificationsMusculoskeletal2012.
- Unresponsive to NSAIDS and/or more responsive to anti-epileptic (e.g. Lyrica) /antidepressant (e.g. Amitriptyline) medication @smartMechanismsbasedClassificationsMusculoskeletal2012.
- Reports of spontaneous (i.e. stimulus-independent) pain and/or paroxysmal pain (i.e. sudden recurrences and intensification of pain) @smartMechanismsbasedClassificationsMusculoskeletal2012.
- Pain in association with high levels of functional disability @smartMechanismsbasedClassificationsMusculoskeletal2012.
- More constant/unremitting pain @smartMechanismsbasedClassificationsMusculoskeletal2012.
- Night pain/disturbed sleep @smartMechanismsbasedClassificationsMusculoskeletal2012.
- Pain in association with other dysesthesias (e.g. burning, coldness, crawling) @smartMechanismsbasedClassificationsMusculoskeletal2012.
- Pain of high severity and irritability (i.e. easily provoked, taking a long time to settle) @smartMechanismsbasedClassificationsMusculoskeletal2012


## Examination

- Disproportionate, inconsistent, non-mechanical/non-anatomical pattern of pain provocation in response to movement/mechanical testing @smartMechanismsbasedClassificationsMusculoskeletal2012.
- Positive findings of hyperalgesia (primary, secondary) and/or allodynia and/or hyperpathia within the distribution of pain @smartMechanismsbasedClassificationsMusculoskeletal2012.
- Diffuse/non-anatomic areas of pain/tenderness on palpation @smartMechanismsbasedClassificationsMusculoskeletal2012.
- Positive identification of various psychosocial factors (e.g. catastrophisation, fear-avoidance behaviour, distress) @smartMechanismsbasedClassificationsMusculoskeletal2012.




