---
title: Hamstrings
---


"The hamstring muscles (i.e., semimembranosus, semitendinosus, and long head of the biceps femoris) have their proximal attachment on the ischial tuberosity. The short head of the biceps has its proximal attachment on the lateral lip of the linea aspera of the femur. Distally, the hamstrings cross the knee joint and attach to the tibia and fibula" @neumannKinesiologyMusculoskeletalSystem2017 

"All hamstring muscles, except the short head of the biceps femoris, cross the hip and knee. As described in Chapter 12, the three biarticular hamstrings are very effective hip extensors, especially in the control of the position of the pelvis and trunk over the femur. " @neumannKinesiologyMusculoskeletalSystem2017 

"As a group, the hamstrings primarily function to extend the hip and to flex the knee. The hamstrings are innervated by branches of the sciatic nerve." @duttonDuttonOrthopaedicExamination2020 

# Knee Rotation

:::{layout-ncol="2"}
### Internal rotation

- Medial hamstrings @neumannKinesiologyMusculoskeletalSystem2017
    - Semimembranosus @neumannKinesiologyMusculoskeletalSystem2017
    - Semitendinosus @neumannKinesiologyMusculoskeletalSystem2017

### External Rotation
Biceps femoris flexes and externally rotates the knee @neumannKinesiologyMusculoskeletalSystem2017
:::



# Examination

- Length Test
    - SLR
    - 90-90 knee extension
- MMT

# Mobility Exercises

- Elephant walks
- SL HF activation + spine flexion

# Strength Exercises

- Exercises biasing fully lengthened position
    - Nordic Curl
- Exercises biasing fully shortened
    - Standing HS curls
- Exercises for mid range