---
title: Multidirectional Instability of the Lumbar Spine
---








# Clinical Presentation

## Subjective

- "Patients describe their provocative movements as being multi-directional in nature (Fig. 11). All weight bearing postures are painful and diÅculty is reported in obtaining relieving positions during weight bearing" @osullivanMasterclassLumbarSegmental2000 
- "Locking of the spine is commonly reported following sustained flexion, rotation and extension postures" @osullivanMasterclassLumbarSegmental2000 

## Posture

- "These patients may assume a Øexed, extended or laterally shifted spinal posture" @osullivanMasterclassLumbarSegmental2000 

## Pain

"Excessive segmental shifting and hinging patterns may be observed in all movement directions with `jabbing' pain and associated back muscle spasm." @osullivanMasterclassLumbarSegmental2000 

## Overuse of Global spine stabilizers

- "These patients have great diÅculty assuming neutral lordotic spinal positions, and attempts to facilitate lumbar multiÆdus and transversus abdominis co-contraction (especially during weight bearing positions) are usually associated with a tendency to Øex, extend or laterally shift the spine segmentally, with associated global muscle substitution, bracing of the abdominal wall and pain." @osullivanMasterclassLumbarSegmental2000 

## Palpation

- Hypomobility at the symptomatic level
    - "Palpatory examination reveals multi-directional increased intersegmental motion at the symptomatic level." @osullivanMasterclassLumbarSegmental2000 

## ROM

- Normal PROM
- Abnormal AROM


# Examination

- Reflex Testing

## Joint Mobility

- Manually assess joint mobility
- 

## Special Tests

- (+) Prone Instability  @duttonDuttonOrthopaedicExamination2020
- Anterior STability Test @duttonDuttonOrthopaedicExamination2020
- LAteral STability Test @duttonDuttonOrthopaedicExamination2020
- Passive Lumbar Extension Test @duttonDuttonOrthopaedicExamination2020


# Prognosis

"If these patients present with high levels of irritability and an inability to tolerate compressive loading in any position, they have a poor prognosis for conservative exercise management." @osullivanMasterclassLumbarSegmental2000 


# Rehabilitation

