---
title: Rib Fracture
---



# Stress fracture

In relation to other stress injuries, rib stress fractures are uncommon @kielStressReactionFractures2023

1st rib fractures are the most common  @kielStressReactionFractures2023

## Epidemiology

Populations susceptible to 1st rib stress fx: @kielStressReactionFractures2023

- Pitchers @kielStressReactionFractures2023
- Basketball players @kielStressReactionFractures2023
- Weightlifters @kielStressReactionFractures2023
- Ballet dancers @kielStressReactionFractures2023

Ribs #4-9 stress fx are seen in competitive rowers @kielStressReactionFractures2023

Posteromedial rib stress fractures can be seen in golfers @kielStressReactionFractures2023

## Subjective
- Insidious onset of pain without any specific trauma @kielStressReactionFractures2023
- High volume: Hx high volume of a specific exercise (i.e. running)  @kielStressReactionFractures2023
- Change: Increase in training intensity/volume or training surface  @kielStressReactionFractures2023
- Sx progress from training to ADLs  @kielStressReactionFractures2023
- Eased w/ decreased activity  @kielStressReactionFractures2023

## Complications

- Can lacerate pleura, lung or abdominal organs
- Can result in hemothorax or pneumothorax