---
title: Lateral Cutaneous Nerve of the Thigh
---


# Roots

# Pathway

# Motor innervation

# Cutaneous Innervation

# Examination

## Sidelying

- Side Lying bottom leg bent
- Top leg in slight ext, add, hands up over head, slump down
- (+) Reproduce symptoms


## Standing



# Dysfunction

# Meralgia Paresthetica

"Ischemia (diminished blood flow) of the lateral cutaneous nerve of the thigh can result when the nerve is stretched or entrapped by the inguinal ligament (see Fig. 34.11B) during hyperextension of the hip or with increased lordosis (curvature) of the lumbar spine, as often occurs during pregnancy. This results in pain, numbness, or paresthesia (tingling or burning) on the outer aspect of the thigh. It is most commonly found in obese or diabetic individuals and in pregnant women." @gilroyAtlasAnatomy2020 

## Symptoms

- Lat leg pain.numbness
- IT band pain
- Lat knee pain

## Causes

- Surgery
- Pelvic surgery
- Adhesive conditions etc


## Post-partum

Meralgia paresthetic is common post-partum since the inguinal canal compressed due to the combination of laxity and supine position for hours

## Treatment

- Clear lumbar nerve roots and thoracolumbar fascia
- Clear fascia along ASIS
- Stretch the ITB
    - do NOT do the slump during exercise since it may aggravate it 
- Regional stretches
    - Standing SB
    - Flossing in and out of the position
- Nerve sliding
    - Same position as testing position
    - Reach I/L arm up and overhead to intensify the floss
    - IF pain → Partial ROM, no slumping
    - Try to get them as far as you can without too much sx
- Progress → More leg extension
- Strengthen hip abductors
    - Supports lateral compartment of the thigh

