---
title: Respiration
---


# Diaphragmatic breathing

Important to avoid pathologies, such as [thoracic outlet syndrome]({{< var ref-thoracic-outlet.syndrome >}})




# Muscles related to respiration

## Inspiration

Primary

- Diaphragm
- Levator costarum
- External intercostals
- Internal intercostals (ant) 

Accessory

- Scaleni
- Sternocleidomastoid (SCM)
- Trapezius (UT, MT, LT)
- Serratus Anterior (SA)
- Serratus Posterior Sup/Inf (SP)
- Pectoralis Major
- Pectoralis Minor
- Lat dorsi
- Subclavius

| Muscle  | Origin | Insertion | Nerve | Action |
|------|--------|-------|----------|--------|
| [Sternocleidomastoid]({{< var ref-sternocleidomastoid.path >}}) | {{< var ref-sternocleidomastoid.origin >}} | {{< var ref-sternocleidomastoid.insertion >}} | {{< var ref-sternocleidomastoid.nerve >}} | {{< var ref-sternocleidomastoid.action >}} |

: Accessory Muscles of Inspiration {.striped .hover}

## Expiration

Primary

- abs: 
    - Internal Obliques (IO)
    - External obliques (EO)
    - Rectus Abdominis (RA)
    - Transverse Abdominis (TA)
- Transverse Intercostal
- Internal intercostal
- Transversus Thoracis

Accessory

- Lat dorsi
- Serratus post inf
- Quadratus Lumborum (QL)
- Iliocostalis lumborum



# Dysfunctional Breathing

## Stress Breathing
