---
title: "Multiple Sclerosis"
subtitle: "A progressive autoimmune disease of the CNS"
---



:::{.callout-note title="AKA"}

- Charcot’s triad @osullivanPhysicalRehabilitation2019 
:::

Multiple sclerosis (MS) is a progressive autoimmune disease characterized by inflammation, selective demyelination, and gliosis @osullivanPhysicalRehabilitation2019. 



# Etiology

:::{layout-ncol="3"}
### Genetics
It appears that although individuals do not inherit the disease, they may inherit a genetic susceptibility to immune system dysfunction


:::

# Pathogenesis

Molecular mimicry

- An autoimmune response when individuals with a genetic susceptibility are exposed to a viral agent @osullivanPhysicalRehabilitation2019


Major Pathologic Mechanisms that result in clinical manifestations @olekManifestationsMultipleSclerosis2023 

- Inflammation @olekManifestationsMultipleSclerosis2023 
- Demyelination @olekManifestationsMultipleSclerosis2023 
- Axonal degeneration @olekManifestationsMultipleSclerosis2023 

## Theories

Theories(Olek and Mowry 2023)

- "The most widely accepted theory is that MS begins as an inflammatory immune-mediated disorder characterized by autoreactive lymphocytes" @olekManifestationsMultipleSclerosis2023 
- "Later, the disease is dominated by microglial activation and chronic neurodegeneration" @olekManifestationsMultipleSclerosis2023


# Clinical Presentation

:::{layout-ncol="3"}

### Onset

- 3% to 5% Occur before 16years @osullivanPhysicalRehabilitation2019
- Onset of MS typically occurs between ages 20 and 50 years and is uncommon in children @osullivanPhysicalRehabilitation2019 
- 9% of patients experience sx onset after 50 yeras old @osullivanPhysicalRehabilitation2019 

### Gender

- Prevalence: MS occurs more often in women than men (2-3:1) when sx onset before 50y/o  @osullivanPhysicalRehabilitation2019 
- Severity: Men experience more progressive disease course and more rapid disability @osullivanPhysicalRehabilitation2019

:::


# Motor Control

- Facilitation
    - Bilateral impairments, more stability