---
title: Vastus Intermedius
---




# OIAN

:::{layout-ncol="2"}

### Origin



### Insertion



### Nerve

[Femoral nerve]({{< var ref-femoral-nerve.path >}}) ([L2]({{< var ref-nerve-root.l2 >}}), [L3]({{< var ref-nerve-root.l3 >}}), [L4]({{< var ref-nerve-root.l4 >}})) @gilroyAtlasAnatomy2020

### Action

Knee joint: extension @gilroyAtlasAnatomy2020 

:::

# Notes
    
"The vastus intermedius (see Fig. 19-7) has its origin in the proximal part of the femur, and its line of action is directly in line with the femur.  " @duttonDuttonOrthopaedicExamination2020

"The deepest quadriceps muscle, the vastus intermedius, is located primarily just deep to the rectus femoris and vastus lateralis. Deep to the vastus intermedius is the poorly defined articularis genu. This muscle contains a few slips of fibers that attach proximally to the anterior side of the distal femur, and then distally into the anterior capsule. This muscle pulls the capsule and synovial membrane proximally during active knee extension.303 The articularis genu is analogous to the poorly defined articularis cubiti at the elbow." @duttonDuttonOrthopaedicExamination2020