---
title: Musculoskeletal examination of the Pelvis
---



# Muscular considerations

- Low back stabilizers
- Glutes
- Pelvic floor




# Examination

- Fortin's Test

## Provacative tests

- Gaenslen's

## ROM

- Hip ROM
    - One-Leg Standing (OLS) Test @duttonDuttonOrthopaedicExamination2020
- Lumbopelvic ROM
    - Forward Bending @duttonDuttonOrthopaedicExamination2020 
    - Backward Bending @duttonDuttonOrthopaedicExamination2020 
    - Side Bending @duttonDuttonOrthopaedicExamination2020 


## MM tests

- Thomas Test?


## Functional tests

- Forward Bending (Functional test of the pelvis) p.1430 @duttonDuttonOrthopaedicExamination2020 
- Functional Squat (Functional test of the pelvis) p.1430 @duttonDuttonOrthopaedicExamination2020 
- Alternating Unilateral Standing p.1431 @duttonDuttonOrthopaedicExamination2020 

## Form Closure

p.1431 @duttonDuttonOrthopaedicExamination2020 

## Postural Assessment

- Compare R vs L ASIS
- Compare ASIS vs PSIS
- Compare R vs L PSIS


- Stork Test