---
title: Interleukin 6 (IL-6)
---



# Overview

Interleukin-6 (IL-6) is a member of the pro-inflammatory cytokine family @uciechowskiInterleukin6MasterplayerCytokine2020.

IL-6 functions to induce the expression multiple types of proteins that are responsible for acute inflammation, and plays an important role in the proliferation and differentiation of cells in humans @uciechowskiInterleukin6MasterplayerCytokine2020



:::{.callout-note title="Reference"}

- Interleukin-6: A Masterplayer in the Cytokine Network @uciechowskiInterleukin6MasterplayerCytokine2020
:::

# Structure

- IL-6 is a pleiotropic cytokine @uciechowskiInterleukin6MasterplayerCytokine2020

# Production

IL-6 is primarily produced by Monocytes and Macrophages @uciechowskiInterleukin6MasterplayerCytokine2020.
Other cells also generate IL-6, such as T cells, B cells, hepatocytes, endothelial cells, fibroblasts, keratinocytes, mesangial cells, and adipocytes, as well as several tumor cells @uciechowskiInterleukin6MasterplayerCytokine2020

# Stimulation


# Function
During inflammatory conditions and infections, IL-6 production is induced via stimulation of cells by [IL-1]({{< var ref-interleukin-1.path >}}) or [TNF-&alpha;]({{< var ref-tumor-necrosis-factor-alpha.path >}}) or through stimulation of Toll-like receptors after binding of pathogenic patterns of microbes @uciechowskiInterleukin6MasterplayerCytokine2020.





IL-6 can influence both immune and physiological processes

acute phase protein generation
(e.g., [C-reactive protein (CRP)]({{< var ref-c-reactive-protein.path >}}), hepcidin, etc.), inflammation, antigen-specific immune responses, hematopoiesis, apoptosis, differentiation, and cellular metabolism [4, 6, 7]. 

## Immunopathogenic Functions

"Many studies have described the immunopathogenic function of IL-6 in regulating tumor growth, angiogenesis, apoptosis, metastasis, and therapeutic resistance [1012]. There are various signaling pathways for IL-6, and many of the molecules involved are therapeutic targets to alter IL-6 expression and function in non-malignant diseases and cancer." @uciechowskiInterleukin6MasterplayerCytokine2020


# Mediation

"IL-6 signaling is mediated by building a complex of IL-6, the transmembrane IL-6 receptor (mIL-6R) or with soluble forms of IL-6R (sIL-6R), and the signal-transducing subunit molecule gp130" @uciechowskiInterleukin6MasterplayerCytokine2020


# Dysfunction

Dysfunction in IL-6 regulation, resulint gin increased IL-6 expression has been associated with the pathogenesis of several disorders, including chronic inflammatory diseases, autoimmune diseases, and tumor development @uciechowskiInterleukin6MasterplayerCytokine2020.

# IL-6 Receptors

"In the classic signal cascade, only cells which express the transmembrane 80-kDa α-receptor subunit IL-6R (mIL-6R, CD126) respond to IL-6. The monomeric complex of IL-6 and mIL-6R associates with a ubiquitously expressed 130-kDa β-receptor subunit receptor (gp130, CD130) and results in gp130 dimerization. gp130 is a binding and signal transducer molecule for several members of the IL-6 family (e.g., oncostatin M, IL-11, ciliary neurotrophic factor, cardiotrophin-1, leukemia inhibitory factor, cardiotrophin-like cytokine, IL-27, and IL35) [8, 13]. However, there are also soluble forms with can build a complex with IL-6 and gp130. One soluble form of IL-6R (sIL-6R) can be released by cleavage of the membrane-bound IL-6R by ADAM 10/17 (a disintegrin and metalloprotease domain-containing protein) [14], and another form of sIL-6R through alternative RNA splicing [14]. In addition, a soluble form of gp130 (sgp130) exists, generated by alternative splicing. The mechanisms by which sgp130 influences the signaling pathways of other cytokines than IL-6 have not been elucidated yet."


# IL-6 as a Clinical Test

