---
title: Cancer Pain 
---

# Definition 

Pain associated with cancer includes pain associated with disease progression as well as treatments (e.g., chemotherapy, radiotherapy, surgery) that may damage the nervous system. Although some contend that pain associated with neoplastic disease is unique, in the majority of instances, we view it as fitting within our description of acute and chronic pain, as depicted in Figure 2.1. Moreover, pain associated with cancer can have multiple causes, namely, disease progression, treatment, and co-occurring diseases (e.g., arthritis). Regardless of whether the pain associated with cancer stems from disease progression, treatment, or a cooccurring disease, it may be either acute or chronic. Thus, we do not advocate a separate classification of cancer pain as distinct from acute and chronic pain.
Some concerns have also been raised regarding the common usage of chronic malignant and chronic benign pain4; often, pain unrelated to cancer is implicitly view as “benign” to distinguish it from cancer-related pain. Certainly, people who have pain associated with neoplastic disease experience a unique and disease-specific situation, but from a mechanistic perspective, there may be little to substantiate continued use of this dichotomy. Moreover, patients who have chronic noncancer pain who are told that their pain is “benign” may feel denigrated because, from their perspective, the inference is that their pain is not a serious concern. @ballantyneBonicaManagementPain2019