---
title: Recurrent Pain 
---

Episodic or intermittent occurrences of pain, with each episode lasting for a relatively short period of time but recurring across an extended period of time (e.g., migraine headaches, tic douloureux, sickle cell crisis, dysmenorrhea). Our distinction between acute and chronic pain using the integration of the dimensions of time and pathology does not specifically include recurrent pain. In the case of recurrent pain, patients may experience episodes of pain interspersed with periods of being completely pain-free. Although recurrent pain may seem acute because each pain episode (e.g., headache) is of relatively short duration, the pathophysiology of many recurrent pain disorders (e.g., migraine) is not well understood. Syndromes characterized by recurrent acute pain share features in common with both acute and chronic pain. The fact that these syndromes extend over time, however, suggests that psychosocial and behavioral factors, not only physical pathology, may be major contributors to emotional and behavioral responses. IASP4 now includes recurrent pain lasting longer than 3 months within its definition of chronic pain. However, it is not clear whether multiple episodes lasting several days within 3 months would meet the chronic pain criterion or whether the pain must last at least 3 months. That is, would multiple migraines in a 3-month period be chronic even if there were pain-free periods within the 3 month period? @ballantyneBonicaManagementPain2019