---
title: Lateral Collateral Ligament (LCL)
---


"Lateral (fibular) collateral (see Fig. 20-1). It provides the primary restraint to varus and lateral rotation of the tibia and is a secondary restraint to the anterior and posterior translation of the tibia on the femur." @duttonDuttonOrthopaedicExamination2020 





# Anatomy 

"The LCL, or fibular collateral ligament (see Fig. 20-1), arises from the lateral femoral condyle and runs distally and posteriorly to insert into the head of the fibula. The LCL forms part of the socalled arcuate–ligamentous complex. This complex also comprises the biceps femoris tendon, iliotibial tract, and the popliteus." @duttonDuttonOrthopaedicExamination2020

"The cord-like LCL develops independently and remains completely free from the joint capsule and the lateral meniscus. It is separated from these structures by the popliteus tendon and straddled by the split tendon of the biceps femoris." @duttonDuttonOrthopaedicExamination2020

The LCL can be divided into three parts: 

1. Anterior. This part consists of the joint capsule. 
2. Middle. This part is considered to be part of the iliotibial band (ITB) and covers the capsular ligament.
1. Posterior. This Y-shaped portion of the ligament is part of the arcuate–ligamentous complex, which supports the posterior capsule.


# Function

"The main function of the LCL is to resist varus forces. It offers the majority of the varus restraint at 25 degrees of knee flexion and in full extension.14 Abnormal varus laxity arising subsequent to injuries of the LCL and other P-L structures has been shown to increase stress on cruciate ligament grafts and has been implicated as one of the causes of crucial ligament reconstruction failure.21" @duttonDuttonOrthopaedicExamination2020 

- "The MCL complex acts as the primary restraint to valgus rotation of the tibia, providing as much as 80% of the restraining force to valgus loads.21" @duttonDuttonOrthopaedicExamination2020
- "The LCL provides the primary restraint to varus rotation of the knee, acts as a secondary restraint to external rotation and posterior displacement of the tibia21 and, during normal gait, is the primary passive structure resisting the knee adduction (varus) moment.21" @duttonDuttonOrthopaedicExamination2020