---
title: Medial Collateral Ligament (MCL) of the Knee
---

"Medial (tibial) collateral (see Fig. 20-1). It provides the primary restraint to valgus and lateral rotation of the tibia and is a secondary restraint to the anterior and posterior translation of the tibia on the femur." @duttonDuttonOrthopaedicExamination2020 

# Anatomy

"Both the MCL and the LCL are considered to be extraarticular ligaments. The MCL, or tibial collateral ligament (see Fig. 20-1), develops as a thickening of the medial joint capsule.1 It can be subdivided into a superficial band and a deep band."


## Superficial Band

"The superficial band is a thick, flat band, and has a fan-like attachment proximally on the medial femoral condyle, just distal to the adductor tubercle, from which it extends to the medial surface of the tibia approximately 6 cm below the joint line, covering the medial inferior genicular artery and nerve.1 The superficial band blends with the posteromedial corner of the capsule and, when combined, is referred to as the posterior oblique ligament. The superficial band is separated from the deep layer of the ligament by a bursa. Since the superficial band is farther from the center of the knee, it is the first ligament injured when a valgus stress is applied.19" @duttonDuttonOrthopaedicExamination2020 

## Deep Band

"The deep band (medial capsular ligament) is a continuation of the capsule. It blends with the medial meniscus and consists of an upper meniscofemoral portion and a lower meniscotibial portion." @duttonDuttonOrthopaedicExamination2020 

## Anterior Fibers

"The anterior fibers of the MCL are taut in flexion and can be palpated easily in this position. The posterior fibers, which are taut in extension, blend intimately with the capsule and with the medial border of the medial meniscus, making them difficult to palpate" @duttonDuttonOrthopaedicExamination2020 

# Biomechanics 

"Information regarding the biomechanical function of the collateral ligaments is quite scarce compared with that of the ACL. It would appear that the MCL is the primary stabilizer of the medial side of the knee against valgus forces, and external rotation of the tibia, especially when the knee is flexed." @duttonDuttonOrthopaedicExamination2020 

- "The MCL complex acts as the primary restraint to valgus rotation of the tibia, providing as much as 80% of the restraining force to valgus loads.21" @duttonDuttonOrthopaedicExamination2020
- "The LCL provides the primary restraint to varus rotation of the knee, acts as a secondary restraint to external rotation and posterior displacement of the tibia21 and, during normal gait, is the primary passive structure resisting the knee adduction (varus) moment.21" @duttonDuttonOrthopaedicExamination2020