---
title: CTJ Mobilizations
---


# Dutton Seated technique
Seated technique: @duttonDuttonOrthopaedicExamination2020

- Seated Technique for the Cervicothoracic Junction @duttonDuttonOrthopaedicExamination2020.
- The patient is seated with the arms behind the head @duttonDuttonOrthopaedicExamination2020. 
- The clinician stands in front of the patient and threads the arms through the patient’s arms, before resting both of the hands on the top, and back, of each of the patient’s shoulders @duttonDuttonOrthopaedicExamination2020.
- By gently leaning the patient forward, the cervical spine is extended until the stiff segment is located at the cervicothoracic junction @duttonDuttonOrthopaedicExamination2020.
- Gradually, the clinician increases the amount of cervicothoracic extension by gently kneading the mid-scapular area. Distraction, side flexion, or rotation motions can also be introduced @duttonDuttonOrthopaedicExamination2020.

:::{.callout-caution}
Care should be taken to avoid overextending the lumbar spine during this technique, by pulling the patient too far forward @duttonDuttonOrthopaedicExamination2020.
:::