---
title: Diarthrosis (Synovial) Joint
---


# Characteristics

- Fluid‐filled joint cavity between bones.
- “Synovial Joints” – presence of synovial membrane.
- Designed for movement!

# Examples:

- Majority of Upper and Lower extremity joints.

# 7 Features

1. Synovial Fluid
1. Articular cartilage
1. Articular capsule
1. Synovial membrane
1. Capsular ligaments
1. Blood vessels
1. Sensory nerves

# Possible Features

Synovial joints may contain:

- Intraarticular discs / menisci
- Peripheral labrum
- Fat Pads
- Synovial Plicae

### Intraarticular discs / menisci

- Fibrocartilage between surfaces
- Increase congruency & improve force dispersion

### Peripheral labrum

- Fibrocartilage
- Deepen concave surface & support capsule

### Fat Pads

- Occupy space within capsular tissue
- Reduce synovial volume

### Synovial Plicae

- “Pleats” / slack in the synovial membrane.
- Increase surface area of joint capsule to allow more motion
- Joints with large capsular surface areas.


# Mechanical Classifications

## Hinge

- Flex/Ext 
- Door Hinge

Examples:

- Humeroulnar
- IP joints

## Pivot

- Spin
- Door Knob

Examples:

- Proximal RU
- AA joint

## Ellipsoid

- Flex/Ext + Abd/Add
- Ellipsoid & trough

Examples:

- Radiocarpal

## Ball-and-socket

- Triplanar
- Sphere & cup

Examples:

- GH
- Hip

## Plane

- Slide, ± Rotation
- Book on a table

Examples:

- Intercarpal
- Intertarsal

## Saddle

- Biplanar
- Horse rider & saddle

Examples:

- CMC thumb
- SC joint

## Condyloid

- Biplanar 
- Abstract parallel: Knuckle & cup

Examples:

- MCP
- Tibiofemoral

