---
title: Knee Bursae
---

There are a number of bursae situated in the soft tissues around the knee joint. The bursae serve to reduce friction and to cushion the movement of one body part over another.

# Superficial and Deep Infrapatellar Bursae

"The superficial infrapatellar bursa is located between the patellar tendon and the skin, whereas the deep infrapatellar bursa is located between the patellar tendon and the tibia." @duttonDuttonOrthopaedicExamination2020

## Prepatellar Bursa

"The prepatellar bursa is located between the skin and the anterior aspect of the patella." @duttonDuttonOrthopaedicExamination2020

## Tibiofemoral Bursa

"The tibiofemoral bursae consist of a bursa between the head of the gastrocnemius muscle and the joint capsule on both sides, a bursa between the LCL and both the biceps femoris and popliteus, and a bursa between the MCL and the femoral condyle. There are also a number of bursae between the various tendons of the pes anserinus and between the MCL and the superficial pes anserinus." @duttonDuttonOrthopaedicExamination2020 

"The bursae around the knee can have contact with each other and with the knee joint capsule." @duttonDuttonOrthopaedicExamination2020