---
title: Distal Tibiofibular Joint
---


# Arthrokinematics

:::{layout-ncol="2"}
### Dorsiflexion
According to Dutton, during DF the tibia and fibula are thought to glide superiorly and separate slightly at the distal tibiofibular joint @duttonDuttonOrthopaedicExamination2020. 
The amount of glide appears to be negligible, but some researchers theorize taht distal fibular dysfunction can lead to ankle inversion injuries @duttonDuttonOrthopaedicExamination2020. 

### Plantar Flexion
:::

# Joint Mobility Tests

## Anterior & Posterior Assessments
- Patient positioned in supine
- Grip the tibia and fibula using one hand for each
- To assess the fibula, use one hand to prevent downward motion of the medial malleolus while the opposite hand glides the fibula anteriorly and posteriorly relative to the tibia @duttonDuttonOrthopaedicExamination2020.
- To assess the tibial component, one hand will stabilize the fibula and lateral malleolus, while the opposite hand glides the tibia anteriorly and posteriorly relative to the fibula.

## Superior & Inferior Assessments

In theory, one can assess the superior and inferior glide of the distal tibiofibular joint, but I do not currently have evidence for why this would be clinically relevant @duttonDuttonOrthopaedicExamination2020 


