---
title: Patellofemoral Joint
---


The PFJ is a complex articulation, dependent on both dynamic and static restraints for its function and stability. The patella (Fig. 20-1), a ubiquitous sesamoid bone found in birds and mammals, plays an important role in the biomechanics of the knee. Its articular anatomy is uncomplicated: it is a very hard, triangular-shaped bone, situated in the intercondylar notch and embedded in the tendon of the quadriceps femoris muscle above and the patellar tendon below. The groove has a complex architecture with increasing height of the groove’s lateral facet at the proximal aspect, providing a deeper “patella track” in knee extension.5 In healthy individuals, aspects of the femoral trochlea including its depth, as well as the shape and height of the lateral trochlea, can affect patellar tracking.6,7 From 20 to 30 degrees of knee flexion, the patella is confined within the trochlea and hence, the bony joint components provide inherent stability but, once beyond this range, there is little intrinsic bony support and stability must be provided by other soft-tissue structures, both passively and actively.6 The thickness of the patella varies considerably, attaining a maximum height of 2–2.5 cm (0.77–1 in) at its central portion.1 The posterior surface of the patella can include up to seven facets. The geometry of these facets varies between individuals and may affect patellar tracking.6 A smaller facet, known as the odd facet, exists medially and is delineated by a second vertical ridge. These concave medial and lateral facets are separated by a vertical ridge and are covered with aneural hyaline cartilage, the thickest cartilage in the body (up to 7 mm thick).1 The articular cartilage of the patella is unique because it lacks conformity with the underlying bone.8 The hyaline cartilage, here as elsewhere, functions to minimize the friction that occurs at the functional contact areas of the joint surfaces.



Radiographic and cadaver studies have classified the patella into three Wiberg classifications (type A–C) based on the size and shape of these lateral and medial facets.


The patellar surface of the femur is divided into medial and lateral facets that closely correspond to those on the posterior surface of the patella. The PFJ functions to


provide the articulation with low friction; ▶ protect the distal aspect of the femur from trauma and the quadriceps from attritional wear; ▶ improve the cosmetic appearance of the knee; ▶ improve the moment arm (distance from the center of gravity and the center of rotation) of the quadriceps. This is achieved by elevating the quadriceps femoris muscle from the center of knee rotation. This increases the efficiency of the quadriceps muscle and provides it with leverage for extending the leg. The patellar contribution to the knee extensor moment arm increases with increasing amounts of knee extension; and ▶ decrease the amount of anteroposterior tibiofemoral shear stress placed on the joint.


# Kinetics

"The patellofemoral joint is routinely exposed to high magnitudes of compression force. A sampling of these forces includes 1.3 times body weight during walking on level surfaces, 2.6 times body weight during performance of a straight leg raise, 3.3 times body weight during climbing of stairs, and up to 7.8 times body weight during performance of deep “knee bends” or squats.81,183,270,291 Although these compression forces originate primarily from active forces produced from the overlying quadriceps their magnitude is strongly influenced by the amount of knee flexion at the time of muscle activation.53 To illustrate this important interaction, consider the compression force on the patellofemoral joint in a partial squat position (Fig. 13.28A). Forces within the extensor mechanism are transmitted proximally and distally through the quadriceps tendon (QT) and patellar tendon (PT), much like a cable crossing a pulley. The resultant, or combined, effect of these forces is directed toward the trochlear groove of the femur as a joint compression force (CF). Increasing knee flexion by descending into a deeper squat significantly raises the force demands throughout the extensor mechanism, and ultimately on the patellofemoral joint (see Fig. 13.28B). The increased knee flexion associated with the deeper squat also reduces the angle formed by the intersection of force vectors QT and PT. As shown by vector addition, reducing the angle of these force increases the magnitude of the CF directed between the patella and the femur. In theory, if the QT and PT vectors were collinear and oriented in opposite directions, the muscular-based compression force on the patellofemoral joint would be zero." @neumannKinesiologyMusculoskeletalSystem2017 

## Joint compression

"Both the compression force and the area of articular contact on the patellofemoral joint increase with knee flexion, reaching a maximum between 60 and 90 degrees.139,199,279 As described earlier, the compression force can rise to very high levels during a descent into a squat or lunge position. Because increased knee flexion is associated with a greater relative increase in compression force than relative increase in articular contact area, the stress (force/area) is also greatest in the patellofemoral joint in the position of 60 to 90 degrees of knee flexion.53,261 Without the relatively large contact area to disperse the large compression force produced by the quadriceps, the stress within the joint would likely rise to intolerable physiologic levels.40,111 Having the area of joint contact greatest at positions that are generally associated with the largest muscular-based compression force naturally protects the joint against stress-induced cartilage degeneration. This mechanism allows most healthy and normally aligned patellofemoral joints to tolerate large compression forces over a lifetime, often with little or no appreciable discomfort or degeneration of the articular cartilage or subchondral bone. As will be explained, for many persons, however, the natural high-force environment within the patellofemoral joint is a major contributing factor to the development of patellofemoral pain syndrome." @neumannKinesiologyMusculoskeletalSystem2017 


## Factors affecting Patella Tracking

"The large compression forces that naturally occur at the patellofemoral joint are typically well tolerated, provided that the forces are evenly dispersed across the largest possible area of articular surface. A joint with less than optimal congruity, or one with subtle structural anomalies, will likely experience abnormal “tracking” of the patella. As a consequence, the patellofemoral joint is exposed to higher joint contact stress, thereby increasing its risk for developing degenerative lesions and pain. Such a scenario may lead to patellofemoral pain syndrome or potentially trigger osteoarthritis later in life. " @neumannKinesiologyMusculoskeletalSystem2017 

### Quadricep Role

"Among the most important influences on patellofemoral joint biomechanics are the magnitude and direction of force produced by the overlying quadriceps muscle. As the knee is extending, the contracting quadriceps pulls the patella not only superiorly within the trochlear groove of the femur, but also slightly laterally and posteriorly. The slight but omnipresent lateral line of force exerted by the quadriceps results, in part, from the larger crosssectional area and force potential of the vastus lateralis. Because of the purported association between patellofemoral joint pain and excessive lateral tracking (and possible dislocation) of the patella, assessing the overall lateral line of pull of the quadriceps relative to the patella is a meaningful clinical measure. Such a measure is referred to as the quadriceps angle, or more commonly the Q-angle (Fig. 13.29A).91,244 The Q-angle is determined first by constructing a line representing an estimation of the resultant force vector of the different heads of the quadriceps. This line connects a point between the anterior-superior iliac spine and the midpoint of the patella.310 A second line is drawn representing the long axis of the patellar tendon, made by connecting a point on the tibial tuberosity with the midpoint of the patella. The Q-angle is formed at the intersection of these two lines, typically measuring about 13 to 15 degrees (±4.5 degrees) within a healthy adult population.244 The Q-angle assessment has been criticized for its poor association with pathology at the patellofemoral joint, inadequate standardized measurement protocol, and inability to measure dynamic alignment.124,177,260 Nevertheless, the Q-angle remains a popular and simple clinical index for a general assessment of the relative lateral pull of the quadriceps on the patella. Factors that naturally offset or limit the lateral pull of the patella are described in the next section. If these factors fail to operate in a coordinated fashion, the patella may track (shift and tilt) more laterally within the trochlear groove—kinematics that reduce contact area, increase patellofemoral joint stress and pain, and potentially increase the likelihood of chronic lateral dislocation of the patella." @neumannKinesiologyMusculoskeletalSystem2017 



"Activation of the quadriceps as a whole also pulls and compresses the patella posteriorly against the femur, thereby stabilizing its path of movement relative to the distal femur. This stabilization effect increases with the knee in greater flexion (review Fig. 13.28). Even in full knee extension, however, some fibers of the quadriceps are aligned to produce a posterior compression through the patellofemoral joint.287 This is particularly apparent by observing a side-view diagram of the line of force of the oblique fibers of the vastus medialis (see Fig. 13.29B). Although relatively small, this posterior stabilizing effect on the patella is especially useful in the last 20 to 30 degrees of extension, at a point when (1) the patella is no longer fully engaged within the trochlear groove of the femur and (2) the resultant patellofemoral joint compression (stabilizing) force produced by the activated quadriceps as a whole is least.4"


## Factors That Naturally Oppose the Lateral Pull of the Quadriceps on the Patella

"Several factors throughout the lower extremity oppose and thereby limit the lateral bias in pull of the quadriceps relative to the patellofemoral joint. These factors are important to optimal tracking. In this context, optimal tracking is defined as movement between the patella and femur across the greatest possible area of articular surface with the least possible stress. Understanding the factors that favor optimal tracking provides insight into most pathomechanics and many treatments for pain and other dysfunctions of the patellofemoral joint. Both local and global factors will be described. Local factors are those that act directly on the patellofemoral joint. Global factors, on the other hand, are those related to the alignment of the bones and joints of the lower limb. Although these factors are described as separate entities, in reality, their effectiveness in optimizing patellar tracking is based on the sum of their combined influences." @neumannKinesiologyMusculoskeletalSystem2017 