---
title: Proximal Tibiofibular Joint
---

"The proximal (or superior) tibiofibular joint is a synovial joint located lateral to and immediately inferior to the knee. The joint is formed between the head of the fibula and the posterior-lateral aspect of the lateral condyle of the tibia (see Fig. 13.4). The joint surfaces are generally flat or slightly oval, covered by articular cartilage.175 Although the proximal tibiofibular joint is functionally independent of the knee (tibiofemoral) joint, anatomic connections exist between the capsules of the two joints" @neumannKinesiologyMusculoskeletalSystem2017 

"A capsule strengthened by anterior and posterior ligaments and part of the tendon of the biceps femoris encloses the proximal tibiofibular joint (see Figs. 13.7 and 13.9). The tendon of the popliteus muscle provides additional stabilization as it crosses the joint posteriorly. When stressed by forces and torques generated while walking, 1–3 mm of anterior and posterior translations have been measured at this joint in cadaver specimens.162 The relative stability at this joint is needed to ensure that forces within the biceps femoris and lateral collateral ligament of the knee are transferred effectively from the fibula to the tibia. Although rare, acute dislocation of the proximal tibiofibular joint secondary to trauma has been described in the literature." @neumannKinesiologyMusculoskeletalSystem2017

"The proximal, or superior, tibiofibular joint (see Fig. 20-1) is an almost plane joint with a slight convexity on the oval tibial facet and a slight concavity on the fibular head. The joint is located below the tibial plateau on the lateral condyle of the tibia. The tibial articulating facet faces laterally, posteriorly, and inferiorly. Although the joint is often described as a simple, synovial, modified ovoid, it functions as a modified sellar when combined with the distal, or inferior, tibiofibular joint (see Chapter 21)" @duttonDuttonOrthopaedicExamination2020


"The joint capsule of the proximal tibiofibular joint complex is thicker anteriorly than posteriorly and, in 10% of the population, the synovium is continuous with that of the knee joint.1 The joint receives support from anterior and posterior ligaments and an interosseous membrane. The interosseous membrane attaches between the medial border of the fibula and the lateral border of the tibia, providing attachment to the deep anterior and posterior muscles of the leg. The majority of its fibers pass obliquely in an inferior and lateral direction." @duttonDuttonOrthopaedicExamination2020

"The proximal tibiofibular joint has more motion than its distal partner. The motion occurring at the proximal joint, consists of two glides, one in a superoinferior direction and the other in an anteroposterior direction.1 These motions are possible because of the orientation of the joint line, which also facilitates an osteokinematic spin of the fibula. The motion at this joint can be decreased by articular fibrosis or by softtissue restraints; the biceps femoris can pull or hold it posteriorly, whereas the tibialis anterior can pull or hold it anteriorly." @duttonDuttonOrthopaedicExamination2020

"Although the capsular pattern of restriction for this joint is unclear, it is probably indicated by pain during an isometric contraction of the biceps femoris with the knee at 90 degrees of flexion. The close-packed position for this joint, equally debatable, is probably weight-bearing (WB) ankle dorsiflexion." @duttonDuttonOrthopaedicExamination2020


"Both the tibia and the fibula are vulnerable to fracture at the lower third of their shaft. Anterior joint subluxations occur at this joint as a result of medial knee joint strain or an inversion sprain of the ankle. Posterior joint subluxation can occur as a result of a lateral knee joint strain, but this is often missed because of the more serious ligament damage to the knee." @duttonDuttonOrthopaedicExamination2020

# Innervation {#innervation}

"The nerve supply to this joint is provided by the common fibular (peroneal) and recurrent articular nerves. The joint receives its blood supply from a perforating branch of the fibular (peroneal) artery and the anterior tibial artery." @duttonDuttonOrthopaedicExamination2020



# Arthrokinematics

:::{layout-ncol="2"}

### Dorsiflexion

According to Dutton, during DF the fibula glides superiorly at the proximal tibiofibular joint @duttonDuttonOrthopaedicExamination2020


:::