---
title: Effect Size
---


# Eta Squared ($\eta^2$)

Eta squared measures the proportion of variance that a given variable accounts for out of the total variance in an ANOVA model. It is calculated as:


$$

\eta^2 = \frac{\textrm{SS}_\textrm{effect}}{(\textrm{SS}_\textrm{total})} 

$$

where:

SSeffect: The sum of squares of an effect for one variable.
SStotal: The total sum of squares in the ANOVA model.
When there is only one predictor variable in the model (i.e. a one-way ANOVA), then the value for eta squared and partial eta squared will be equal.

# Partial Eta Squared ($\eta^2$)


Partial eta squared is a way to measure the effect size of different variables in ANOVA models.

It measures the proportion of variance explained by a given variable of the total variance remaining after accounting for variance explained by other variables in the model.

How to Calculate Partial Eta Squared
The formula to calculate Partial eta squared is as follows:

$$

\textrm{partial} \space \eta^2 = \frac{\textrm{SS}_\textrm{effect}}{(\textrm{SS}_\textrm{effect} + \textrm{SS}_\textrm{error})} 

$$

- $\textrm{SS}_\textrm{effect}$: The sum of squares of an effect for one variable.
- $\textrm{SS}_\textrm{error}$: The sum of squares error in the ANOVA model.

Interpretation

- The value for Partial eta squared ranges from 0 to 1
- Values closer to 1 indicate a higher proportion of variance that can be explained by a given variable in the model after accounting for variance explained by other variables in the model.
- The following rules of thumb are used to interpret values for Partial eta squared:

| $\eta^2$ | Interpretation |
|-|-|
|0.01 | Small effect size |
|0.06 | Medium effect size |
| 0.14 or higher | Large effect size |