---
title: Navicular Bone
---

The navicular ("navy") is named after its resemblance to a ship @neumannKinesiologyMusculoskeletalSystem2017.
The navicular articulates proximally with the talus and distally with the cuneiforms @neumannKinesiologyMusculoskeletalSystem2017.


"The navicular is named for its resemblance to a ship (i.e., referring to “navy”). Its proximal (concave) surface accepts the head of the talus at the talonavicular joint (see Fig. 14.4). The distal surface of the navicular bone contains three relatively flat facets that articulate with the three cuneiform bones." @neumannKinesiologyMusculoskeletalSystem2017 


# Navicular Tuberosity

"The medial surface of the navicular has a prominent tuberosity, palpable in the adult at about 2.5 cm inferior and distal (anterior) to the tip of the medial malleolus (see Fig. 14.6). This tuberosity serves as one of several distal attachments of the tibialis posterior muscle." @neumannKinesiologyMusculoskeletalSystem2017

# Palpation

"he navicular is the most prominent bone on the medial aspect of the foot. The navicular tuberosity can be located by moving proximally from the medial aspect of the first cuneiform (see Fig. 21-1). The talonavicular joint line lies directly proximal to the navicular tuberosity. In addition, the posterior tibialis, which can be made more prominent with resisted plantar flexion, adduction, and supination, can be used as a reference as it inserts on the plantar surface of the navicular (see later). Tenderness of the navicular could indicate the presence of a fracture or osteochondritis of the navicular (Köhler disease)." @duttonDuttonOrthopaedicExamination2020 