---
title: Tensor Fascia Latae (TFL)
---

# Overview

| Muscle  | Origin | Insertion | Nerve | Action |
|------|--------|-------|----------|--------|
| [Tensor Fascia Latae]({{< var ref-tensor-fascia-latae.path >}}) | {{< var ref-tensor-fascia-latae.origin >}} | {{< var ref-tensor-fascia-latae.insertion >}} | {{< var ref-tensor-fascia-latae.nerve >}} | {{< var ref-tensor-fascia-latae.action >}} |
: {.striped .hover}

# Origin

ASIS @gilroyAtlasAnatomy2020 

# Insertion

Iliotibial Tract @gilroyAtlasAnatomy2020 


# Innervation

The TFL is innervated by nerve roots [L4]({{< var ref-nerve-root.l4 >}}), [L5]({{< var ref-nerve-root.l5 >}}), and [S1]({{< var ref-nerve-root.s1 >}}), via the [Superior gluteal nerve]({{< var ref-superior-gluteal-nerve.path >}})  @gilroyAtlasAnatomy2020



# Action

- Tenses the fascia latae @gilroyAtlasAnatomy2020
- Hip joint: abduction, flexion, and internal rotation @gilroyAtlasAnatomy2020



# Notes

"The tensor fascia latae (TFL) arises from the outer lip of the iliac crest and the lateral surface of the anterior superior iliac spine (ASIS) (Fig. 19-5). Over the flattened lateral surface of the thigh, the fascia latae thickens to form a strong band, the iliotibial tract. When the hip is flexed, the TFL is anterior to the greater trochanter and helps maintain the hip in flexion. As the hip extends, the TFL moves posteriorly over the greater trochanter to assist with hip extension. The TFL is also a weak extensor of the knee, but only when the knee is already extended. The muscle is innervated by the superior gluteal nerve, L4–L5." @duttonDuttonOrthopaedicExamination2020 


“The tensor fascia latae attach to the ilium just lateral to the sartorius (see Fig. 12.26). This relatively short muscle attaches distally to the proximal part of the iliotibial band. The band extends distally across the knee to attach to the lateral tubercle of the tibia. The iliotibial band is a component of a more extensive connec­tive tissue known as the fascia lata of the thigh.216 Laterally, the fascia lata is thickened by attachments from the tensor fasciae latae and the gluteus maximus. The remainder of the fascia lata encir­ cles the thigh, located within a plane deep to subcutaneous fat. At multiple locations, the fascia lata of the thigh turns inward between muscles, forming distinct fascial sheets known as intermuscular	septa. These septa partition the main muscle groups of the thigh according to innervation. The intermuscular septa of the thigh ultimately attach to the linea aspera on the posterior surface of the femur, along with attachments of most of the adductor muscles and several of the vasti muscles (components of the quadriceps).”  @neuman

“From the anatomic position, the tensor fascia lata is a primary flexor and abductor of the hip. The muscle is often considered a secondary internal rotator,57,162,177 although its leverage for this action is likely only functionally significant when activated from a position of external rotation. As suggested by its name, the tensor fasciae latae increase tension in the fascia lata. Although speculation, activation of the tensor fasciae latae (and theoretically the gluteus maximus and to a lesser extent the psoas minor170) can transmit a force around the thigh and between muscle groups. In some manner, this tensional force within the fascia lata may influ­ ence the function of the underlying thigh muscles. Tension in the fascia lata is most certainly transmitted inferiorly through the iliotibial band and may help stabilize the extended knee. Repeti­ tive tension within the iliotibial band may cause inflammation at its insertion site near the lateral tubercle of the tibia. Maneuvers designed to stretch a tightened tensor fascia lata (which may include the iliotibial band and adjacent tissues) are often per­ formed with the knee extended combined with various combina­ tions of hip adduction and extension.” @neuman 
