---
title: "The Archive"

---

# Anatomy 

- Vasculature
- [Bones]({{< var ref-bone-index.path >}})
- [Muscle OIAN List]({{< var ref-oians.path >}})

::: {.columns}
::: {.column}
[{{< iconify icon-park-outline muscle size=5x >}} </br> Upper extremity Muscles](https://nateyomo.github.io/Yomogida-Kerstein-Lab/The%20Archive/Anatomy/Skeletal%20Muscles/OIAN.html){.btn .btn-outline-primary .btn role="button"}
:::
::: {.column}
[{{< iconify fluent-emoji-high-contrast leg size=5x >}} </br> Upper extremity Muscles](https://nateyomo.github.io/Yomogida-Kerstein-Lab/The%20Archive/Anatomy/Skeletal%20Muscles/OIAN.html){.btn .btn-outline-primary .btn role="button"}
:::
:::

- Connective Tissue
    - Ligaments
- Nervous System
    - [Nerves]({{< var ref-nerve-index.path >}})
    - [Neuroanatomy]({{< var ref-index-neuroanatomy.path >}})

# Biomechanics



# Chemistry


::: {.columns}

::: {.column}
[{{< iconify carbon chemistry size=5x >}} </br> Chemistry](){.btn .btn-outline-primary .btn role="button"}
:::

::: {.column}
[{{< iconify healthicons biochemistry-laboratory size=5x >}} </br> Biochemistry](){.btn .btn-outline-primary .btn role="button"}
:::

::: {.column}
[{{< iconify lets-icons chemistry-light size=5x >}} </br> Organic </br> Chemistry](){.btn .btn-outline-primary .btn role="button"}
:::

:::



# Microbiology

[Microbiology]({{< var ref-microbiology-index.path >}})

- [Cells]({{< var ref-microbiology-index.cell >}})
    - [Chemokines]({{< var ref-microbiology-index.chemokine >}})
- [Enzymes]({{< var ref-microbiology-index.enzyme >}})
- [Proteins]({{< var ref-microbiology-index.protein >}})
- [Non-Proteins]({{< var ref-microbiology-index.non-protein >}})


# Physiology
{{< include Physiology/physiology_index.qmd >}}

- Pathophysiology

# Psychosocial
{{< include "Psychosocial/psychosocial_index.qmd" >}}

# Pain Science
{{< include Pain_science/pain_index.qmd >}}

# Pediatrics
{{< include "/The Archive/Pediatrics/pediatrics_index.qmd" >}}



# Pathologies
{{< include Pathologies/pathologies_index.qmd >}}

# Neuroscience
{{< include Neuroscience/neuro_index.qmd >}}

# Motor control
{{< include "/The Archive/Motor Control/index_motor_control.qmd" >}}

# Genetics & Genomics
{{< include "Genetics and genomics/genetics_and_genomics_index.qmd" >}}

# MSK

{{< include "MSK/MSK_index.qmd" >}}

# Examination
{{< include "Examination/examination_index.qmd" >}}

# Evidence Based Practice
{{< include "/The Archive/Evidene Based Practice/EBP_index.qmd" >}}

# Performance Training

::: {.columns}
::: {.column}
[{{< iconify game-icons wave-surfer size=5x >}} </br> Surfing]({{< var ref-surfing-overview.path >}}){.btn .btn-outline-primary .btn role="button"}
:::
::: {.column}
[{{< iconify fa-solid volleyball-ball size=5x >}} </br> Volleyball](){.btn .btn-outline-primary .btn role="button"}

:::
::: {.column}
:::
:::

{{< include "/The Archive/Performance Training/performance_training_index.qmd" >}}


