---
title: MSK approach to the Ankle
---


# Osteokinematics


## Dorsiflexion


Muscles that assist DF

- Tib Ant
- 


# DDX



# Pathologies


# Strength Tests

- Tib ant: DF/inv
- Tib post: PF/inv
- Fib brev & long: PF/ev
- Fib tertius: DF/ev
- G/S: PF

# Special Tests

## Syndesmosis & Mortise

- Cotton (Clunk) Test. 
    - "The patient lies in the supine position with their foot over the end of the bed. One hand is used to stabilize the distal leg on the bed while the clinician uses the other hand to grasp the heel and move the calcaneus laterally (see Fig. 21-44).93 A clunk can be felt as the talus hits the tibia and fibula if there has been significant mortise widening." @duttonDuttonOrthopaedicExamination2020 
- The Crossed-Leg Test
    - "The crossed-leg test mimics the squeeze test (see later) and attempts to induce separation of the distal syndesmosis.95,98 The patient sits in a chair, with the injured leg resting across the knee of the uninjured leg. The resting point should be at approximately mid-calf. The clinician then applies a gentle force on the medial aspect of the knee of the test leg (Fig. 21-49). Pain experienced in the area of the distal syndesmosis suggests the presence of injury. This test may not be useful for patients with knee or hip pathology because it may be difficult for them to assume the test position. Reliability and validity data for this test are not yet available." @duttonDuttonOrthopaedicExamination2020 
- Squeeze Test
    - "In the squeeze test, the patient lies in supine or side-lying position and the clinician squeezes the lower third of the leg at a point just above the ankle (Fig. 21-52). Pain felt in the distal third of the leg may indicate a compromised syndesmosis (high ankle sprain), if the presence of a tibia and/ or fibula fracture, calf contusion, or compartment syndrome (see Chapter 5) has been ruled out." @duttonDuttonOrthopaedicExamination2020 
- The One-Legged Hop Test
    - "The one-legged hop test is performed by having the patient stand on the injured leg and hop continuously.95 Nussbaum et al.97 reported that patients with syndesmosis injuries could not complete 10 repetitions of unilateral hopping without significant pain. However, the one-legged hop test should be used with caution, and perhaps only if the other special tests are negative because performing this test may impose further separation of the distal tibiofibular syndesmosis.95" @duttonDuttonOrthopaedicExamination2020
- Kleiger Test (External Rotation Test)
    - "The Kleiger (external rotation) test is a general test to implicate the syndesmosis if pain is produced over the anterior or posterior tibiofibular ligaments and the interosseous membrane, but can also be used to assess the integrity of the medial (deltoid) ligament of the ankle complex. If this test is positive, further testing is necessary to determine the source of the symptoms. The patient sits with their legs dangling over the end of the bed; the knee flexed to approximately 90 degrees, and the foot relaxed. The clinician stabilizes the lower leg with one hand and, using the other hand, grasps the foot and externally rotates it (Fig. 21-45). Pain experienced at the anterolateral aspect of the distal tibiofibular syndesmosis is a positive sign for syndesmosis injury, whereas pain on the medial aspect of the ankle and/or displacement of the talus from the medial malleolus (depending on severity) with the ankle positioned in plantar flexion may indicate a tear of the medial (deltoid) ligament of the ankle." @duttonDuttonOrthopaedicExamination2020 
- The Point Test
    - "The point test also referred to as the palpation test, is used to impose pressure on the anterior distal tibiofibular syndesmosis.94,95 The patient can be positioned in supine or sitting. The clinician applies pressure directly to the anterior aspect of the distal tibiofibular syndesmosis (Fig. 21-46). Pressure is applied gradually, and a positive test involves a report of pain by the patient." @duttonDuttonOrthopaedicExamination2020 
- The Dorsiflexion Compression Maneuver
    - "The dorsiflexion compression maneuver is performed to force the wider anterior portion of the talar dome into the ankle mortise, thereby inducing separation of the distal fibula and tibia. The patient sits at the edge of the examination table, and the clinician stabilizes the patient’s leg with one hand, while the clinician’s other hand passively moves the foot into dorsiflexion (Fig. 21-47). Pain experienced at the distal tibiofibular syndesmosis is a positive test result. A variation of the dorsiflexion maneuver exists, known as the dorsiflexion compression test, which involves patients moving their ankle joints into extreme dorsiflexion in bilateral weight-bearing. Patients are asked to note the pain they experience in this position and the position of the tibia is noted with an inclinometer. The patient then assumes an upright position and the clinician applies medial–lateral compression with two hands on the malleoli of the injured leg. The clinician maintains the medial–lateral compression, as the patient is asked to move the ankles into dorsiflexion again and to report if the endrange pain has changed compared with the previous movement. A positive test result is either a reported reduction in the end-range pain or an increase in dorsiflexion ROM." @duttonDuttonOrthopaedicExamination2020 
- Fibula Translation Test
    - "The patient is placed in the side-lying position with the tested leg uppermost. The clinician applies an anterior and posterior force on the fibula at the level of the syndesmosis (Fig. 21-48). A positive test is a pain during translation and more displacement of the fibula than the compared side. Although a cadaver study by Beumer et al.96 found this test to have a sensitivity of 82% and specificity of 88% (LR+ 6.8; LR− 0.2), the study only found increased translation when all ligaments were removed in the cadavers."
- Heel-Thump Test
    - "The heel-thump test is performed to force the talus into the mortise, in an attempt to impose a separation of the distal syndesmosis.95,99 The patient lies at the edge of the examination table, with the ankle resting in plantar flexion. The clinician holds the patient’s leg with one hand and with the other hand applies a gentle but firm thump on the heel with their fist (Fig. 21-50). This force is applied at the center of the heel and in line with the long axis of the tibia. Pain experienced at the distal tibiofibular syndesmosis suggests the presence of injury. Although the heel thump test has been recommended to help differentiate between a syndesmotic sprain and a lateral ankle sprain, this test may not be specific for a syndesmotic sprain as the test has also been recommended to assess the possible presence of tibial stress fractures.100 Reliability and validity data for this test are not yet available." @duttonDuttonOrthopaedicExamination2020
- Posterior Drawer Test
    - "The posterior drawer test can also be used to test for the presence of instability at the distal tibiofibular joint. The patient is supine. The hip and knee are flexed to provide as much dorsiflexion of the ankle as possible. This drives the wide anterior part of the talus back into the mortise. An anterior stabilizing force is then applied to the cruris, and the foot and talus are translated posteriorly (Fig. 21-51). If the distal tibiofibular joint is stable, there will be no drawer available, but if there is instability, there will be a drawer." @duttonDuttonOrthopaedicExamination2020 

## Lateral Collaterals

"The lateral collateral ligaments of the ankle resist inversion. An additional function is to prevent excessive varus movement, especially during plantar flexion. In extreme plantar flexion, the mortise no longer stabilizes the broader anterior part of the talus, and varus movement of the ankle is then possible." @duttonDuttonOrthopaedicExamination2020 

- Calcaneus Tilt
    - "The patient lies in the supine position. The lower leg is stabilized using a lumbrical grip while the other hand grasps the foot and calcaneus. The clinician applies a medially directed force in an attempt to adduct the calcaneus, thereby gapping the lateral side of the ankle (Fig. 21-53). Pain on the lateral aspect of the ankle with this test, and/or displacement (depending on severity) may indicate a sprain of the ligament." @duttonDuttonOrthopaedicExamination2020 
- Talar Tilt
    - "This test is used to determine whether the CFL is torn. The patient lies in a supine or side-lying position with the foot relaxed and the knee flexed. The clinician places the foot in the anatomical (90 degrees) position to bring the CFL perpendicular to the long axis of the talar. The talus is then tilted from side to side into adduction and abduction (Fig. 21-54). Adduction tests the CFL and, to some degree, the ATFL, whereas abduction stresses the deltoid ligament. No diagnostic accuracy studies have been performed to determine the sensitivity and specificity of this test." @duttonDuttonOrthopaedicExamination2020
- Anterior Drawer Test
    - "The anterior drawer stress test is performed to estimate the stability of the ATFL. The test is performed with the patient seated at the end of the bed or lying supine with their knee flexed, to relax the gastrocnemiussoleus muscles, and the foot supported perpendicular to the leg. The clinician uses one hand to stabilize the distal aspect of the leg, while the other hand grasps the patient’s heel and positions the ankle in 10–20 degrees of plantar flexion (Fig. 21-55). Either the heel is very gently pulled forward, or the clinician can manually apply a posterior force on the tibia. The clinician attempts to visually and manually assess the quantity of talar movement and to determine if an asymmetry exists between the involved and the uninvolved ankle. If the test is positive, the talus, and with it the foot, rotates anteriorly out of the ankle mortise around the intact medial (deltoid) ligament of the ankle, which serves as the center of rotation. Variances in hand position, joint congruency, forces imparted, the perception of movement, scoring methods, and tissue variability are factors that may affect the reliability of this test.101" @duttonDuttonOrthopaedicExamination2020 
    - "It has been reported that 4 mm of laxity in the ATFL, resulting from posttraumatic attenuation or fibrosis, will give a clinically apparent anterior drawer (2 mm is normal)false-positive findings may be seen in up to 19% of uninjured ankles in those with ligamentous laxity.102,103 As is often the case, when combining the results from several tests, diagnostic accuracy can be enhanced. For example, a 2013 study by Croy et al.102 reported that when the combination of pain on lateral ligament palpation, hematoma formation of the lateral ankle, and a positive anterior drawer test were used a lateral ligament lesion was correctly diagnosed in 95% of cases." @duttonDuttonOrthopaedicExamination2020 
- The Dimple Sign
    - "Another positive sign for a rupture of the ATFL, if pain and spasm are minimal, is the presence of a dimple located just in front of the tip of the lateral malleolus during the anterior drawer test. This results from a negative pressure created by the forward movement of the talus, which draws the skin inwards at the site of the ligament rupture. This dimple is also seen with a combined rupture of the ATFL and CFLs. However, the dimple is only present within the first 48 hours after injury, due to organized hematoma and repair tissue blocking the communication between the joint and the subcutaneous tissues." @duttonDuttonOrthopaedicExamination2020 

## Medial Collaterals (Deltoid Complex)

"The medial collaterals function to resist eversion. Given their strength, these ligaments are usually only injured as the result of a major trauma." @duttonDuttonOrthopaedicExamination2020 

## Tendon 


# Examination

## ROM

- Ankle DF ROM




## Lateral ankle

- PTFL
    - a
- CFL
    - a
- ATFL
    - Ant drawer?

## Medial Ankle (Deltoid ligament)

- j