---
title: Hip examination and treatment
---


# Lumbopelvic Movement

:::{layout-ncol="3"}
### pelvic pronation
lumbopelvic hip complex during ground impact is a combination of 3-D shock-absorbing movements driving the pelvis into an anterior tilt, forward rotation, contralateral drop, and concomitant spinal extension/rotation and relative sacral nutation. Triplanar pelvic motion is analogous to pronation at the foot—an important mechanism for absorbing ground reaction forces6 and a key antecedent for effective propulsion during gait @dischiaviRethinkingDynamicKnee2019
:::

# Testing

## Functional Tests

- Squat Analysis
- Deep Squat Test


## Femoroacetabular Impingement & Labral Pathology Tests 

- Flexion-Adduction-Internal Rotation (FADDIR) @wongPhysicalExaminationHip2022 
- Scour Test (Labral Stress Test) @wongPhysicalExaminationHip2022 
- Internal Rotation Over Pressure (IROP) @wongPhysicalExaminationHip2022 
- Posterior Impingement Test
- Flexion-Abduction-External Rotation (FABER/Patrick Sign)

## Other/Extra-Articular Maneuvers

- Resisted Straight Leg Raise (Stinchfield Test) @wongPhysicalExaminationHip2022 
- Thomas Test @wongPhysicalExaminationHip2022 
- Gear Stick Sign @wongPhysicalExaminationHip2022 

## Microinstability

## Provocative maneuvers
In addition to astandardexamofthehip,thereareanumberofprovocative maneuvers that assess apprehension, range of motion, and joint stability

- Anterior Apprehension Test (Hyperextension, External Rotation Test) @wongPhysicalExaminationHip2022 
- Abduction-Extension-External Rotation Test @wongPhysicalExaminationHip2022 
- Prone External Rotation Test @wongPhysicalExaminationHip2022 
- Log Roll Test (Dial Test) @wongPhysicalExaminationHip2022 
- Posterior Apprehension Test @wongPhysicalExaminationHip2022 
- Axial Distraction Test @wongPhysicalExaminationHip2022 