---
title: Atlanto-Axial Joint
---

The atlanto-axial joint complex has two articular components: a median joint and a pair of laterally positioned apophyseal joints. The median joint is formed by the dens of the axis (C2) projecting through an osseous-ligamentous ring created by the anterior arch of the atlas and the transverse ligament (Fig. 9.43). Because the dens serves as a vertical axis for horizontal plane rotation of the atlas, the atlanto-axial joint is often described as a pivot joint.


The median joint within the atlanto-axial joint complex has two synovial cavities. The smaller, anterior cavity is formed between the anterior side of the dens and the posterior border of the anterior arch of the atlas (see Fig. 9.43). An anterior facet on the anterior side of the dens marks this articulation (see Fig. 9.20A). The much larger posterior cavity separates the posterior side of the dens and a cartilage-lined section of the transverse ligament of the atlas. This strong, 2-cm long ligament is essential to the horizontal plane stability of the atlanto-axial articulation.35 Without its restraint, the atlas (and articulated cranium) can slip anteriorly relative to the axis, possibly damaging the spinal cord.