---
title: Occipitoatlanto Joint (OAJ)
---

# Overview

The atlanto-occipital joints provide independent movement of the cranium relative to the atlas (C1) @neumannKinesiologyMusculoskeletalSystem2017.

# Anatomy

The joints are formed by the protruding convex condyles of the occipital bone fitting into the reciprocally concave superior articular facets of the atlas @neumannKinesiologyMusculoskeletalSystem2017.

### Joint Capsule


# Stability

### Structural stability

The convex-concave relationship provides inherent structural stability to the articulation @neumannKinesiologyMusculoskeletalSystem2017. 



Anteriorly, the capsule of each atlanto-occipital joint blends with the anterior atlanto-occipital membrane (Fig. 9.41). Posteriorly, the capsule is covered by a thin, broad posterior atlantooccipital membrane (Fig. 9.42). As depicted on the right side of Fig. 9.42, the vertebral artery pierces the posterior atlanto-occipital membrane to enter the foramen magnum. This crucial artery supplies blood to the brain.

The concave-convex structure of the atlanto-occipital joints permits angular rotation primarily in two degrees of freedom. The primary motions are flexion and extension. Lateral flexion is slight. Axial rotation is very limited and usually not considered as the third degree of freedom.