---
title: Golf Injuries
---


Golf injuries can include either overuse or traumatic injuries @mchardyGolfInjuriesReview2006

Upper limb injuries are also common due to their role in linking the fast moving golf club with the power-generating torso. 

# Professional Golf Injuries
Professional golfers primarily experience overuse injuries @mchardyGolfInjuriesReview2006

Overall injury rates do not have a consensus, but include the following:

- Left wrist (for Right handers) @mchardyGolfInjuriesReview2006
- Low back @mchardyGolfInjuriesReview2006
- Neck @mchardyGolfInjuriesReview2006

## Gender differences
Most common sites of injury for professsional male golfers were:

1. Low back @mchardyGolfInjuriesReview2006
1. Left Wrist (for right handers) @mchardyGolfInjuriesReview2006
1. Left shoulder (for right handers) @mchardyGolfInjuriesReview2006

Female professionals common injuries:

1. Left wrist (For right handers) @mchardyGolfInjuriesReview2006
1. Low back @mchardyGolfInjuriesReview2006
1. Left hand (For R-handers) @mchardyGolfInjuriesReview2006

## Causes
Professionals generally have good golf mechanics so the chance of them injuring themselves due to an improper swing is very low

Professional golfers generally experience injury due to excessive practice @mchardyGolfInjuriesReview2006.
Since the professional's income and career achievement is based on golf, they are more likely to re-aggravate existing injuries compared to an amateur @mchardyGolfInjuriesReview2006.




# Amateur golfers

Amateur golfers primarily experience injury secondary to incorrect golf swing mechanics @mchardyGolfInjuriesReview2006

Common injury sites in amateur golfers:

- Low back
- Wrist
- Elbow
- Shoulder

## Gender

Differing research exists, whether low back or wrist is the most common injured site in amateur males @mchardyGolfInjuriesReview2006.

The most common injury site in amateur females was the elbow @mchardyGolfInjuriesReview2006.

## Causes

Most elbow injuries were diagnosed as [Lateral epicondylitis (tennis elbow)]({{< var ref-lateral-epicondylitis.path >}}) and usually occurred in the non-dominant elbow (L elbow for R-hand golfers) @mchardyGolfInjuriesReview2006

the most common MOI:

- Overuse injury
- Poor swing biomechanics
- Hitting the ground during the swing

# Amateur vs Professional



# Injury Type

## Overuse injury

More common are the overuse injuries associated with the back, neck and shoulder @mchardyGolfInjuriesReview2006

## Injury location

# Specific injury sites

## Low Back injuries
Many studies report the low back to be the most commonly injured site in golf (~23.7–34.5% of all injuries) @mchardyGolfInjuriesReview2006

Incorrect swing/miss is the most common method to injury the back @mchardyGolfInjuriesReview2006

The mechanics of the golf swing place a large range of motion and force on the low back such as:

- Downward compression @mchardyGolfInjuriesReview2006
- Side-to-side Bending @mchardyGolfInjuriesReview2006
- Sliding, back to front shearing @mchardyGolfInjuriesReview2006

Peak load during a golf swing on the low back is 8xBW, as opposed to 7xBW while rowing and 3xBW while jogging @mchardyGolfInjuriesReview2006.


### Low back Amateur vs Professional

- Amateurs use 10% more peak muscle force during swing, which places more load on the lumbar spine @mchardyGolfInjuriesReview2006
- Amateurs and professionals experience similar compressional loads @mchardyGolfInjuriesReview2006
- Amateurs experienced 80% more lateral bending and peak shear loads @mchardyGolfInjuriesReview2006
- Amateurs displayed 50% more torque @mchardyGolfInjuriesReview2006

## Wrist/Hand injuries
Incorrect swing/miss is the most common method to injure the wrist @mchardyGolfInjuriesReview2006

## Elbow injuries

## Shoulder injuries

## Knee injuries

# Major injuries: Head & Eye

# Other injuries
## Stress Fx