---
title: Calcaneocuboid Joint
---


The calcaneocuboid joint is a plane synovial joint @duttonDuttonOrthopaedicExamination2020 

"The anterior surface of the calcaneus, which articulates with the reciprocally shaped posterior surface of the cuboid, is relatively convex in an oblique horizontal direction and relatively concave in an oblique vertical direction.8 The cuboid, most lateral in the distal tarsal row, is located between the calcaneus proximally and the fourth and fifth metatarsals distally. To the posterior (dorsal) surface are attached posterior (dorsal) calcaneocuboid, cubonavicular, cuneocuboid, and cubometatarsal ligaments, and to the proximal edge of the plantar ridge, deep fibers of the long plantar ligament. To the projecting proximal–medial part of the plantar surface are attached a slip of the tendon of tibialis posterior and flexor hallucis brevis (FHB). To the rough part of the medial cuboidal surface are attached the interosseous, cuneocuboid, and cubonavicular ligaments, and proximally the medial calcaneocuboid ligament, which is the lateral limb of the bifurcated ligament.8 The capsule is thickened posteriorly (dorsally) to form the posterior (dorsal) calcaneocuboid ligament. The joint has a large plantar phalanx to provide additional support during weight-bearing. A number of ligaments help provide support to this region. The spring ligament (plantar calcaneonavicular Fig. 21-3) connects the navicular bone to the sustentaculum tali on the calcaneus. The ligaments of the calcaneocuboid joint include the long plantar ligament and a portion of the bifurcate ligament posterior (dorsally)." @duttonDuttonOrthopaedicExamination2020 


"The long and strong plantar ligament attaches to the plantar surface of the calcaneus, the tuberosity on the plantar surface of the cuboid bone, and to the bases of the second, third, and fourth (and possibly fifth) metatarsals.8 The plantar ligament functions to provide indirect plantar support to the joint, by limiting the amount of flattening of the lateral longitudinal arch of the foot. Together with the groove in the cuboid bone, it forms a tunnel for the passage of the fibularis (peroneus) longus tendon across the plantar surface of the foot.8 The perpendicular arrangement of the long and short plantar ligaments may compress the calcaneocuboid joint increasing its stability.11 During inversion, the cuboid inverts approximately twice as much as the calcaneus.19" @duttonDuttonOrthopaedicExamination2020 

"The bifurcate ligament functions to support the medial and lateral aspects of the foot when weight-bearing in a plantar flexed position (twisted)." @duttonDuttonOrthopaedicExamination2020 

"The plantar calcaneocuboid ligament, sometimes referred to as the short plantar ligament, is a relatively broad and strong strap-like structure that extends from the area of the anterior tubercle of the calcaneus to the adjacent plantar surface of the cuboid bone. It provides plantar support to the joint and possibly helps to limit flattening of the lateral longitudinal arch." @duttonDuttonOrthopaedicExamination2020 