---
title: C3 Nerve Root (C3)
---


# Motor Innervation

```{r}
#| echo: false
#| warning: false
#| message: false

# Load the here package
library(here)

# Source the functions script
source(here("scripts/functions.R"))

# Example usage
identifier_col <- "root_identifier"  # or "group_identifier"
filter_patterns <- "C3"
display_columns <- c("name_final", "origin_final", "insertion_final", "innervation_final", "action_final")
table_title <- "C3 Nerve Root Skeletal Muscle Innervations"

# Call the function
gt_table <- gt_oian(identifier_col, filter_patterns, display_columns, table_title)

gt_table
```

# Lesion

"Sensory disturbances occur on the lower occiput, the angle of the jaw, and the upper neck [28]. Paresis may occur in the scalene and levator scapulae muscles of the neck (including the infrahyoids, semispinalis capitis and cervicis, longissimus capitis and cervicis, intertransversarii, rotatores, multifidi), and in the trapezius (shoulder elevation), this last muscle being predominantly innervated by the spinal accessory nerve (cranial nerve XI). Diaphragmatic paresis may also result because the phrenic nerve receives some of its fibers from the C3 segment." @brazisLocalizationClinicalNeurology2022

"Irritation of the C3 nerve root may cause a painful, burning, red ear (red ear syndrome) [15]. The increased ear temperature may be caused by antidromic release of vasodilator peptides. This red ear syndrome may also occur with temporomandibular joint dysfunction and with thalamic lesions [15]." @brazisLocalizationClinicalNeurology2022