---
title: C5 Nerve Root
---

# Contribution

C5 and [C6]({{< var ref-nerve-root.c6 >}}) contribute to the [Superior trunk]({{< var ref-brachial-plexus.superior-trunk >}}) of the [brachial plexus]({{< var ref-brachial-plexus.path >}}).

# Motor Innervation

```{r}
#| echo: false
#| warning: false
#| message: false

# Load the here package
library(here)

# Source the functions script
source(here("scripts/functions.R"))

# Example usage
identifier_col <- "root_identifier"  # or "group_identifier"
filter_patterns <- "C5"
display_columns <- c("name_final", "origin_final", "insertion_final", "innervation_final", "action_final")
table_title <- "C5 Nerve Root Skeletal Muscle Innervations"

# Call the function
gt_table <- gt_oian(identifier_col, filter_patterns, display_columns, table_title)

gt_table
```

# Lesion

"C5 nerve root involvement results in neck, shoulder, and upper anterior arm pain. Sensory disturbances occur on the lateral arm with these lesions. Paresis occurs predominantly and variably in the following muscles: levator scapulae, rhomboids, serratus anterior, supraspinatus, infraspinatus, deltoid, biceps, and brachioradialis (for methods of examination of each of these muscles, see Chapter 2 ). Diaphragmatic paresis may rarely occur owing to C5 fibers reaching the phrenic nerve. The biceps reflex (subserved by segments C5 C6) and the brachioradialis reflex (C5 C6) may be depressed." @brazisLocalizationClinicalNeurology2022


# DDX

:::{layout-ncol="3"}
### Level
C4/C5 @hongReliabilityDiagnosticAccuracy2022

### Sensation
Deltoid and lateral arm @hongReliabilityDiagnosticAccuracy2022 

### Motor

- Deltoid @hongReliabilityDiagnosticAccuracy2022
- Biceps @hongReliabilityDiagnosticAccuracy2022

### Abnormal DTR
Bicep reflex @hongReliabilityDiagnosticAccuracy2022

:::