---
title: C6 Nerve Root
---


| Level | Root | Pain & Sensory Change | Motor Weakness | Abnormal Reflexes |
|-|-|---|--|-|
| C4/C5 | C5 | Deltoid @hongReliabilityDiagnosticAccuracy2022 <br> Lateral arm @hongReliabilityDiagnosticAccuracy2022 | Deltoid @hongReliabilityDiagnosticAccuracy2022 <br> Biceps @hongReliabilityDiagnosticAccuracy2022 | Bicep reflex @hongReliabilityDiagnosticAccuracy2022 |
| C5/C6 | C6 | Radial forearm to thumb and index finger @hongReliabilityDiagnosticAccuracy2022 | Biceps @hongReliabilityDiagnosticAccuracy2022 <br> Wrist extensor @hongReliabilityDiagnosticAccuracy2022 | Bicep reflex @hongReliabilityDiagnosticAccuracy2022 <br> Brachioradialis reflex @hongReliabilityDiagnosticAccuracy2022 |
| C6/C7 | C7 | Midradial forearm to index and middle finger @hongReliabilityDiagnosticAccuracy2022 | Wrist Flexor @hongReliabilityDiagnosticAccuracy2022 <br> Tricep @hongReliabilityDiagnosticAccuracy2022 | Triceps reflex @hongReliabilityDiagnosticAccuracy2022 |
| C7/T1 | C8 | Ulnar forearm to ring and little finger @hongReliabilityDiagnosticAccuracy2022 | Hand Intrinsic @hongReliabilityDiagnosticAccuracy2022 <br> Finger Flexor @hongReliabilityDiagnosticAccuracy2022 | N/a @hongReliabilityDiagnosticAccuracy2022 |

: {.striped .hover}

# Contribution

C6 along with [C5]({{< var ref-nerve-root.c5 >}}) contribute to the [Superior trunk]({{< var ref-brachial-plexus.superior-trunk >}}) of the [brachial plexus]({{< var ref-brachial-plexus.path >}}).

# Lesion

"This nerve root is often compressed by disc herniation at the C5 C6 vertebral level. A monoradiculopathy affecting the C6 nerve root is the second most common level of cervical radiculopathy after lesions of the C7 level [28]. C6 root involvement results in pain in the lateral arm and dorsal forearm. Sensory signs and symptoms occur on the lateral forearm, lateral hand, and the first and second digits. Paresis occurs predominantly in the following muscles: serratus anterior, biceps, pronator teres, flexor carpi radialis, brachioradialis, extensor carpi radialis longus, supinator, and extensor carpi radialis brevis (examination of these muscles is described in Chapter 2 ). The biceps reflex (segments C5 C6) and the brachioradialis reflex (segments C5 C6) may be depressed. An “inverted radial reflex” occurs when the lesion causes compression of the spinal cord at the C5 C6 level. A central disc prolapse or a horizontal bar due to degenerative disc disease is often responsible for this clinical finding. Damage of the corticospinal tract at the level of C5 C6 results in hyperreflexia at lower levels. Therefore, tapping the tendon of the brachioradialis muscle elicits no response by the brachioradialis but a brisk contraction of the finger flexors innervated by the C8 T1 segments." @brazisLocalizationClinicalNeurology2022 