---
title: L5 Nerve Root (L5)
---

# Peripheral Nerve Supply

| Nerve | Roots | Motor Innervation | Cutaneous Innervation |
|-|-|---|-|
| [Superior Gluteal N.]({{< var ref-superior-gluteal-nerve.path >}}) | {{< var ref-superior-gluteal-nerve.roots >}} | {{< var ref-superior-gluteal-nerve.motor >}} | {{< var ref-superior-gluteal-nerve.cutaneous >}} |
| [Inferior Gluteal N.]({{< var ref-inferior-gluteal-nerve.path >}}) | {{< var ref-inferior-gluteal-nerve.roots >}} | {{< var ref-inferior-gluteal-nerve.motor >}} | {{< var ref-inferior-gluteal-nerve.cutaneous >}} |
| [Posterior Cutaneous Nerve of the Thigh]({{< var ref-posterior-cutaneous-nerve-of-the-thigh.path >}}) | {{< var ref-posterior-cutaneous-nerve-of-the-thigh.roots >}} | {{< var ref-posterior-cutaneous-nerve-of-the-thigh.motor >}} | {{< var ref-posterior-cutaneous-nerve-of-the-thigh.cutaneous >}} |
| [Sciatic N.]({{< var ref-sciatic-nerve.path >}}) | {{< var ref-sciatic-nerve.roots >}} | {{< var ref-sciatic-nerve.motor >}} | {{< var ref-sciatic-nerve.cutaneous >}} |
| [Common Fibular N.]({{< var ref-common-fibular-nerve.path >}}) | {{< var ref-common-fibular-nerve.roots >}} | {{< var ref-common-fibular-nerve.motor >}} | {{< var ref-common-fibular-nerve.cutaneous >}} |
| [Tibial N.]({{< var ref-tibial-nerve.path >}}) | {{< var ref-tibial-nerve.roots >}} | {{< var ref-tibial-nerve.motor >}} | {{< var ref-tibial-nerve.cutaneous >}} |
: {.striped .hover}

# Muscle Supply

| Muscle  | Origin | Insertion | Nerve | Action |
|------|--------|-------|----------|--------|
| [Gluteus Maximus]({{< var ref-gluteus-maximus.path >}}) | {{< var ref-gluteus-maximus.origin >}} | {{< var ref-gluteus-maximus.insertion >}} | {{< var ref-gluteus-maximus.nerve >}} | {{< var ref-gluteus-maximus.action >}} |
| [Gluteus Medius]({{< var ref-gluteus-medius.path >}}) | {{< var ref-gluteus-medius.origin >}} | {{< var ref-gluteus-medius.insertion >}} | {{< var ref-gluteus-medius.nerve >}} | {{< var ref-gluteus-medius.action >}} |
| [Gluteus Minimus]({{< var ref-gluteus-minimus.path >}}) | {{< var ref-gluteus-minimus.origin >}} | {{< var ref-gluteus-minimus.insertion >}} | {{< var ref-gluteus-minimus.nerve >}} | {{< var ref-gluteus-minimus.action >}} |
| [Tensor Fascia Latae]({{< var ref-tensor-fascia-latae.path >}}) | {{< var ref-tensor-fascia-latae.origin >}} | {{< var ref-tensor-fascia-latae.insertion >}} | {{< var ref-tensor-fascia-latae.nerve >}} | {{< var ref-tensor-fascia-latae.action >}} |
| [Obturator Internus]({{< var ref-obturator-internus.path >}}) | {{< var ref-obturator-internus.origin >}} | {{< var ref-obturator-internus.insertion >}} | {{< var ref-obturator-internus.nerve >}} | {{< var ref-obturator-internus.action >}} |
| [Superior Gemellus]({{< var ref-superior-gemellus.path >}}) | {{< var ref-superior-gemellus.origin >}} | {{< var ref-superior-gemellus.insertion >}} | {{< var ref-superior-gemellus.nerve >}} | {{< var ref-superior-gemellus.action >}} |
| [Inferior Gemellus]({{< var ref-inferior-gemellus.path >}}) | {{< var ref-inferior-gemellus.origin >}} | {{< var ref-inferior-gemellus.insertion >}} | {{< var ref-inferior-gemellus.nerve >}} | {{< var ref-inferior-gemellus.action >}} |
| [Quadratus Femoris]({{< var ref-quadratus-femoris.path >}}) | {{< var ref-quadratus-femoris.origin >}} | {{< var ref-quadratus-femoris.insertion >}} | {{< var ref-quadratus-femoris.nerve >}} | {{< var ref-quadratus-femoris.action >}} |
| [Biceps Femoris Long Head]({{< var ref-biceps-femoris-long-head.path >}}) | {{< var ref-biceps-femoris-long-head.origin >}} | {{< var ref-biceps-femoris-long-head.insertion >}} | {{< var ref-biceps-femoris-long-head.nerve >}} | {{< var ref-biceps-femoris-long-head.action >}} |
| [Biceps Femoris Short Head]({{< var ref-biceps-femoris-short-head.path >}}) | {{< var ref-biceps-femoris-short-head.origin >}} | {{< var ref-biceps-femoris-short-head.insertion >}} | {{< var ref-biceps-femoris-short-head.nerve >}} | {{< var ref-biceps-femoris-short-head.action >}} |
| [Semitendinosus]({{< var ref-semitendinosus.path >}}) | {{< var ref-semitendinosus.origin >}} | {{< var ref-semitendinosus.insertion >}} | {{< var ref-semitendinosus.nerve >}} | {{< var ref-semitendinosus.action >}} |
| [Semimembranosus]({{< var ref-semimembranosus.path >}}) | {{< var ref-semimembranosus.origin >}} | {{< var ref-semimembranosus.insertion >}} | {{< var ref-semimembranosus.nerve >}} | {{< var ref-semimembranosus.action >}} |
| [Tibialis Anterior]({{< var ref-tibialis-anterior.path >}}) | {{< var ref-tibialis-anterior.origin >}} | {{< var ref-tibialis-anterior.insertion >}} | {{< var ref-tibialis-anterior.nerve >}} | {{< var ref-tibialis-anterior.action >}} |
| [Extensor Hallucis Longus]({{< var ref-extensor-hallucis-longus.path >}}) | {{< var ref-extensor-hallucis-longus.origin >}} | {{< var ref-extensor-hallucis-longus.insertion >}} | {{< var ref-extensor-hallucis-longus.nerve >}} | {{< var ref-extensor-hallucis-longus.action >}} |
| [Extensor Digitorum Longus]({{< var ref-extensor-digitorum-longus.path >}}) | {{< var ref-extensor-digitorum-longus.origin >}} | {{< var ref-extensor-digitorum-longus.insertion >}} | {{< var ref-extensor-digitorum-longus.nerve >}} | {{< var ref-extensor-digitorum-longus.action >}} |
| [Fibularis Tertius]({{< var ref-fibularis-tertius.path >}}) | {{< var ref-fibularis-tertius.origin >}} | {{< var ref-fibularis-tertius.insertion >}} | {{< var ref-fibularis-tertius.nerve >}} | {{< var ref-fibularis-tertius.action >}} |
| [Fibularis Longus]({{< var ref-fibularis-longus.path >}}) | {{< var ref-fibularis-longus.origin >}} | {{< var ref-fibularis-longus.insertion >}} | {{< var ref-fibularis-longus.nerve >}} | {{< var ref-fibularis-longus.action >}} |
| [Fibularis Brevis]({{< var ref-fibularis-brevis.path >}}) | {{< var ref-fibularis-brevis.origin >}} | {{< var ref-fibularis-brevis.insertion >}} | {{< var ref-fibularis-brevis.nerve >}} | {{< var ref-fibularis-brevis.action >}} |
| [Tibialis Posterior]({{< var ref-tibialis-posterior.path >}}) | {{< var ref-tibialis-posterior.origin >}} | {{< var ref-tibialis-posterior.insertion >}} | {{< var ref-tibialis-posterior.nerve >}} | {{< var ref-tibialis-posterior.action >}} |
| [Flexor Digitorum Longus]({{< var ref-flexor-digitorum-longus.path >}}) | {{< var ref-flexor-digitorum-longus.origin >}} | {{< var ref-flexor-digitorum-longus.insertion >}} | {{< var ref-flexor-digitorum-longus.nerve >}} | {{< var ref-flexor-digitorum-longus.action >}} |
| [Flexor Hallucis Longus]({{< var ref-flexor-hallucis-longus.path >}}) | {{< var ref-flexor-hallucis-longus.origin >}} | {{< var ref-flexor-hallucis-longus.insertion >}} | {{< var ref-flexor-hallucis-longus.nerve >}} | {{< var ref-flexor-hallucis-longus.action >}} |
| [Popliteus]({{< var ref-popliteus.path >}}) | {{< var ref-popliteus.origin >}} | {{< var ref-popliteus.insertion >}} | {{< var ref-popliteus.nerve >}} | {{< var ref-popliteus.action >}} |
: Muscles supplied by L5 Nerve Root {.striped .hover}


# Overview

"L5 root involvement causes lower back, buttock, lateral thigh, and anterolateral calf pain. Sensory signs and symptoms occur on the lateral leg, the dorsomedial foot, and the large toe. Paresis occurs in the gluteus medius, gluteus minimus, tensor fasciae latae (adduction and internal rotation of thigh), semimembranosus and semitendinosus (knee flexion), tibialis posterior (plantar flexion and inversion of foot), tibialis anterior (dorsiflexion and inversion of foot), peronei (foot plantar flexion and eversion), flexor digitorum longus (plantar flexion of foot and all toes except the large toe), extensor digitorum brevis (extension of the large toe and three medial toes), extensor hallucis longus (extension of great toe and foot dorsiflexion), and extensor digitorum longus (extension of four lateral toes and foot dorsiflexion). With L5 root lesions, both the patellar (L2 L4) and Achilles (S1 S2) reflexes are spared." @brazisLocalizationClinicalNeurology2022 

# Examination


## SLR

"The straight leg raise, also called Lasègue sign, Lasègue test or Lazarevi sign, is a test done during the physical examination to determine whether a patient with low back pain has an underlying herniated disk, often located at L5 (fifth lumbar spinal nerve). With the patient lying down on his or her back on an examination table or exam floor, the examiner lifts the patient’s leg while the knee is straight. If the patient experiences sciatic pain when the straight leg is at an angle of between 30 and 70 degrees, then the test is positive and a herniated disc is likely to be the cause of the pain. A meta-analysis reported the accuracy of the straight leg test as 91% sensitive and 26% specific [7]. If raising the opposite leg causes pain (cross or contralateral straight leg raising), the sensitivity is 29% and the specificity is 88% [7]. The straight leg raising test and the cross straight leg raising test are two tests based on stretching of the nerves in the spine. The diagnostic accuracy of the straight leg raising test is thus limited by its low specificity [7]." @brazisLocalizationClinicalNeurology2022 

# Sensation

- 1st 2 toes


# DDX

- Superficial fib
    - Doesnt innervate cleft between toes #1 and #2


