---
title: T1 Nerve Root (T1)
---


# Motor Innervation

```{r}
#| echo: false
#| warning: false
#| message: false

# Load the here package
library(here)

# Source the functions script
source(here("scripts/functions.R"))

# Example usage
identifier_col <- "root_identifier"  # or "group_identifier"
filter_patterns <- "T1"
display_columns <- c("name_final", "origin_final", "insertion_final", "innervation_final", "action_final")
table_title <- "T1 Nerve Root Skeletal Muscle Innervations"

# Call the function
gt_table <- gt_oian(identifier_col, filter_patterns, display_columns, table_title)

gt_table
```

# Lesion

"Sensory disturbances occur on the medial arm. Paresis occurs variably in the following muscles: abductor pollicis brevis, opponens pollicis, flexor pollicis brevis, all lumbricals and interossei, abductor digiti minimi, opponens digiti minimi, flexor digiti minimi, and adductor pollicis [16]. The finger flexor reflex (C8 T1) may be depressed. Sympathetic fibers destined for the superior cervical ganglia are interrupted, resulting in an ipsilateral Horner syndrome." @brazisLocalizationClinicalNeurology2022

# Examination

## Muscle Strength

"Hand Intrinsics (T1) The patient is asked to squeeze the clinician’s fingers between their fingers while the clinician tries to pull their fingers away (Fig. 25-30). Based on the findings from the history, systems review, and key muscle testing, a sensory examination may be necessary (see Chapter 3)." @duttonDuttonOrthopaedicExamination2020