---
title: High Stepping
subtitle: Locomotion Intervention
---

:::{layout-ncol="3"}
### Purpose
High-stepping is used to reinforce the components of swing and stance and to assist the patient in developing an improved kinesthetic sense of the components of gait @osullivanImprovingFunctionalOutcomes2016.

### Harnessing the cross-extension reflex

- The Cross-Extension reflex can be recruited when flexing the hippast 90&deg @osullivanImprovingFunctionalOutcomes2016. 
- the reflex facilitates extension of the stance LE and flexion of the swing LE @osullivanImprovingFunctionalOutcomes2016. 
- Applying resistance to the swing leg will further facilitate this reflex @osullivanImprovingFunctionalOutcomes2016
:::

:::{layout-ncol="2"}

### Swing Benefits
This activity is highly effective in facilitating components of both swing (pelvis anterior elevation with hip flexion, adduction, and external rotation; knee flexion; and ankle dorsiflexion) @osullivanImprovingFunctionalOutcomes2016.

### Stance Benefits
pelvis posterior depression with hip extension, abduction, and internal rotation; knee extension; and ankle plantarflexion @osullivanImprovingFunctionalOutcomes2016.

:::

:::{layout-ncol="4"}
### Environment

Since this activity challenges dynamic single leg balance one should consider performing this near support, such as a treatment table or parallel bars initially @osullivanImprovingFunctionalOutcomes2016.


### Initial position

- The patient stands in a stride position with one foot forward and one foot back @osullivanImprovingFunctionalOutcomes2016. 

### Performing the movement

### Clinician Cues

- The patient is assisted (guided) or resisted (facilitatory) through weight shifting anteriorly onto the forward limb with a high step taken by the posterior limb @osullivanImprovingFunctionalOutcomes2016.
- Observe proper alignment and control of the stance LE @osullivanImprovingFunctionalOutcomes2016.

Emphasis is placed on pelvis posterior depression on the stance limb and pelvis anterior elevation on the dynamic limb (Fig. 10.2). Appropriate resistance to the pelvis and the LE is used on the swing side while approximation is applied through the pelvis and LE on the stance side. A static high-step position can be used to emphasize each component of gait as it challenges strength, endurance, and balance while providing the patient with increased kinesthetic and proprioceptive input.
:::

# Cues
:::{layout-ncol="3"}
- Variation in point of contact, amount of pressure, direction of pressure, and timing all change which part of the gait is emphasized @osullivanImprovingFunctionalOutcomes2016.

Manual contacts include application of resistance to pelvis anterior elevation and LE flexion on the dynamic side and approximation through pelvis posterior depression and LE extension on the stance side. 



### Hand placement

"Hand placements for the stance side are on the superior and slightly anterior iliac crest with the therapist’s forearms in line with the pelvic diagonal (i.e., in line with the patient’s heel)" @osullivanImprovingFunctionalOutcomes2016. 

### Verbal Cues

- “Shift forward onto your front leg, and step high with your opposite leg.” @osullivanImprovingFunctionalOutcomes2016
:::






# Facilitation

:::{layout-ncol="3"}

### Weight-shifting

- Light facilitatory resistance can to the stance pelvis during forward weight shift from midstance to terminal stance further emphasizes weight shifting weight acceptance together with pelvic posterior depression, hip extension, and knee control @osullivanImprovingFunctionalOutcomes2016.



:::

# Progression
:::{layout-ncol="2"}
### Assistance / Resistance

- Resistance can facilitate the cross-extension reflex


Regression
:::

