---
title: Memory
---

Memory refers to the ability to initially acquire, store, and recall (remember) information from the past.
Memory can involve remembering facts or information or can involve recalling and knowing how to perform a task.

2 Types of learning and memory:

- Explicit memory:
- Implicit memory:



# Neurophysiology

Stored in hippocampus temporary then moves to association areas then other areas

# Types

## Explicit Memory

- AKA declarative memory
- A collection of memory systems that together are responsible for the acquisition, retention, and retrieval of information that can be consciously and intentionally recollected
- Examples of explicit memory include remembering a specific fact, a specific event, or the steps required to complete a task.

## Implicit memory

- AKA "procedural memory" or "nondeclarative memory"
- Cannot be accessed by conscious recall but occurs through unconscious systems such as movement or perception

# Impairments

- Immediate Re-call & Short term Memory – Remedial Tx Suggestions:
    - address attention first, organize material with associations, for easy retrieval, ask about previous strategies
- Compensatory: 
    - Diary, Logs, Environmental Prompts
