---
title: Trendelenberg Sign
---


"The Trendelenburg sign indicates a weakness of the gluteus medius muscle during unilateral weight bearing. This position produces a strong contraction of the gluteus medius, which is powerfully assisted by the gluteus minimus and TFL, in order to keep the pelvis horizontal. For example, when the body weight is supported by the left foot (Fig. 19-19), the left hip abductors contract both isometrically and eccentrically to prevent the right side of the pelvis from being pulled downward by gravity. The clinician crouches or kneels behind the patient so that the eyes are level with the patient’s pelvis, and ensures that the patient does not lean to one side during the testing. The patient is asked to stand on one limb by flexing the opposite hip to approximately 30 degrees. The patient may use a light touch with the ipsilateral upper extremity for balance, or the clinician may provide gentle manual pressure to maintain balance and reduce any trunk shift. Once balanced, the patient is asked to raise the nonstance pelvis as high as possible. From the posterior view, the clinician observes the angle formed by a line that connects the iliac crest and a line vertical to the testing surface. If the patient can maintain the elevation of the hip of the nonstance side for 30 seconds, the test is considered negative. A positive Trendelenburg sign is indicated if one of the following criteria is met22: " @duttonDuttonOrthopaedicExamination2020

1. The patient is unable to hold the elevated pelvic position for 30 seconds. 
2. No elevation is noted on the nonstance side. 
3. The stance hip adducts, allowing the pelvis on the nonstandard side to 

"drop downwardly below the level of the stance side pelvis (Fig. 19-19). A goniometer may be used to quantify the amount of pelvic movement by placing the axis of the goniometer on the ASIS, the stationary arm along an imaginary line between the two ASIS landmarks, and the moving arm along the anterior midline of the femur.126" @duttonDuttonOrthopaedicExamination2020 


"A false-negative may occur if the patient is allowed to shift his or her trunk too far laterally over the stance limb (reverse Trendelenburg sign) in an attempt to prevent the contralateral pelvis from dropping and to reduce the demand on the hip abductors. A number of dysfunctions can produce the Trendelenburg sign. These include superior gluteal nerve palsy, lumbar disk herniation, weakness or tear of the gluteus medius, and advanced degeneration of the hip. Thus, if used in isolation, this test has little diagnostic value" @duttonDuttonOrthopaedicExamination2020 