---
title: Greater Trochanteric Pain Syndrome
---


# Neuman 

"G reater trochanteric pain syndrome (GTPS) involves degenerative changes of the distal tendinous attachments of the gluteus medius and minimus and, in some cases, associated bursitis.67 GTPS can be a primary cause of lateral hip pain, most commonly affecting women more than 40 years of age.6,81 Classic signs include aching or point tenderness near or on the greater trochanter (where the gluteal muscles attach), weakened hip abduction, and a gait deviation consistent with weak or painful hip abductor muscles (described later in this chapter). Symptoms are often exacerbated by activities that demand high, sustained, or repetitive forces from the hip abductors, such as standing on one limb, climbing stairs or hills, or prolonged walking. As with all pain in the hip region, associated co-morbidities must be ruled out as well as pain referred from the low back region.81" @neumannKinesiologyMusculoskeletalSystem2017

"The primarily pathology underlying GTPS is believed to be tendinopathy of the gluteus medius and minimus. MRI often shows a thickening or a thinning of the affected tendons as well as partialor full-thickness tears.6,41,81,179 Tears occur more frequently in the tendon of the gluteus medius as it attaches to the lateral and superior-posterior facets of the greater trochanter.6 In up to 20% of cases, bursitis may be associated with GTPS, either in the bursa beneath the distal attachments of the gluteus medius and minimus or, more frequently, in the bursa over the posterior-inferior aspect of the greater trochanter and just under the gluteus maximus"

"The pathology associated with tendinopathy of the gluteus medius or gluteus minimus has features similar to rotator cuff pathology.50 For this reason, GTPS has been loosely referred to as the “rotator cuff syndrome of the hip.” The supraspinatus and gluteal tendons both tend to show degenerative changes on the undersurface of the tendon as it abuts against bone.68 Pain is usually insidious and chronic in both GTPS and rotator cuff syndrome, typically involving attritional degeneration or tears rather than acute rupture from an isolated event. The degenerative changes that tend to occur in these muscles are, in some way, related to a failure of the tissues to absorb and tolerate mechanical stress. Forces from the gluteal muscles, required at every mid stance phase of gait, impose relatively large and repetitive stresses on their respective tendons.5 Such stress is ordinarily described as tension, because it pulls the tendon away from the bone, but insofar as the very distal aspect of that tendon is pulled directly into the bone, the stress is also a localized compression.81 The magnitude of the compressional stress may be influenced by simultaneous forces acting on the overlying fascia lata of the thigh exerted in part by the tensor fasciae latae muscle. Stiffening of this complex could create an inward push against the underlying gluteal tendons as they wrap superior-medially over the greater trochanter, amplifying the localized compression on the gluteal tendons.81 Over time, the repeated compressional stress might degrade and weaken the tissue matrix of the tendon insertion. Subsequent small tears or abrasions in the tendon theoretically place greater stress on the intact, healthy parts of the tendon, thereby predisposing these tissues to degeneration as well. The precise pathology of GTPS and the associated gluteal tendinopathy are not well understood." @neumannKinesiologyMusculoskeletalSystem2017

"Although theoretical, one factor leading to GTPS may be related to a prior history of weakness or otherwise reduced abduction torque potential of the gluteus medius and minimus. A scenario of weakness of the gluteal muscles could increase the compensatory demands on the more superficial abductor hip mechanism (i.e., the tensor fasciae latae muscle and associated lateral fascia of the thigh). Such compensation, if occurring at every gait cycle, could plausibly abrade the gluteal tendons to the point that they undergo attritional degeneration or even failure. Much more biomechanical and histologic research is needed to better understand the pathogenesis of GTPS in order to better treat this condition." @neumannKinesiologyMusculoskeletalSystem2017 

# Conservative Treatment

"Conservative treatment has been described for GTPS, including use of anti-inflammatory medication, corticosteroid injection, a cane in the hand contralateral to the affected hip, and physical therapy.41,81 Grimaldi and Fearon have proposed a physical therapy approach that limits activities or exercises involving hip adduction (both pelvic-on-femoral and vice versa). This precaution is believed to minimize compressional stress on the insertions of the gluteal tendons as the tensor fasciae latae and associated lateral fascia are stretched across the lateral side of the hip. In addition, initial physical therapy sessions may incorporate non–pain-provoking isometric abduction exercises in positions that limit hip adduction. As thoroughly outlined by Grimaldi and Fearon,81 methods of applying greater resistance with non–isometric-type exercises may be judiciously incorporated when tolerated." @neumannKinesiologyMusculoskeletalSystem2017


# Surgical Treatment

"When conservative treatment is unsuccessful, surgical repair of the tendons may be indicated. Both open and endoscopic surgical approaches have been shown to produce favorable results" @neumannKinesiologyMusculoskeletalSystem2017 