---
title: Hip Osteoarthritis
---

"Hip osteoarthritis is a disease manifested primarily by deteriora­ tion of the joint’s articular cartilage, loss of joint space, thickening of the joint capsule, sclerosis of subchondral bone, and the pres­ ence of osteophytes. Without an adequate damping mechanism to dissipate joint forces, the hip can experience marked degenera­ tion and change in shape. Several years ago, the American College of Rheumatology recommended the following criteria for diag­ nosing hip osteoarthritis without the use of radiography: hip pain, less than 115 degrees of hip flexion, and less than 15 degrees of internal rotation.7 The reduced range of motion may be caused by restrictions in soft tissue (such as posterior and inferior capsule or parts of the ischiofemoral ligament) and, in more severe cases, articular malalignment and osteophyte formation. Additional symptoms may include atrophy and weakness of hip muscles, morning stiffness, crepitus, inflammation of soft tissues, and an abnormal gait pattern (such as a compensated Trendelenburg gait) or altered step length. The impairments associated with advanced hip osteoarthritis can cause a significant loss in function, including difficulty climbing stairs, walking, bathing, dressing the lower extremities, getting in and out of a car, and rising from a low chair." @neumannKinesiologyMusculoskeletalSystem2017 

"Hip osteoarthritis may be classified as either a primary or a secondary disease. Primary, or idiopathic, hip	 osteoarthritis is an arthritic condition without a known or obvious cause. Secondary	 hip	 osteoarthritis, in contrast, is an arthritic condition resulting from a known or relatively obvious mechanical disruption of the joint. This may occur from trauma or exposure to high loads; structural failure, such as a slipped capital femoral epiphysis or avascular necrosis of the femoral head (e.g., Legg­Calvé­Perthes disease); significant anatomic asymmetry or dysplasia, such as excessive acetabular or femoral anteversion; or repeated dislo­ cations and chronic instability.40,87,109 Often the source of the mechanical disruption is not so obvious and relatively subtle anatomic variations in bony structure can be a precursor to osteo­ arthritis. The resulting joint incongruity (even when slight and asymptomatic), if combined with certain habitual and usually extreme movements, can lead to repeated impingement and stress on the joint to a point of potentially triggering osteoarthritis." @neumannKinesiologyMusculoskeletalSystem2017


"Despite decades of clinical and basic science research, the exact underlying cause of primary hip osteoarthritis remains unclear.197 Although the frequency of osteoarthritis at any joint increases with age, the disease is not triggered solely by the aging process.137 If that were true, then all elderly people would eventually develop this disease. The causes of osteoarthritis are complicated and not exclusively based on a simple wear­and­tear phenomenon. Although physical stress may increase the rate and amount of wear at the hip, this does not always lead to osteoarthritis.133,189 Other factors that may be related to osteoarthritis are an altered metabo­ lism of the ground matrix of the cartilage, increased body­mass index, genetics, immune system factors, neuromuscular disorders, and biochemical factors." @neumannKinesiologyMusculoskeletalSystem2017