---
title: Tensor Fascia Latae (TFL)
---

# OIAN

:::{layout-ncol="4"}

### Origin

ASIS @gilroyAtlasAnatomy2020 

### Insertion

Iliotibial Tract @gilroyAtlasAnatomy2020 


### Innervation

The TFL is innervated by nerve roots [L4]({{< var ref-nerve-root.l4 >}}), [L5]({{< var ref-nerve-root.l5 >}}), and [S1]({{< var ref-nerve-root.s1 >}}), via the [Superior gluteal nerve]({{< var ref-superior-gluteal-nerve.path >}})  @gilroyAtlasAnatomy2020

### Action

- Tenses the fascia latae @gilroyAtlasAnatomy2020
- Hip joint: abduction, flexion, and internal rotation @gilroyAtlasAnatomy2020

:::

# Overview

"The tensor fascia latae (TFL) arises from the outer lip of the iliac crest and the lateral surface of the anterior superior iliac spine (ASIS) (Fig. 19-5). Over the flattened lateral surface of the thigh, the fascia latae thickens to form a strong band, the iliotibial tract. When the hip is flexed, the TFL is anterior to the greater trochanter and helps maintain the hip in flexion. As the hip extends, the TFL moves posteriorly over the greater trochanter to assist with hip extension. The TFL is also a weak extensor of the knee, but only when the knee is already extended. The muscle is innervated by the superior gluteal nerve, L4–L5." @duttonDuttonOrthopaedicExamination2020 