---
title: Deltoid muscle
---

# OIAN

| Muscle  | Origin | Insertion | Nerve | Action |
|------|--------|-------|----------|--------|
| [Anterior Deltoid]({{< var ref-deltoid-muscle-anterior.path >}}) | {{< var ref-deltoid-muscle-anterior.origin >}} | {{< var ref-deltoid-muscle-anterior.insertion >}} | {{< var ref-deltoid-muscle-anterior.nerve >}} | {{< var ref-deltoid-muscle-anterior.action >}} |
| [Lateral Deltoid]({{< var ref-deltoid-muscle-lateral.path >}}) | {{< var ref-deltoid-muscle-lateral.origin >}} | {{< var ref-deltoid-muscle-lateral.insertion >}} | {{< var ref-deltoid-muscle-lateral.nerve >}} | {{< var ref-deltoid-muscle-lateral.action >}} |
| [Posterior Deltoid]({{< var ref-deltoid-muscle-posterior.path >}}) | {{< var ref-deltoid-muscle-posterior.origin >}} | {{< var ref-deltoid-muscle-posterior.insertion >}} | {{< var ref-deltoid-muscle-posterior.nerve >}} | {{< var ref-deltoid-muscle-posterior.action >}} |

: Deltoid Muscles OIAN {.striped .hover}

# Anterior head
:::{layout-ncol="2"}
### Origin
Lateral 1/3 of clavicle @gilroyAtlasAnatomy2020

### Insertion
Humerus (deltoid tuberosity) @gilroyAtlasAnatomy2020

### Innervation
[Axillary n. {{< var ref-axillary-nerve.roots >}}]({{< var ref-axillary-nerve.path >}}) @gilroyAtlasAnatomy2020

### Action
Flexion, internal rotation, adduction @gilroyAtlasAnatomy2020
:::

# Lateral part
:::{layout-ncol="2"}
### Origin
Acromion @gilroyAtlasAnatomy2020

### Insertion
Humerus (deltoid tuberosity) @gilroyAtlasAnatomy2020

### Innervation
[Axillary n. {{< var ref-axillary-nerve.roots >}}]({{< var ref-axillary-nerve.path >}}) @gilroyAtlasAnatomy2020

### Action
Abduction @gilroyAtlasAnatomy2020
:::

:::{.callout-note}
*Between 60 and 90 degrees of abduction, the clavicular and spinal parts assist the acromial part with abduction @gilroyAtlasAnatomy2020
:::

## Posterior part
### Origin
Scapular spine @gilroyAtlasAnatomy2020
### Insertion
Humerus (deltoid tuberosity) @gilroyAtlasAnatomy2020

### Innervation
[Axillary n. {{< var ref-axillary-nerve.roots >}}]({{< var ref-axillary-nerve.path >}}) @gilroyAtlasAnatomy2020

### Action
Extension, external rotation, adduction @gilroyAtlasAnatomy2020

:::{.callout-note}
*Between 60 and 90 degrees of abduction, the clavicular and spinal parts assist the acromial part with abduction @gilroyAtlasAnatomy2020
:::

# Strength Testing

# Palpation

# Dysfunction