---
title: Biceps Femoris
---


# Overview

```{r}
#| echo: false
#| warning: false
#| message: false

# Load the here package
library(here)

# Source the functions script
source(here("scripts/functions.R"))

# Example usage
identifier_col <- "group_identifier"  # or "group_identifier"
filter_patterns <- "biceps_femoris"
display_columns <- c("name_final", "origin_final", "insertion_final", "innervation_final", "action_final")
table_title <- "Biceps Femoris Muscles"

# Call the function
gt_table <- gt_oian(identifier_col, filter_patterns, display_columns, table_title)

gt_table
```

"The biceps femoris (see Fig. 19-8) muscle is a two-headed muscle. The longer of the two heads arises from the inferomedial facet of the ischial tuberosity, whereas the shorter head originates from the lateral lip of the linea aspera of the femur. The muscle inserts on the lateral tibial condyle and the fibular head. The biceps femoris functions to extend the hip, flex the knee, and externally rotate the tibia. The superficial layer of the common tendon has been identified as the main force creating external tibial rotation and controlling the internal rotation of the femur.14 The pull of the biceps on the tibia retracts the joint capsule and pulls the iliotibial tract posteriorly, keeping it tight throughout flexion." @duttonDuttonOrthopaedicExamination2020 