---
title: Semitendinosus
---

# Overview

```{r}
#| echo: false
#| warning: false
#| message: false

# Load the here package
library(here)

# Source the functions script
source(here("scripts/functions.R"))

# Example usage
identifier_col <- "muscle_identifier"  # or "group_identifier"
filter_patterns <- "semitendinosus"
display_columns <- c("name_final", "origin_final", "insertion_final", "innervation_final", "action_final")
table_title <- "Semitendinosus Muscle"

# Call the function
gt_table <- gt_oian(identifier_col, filter_patterns, display_columns, table_title)

gt_table
```

# Origin {#origin}
- Ischial tuberosity @gilroyAtlasAnatomy2020
- Sacrotuberous lig. @gilroyAtlasAnatomy2020
- (*common head with long head of biceps femoris*) @gilroyAtlasAnatomy2020

# Insertion {#insertion}

- Medial to the tibial tuberosity in the [Pes Anserine]({{< var ref-pes-anserine.path >}}) @gilroyAtlasAnatomy2020
    - (*along with the tendons of gracilis and sartorius*) @gilroyAtlasAnatomy2020

# Nerve

[Tibial N. (*division of Sciatic N.*)]({{< var ref-tibial-nerve.path >}}) ([L5]({{< var ref-nerve-root.l5 >}}), [S1]({{< var ref-nerve-root.s1 >}}), [S2]({{< var ref-nerve-root.s2 >}})) @gilroyAtlasAnatomy2020

# Action {#action}

- **Hip**: Extension @gilroyAtlasAnatomy2020
- **Pelvic Stabilization**: Sagittal plane @gilroyAtlasAnatomy2020
- **Knee**: Flexion and Internal rotation @gilroyAtlasAnatomy2020


# Overview

"The semitendinosus muscle (see Fig. 19-8) arises from the upper portion of the ischial tuberosity via a shared tendon with the long head of the biceps femoris. From there, it travels distally, becoming cord-like about two-thirds of the way down the posteromedial thigh. Passing over the MCL, it inserts into the medial surface of the tibia and deep fascia of the lower leg, distal to the gracilis attachment, and posterior to the sartorius attachment. These three structures are collectively called the pes anserinus (“goose foot”) at this point. Like the semimembranosus, the semitendinosus functions to extend the hip, flex the knee, and internally rotate the tibia." @duttonDuttonOrthopaedicExamination2020 