---
title: Cuboid bone
---


"As its name indicates, the cuboid has six surfaces, three of which articulate with adjacent tarsal bones (see Figs. 14.4, 14.5, and 14.7). The distal surface articulates with the bases of both the fourth and the fifth metatarsals. The cuboid is therefore homologous to the hamate bone in the wrist." @neumannKinesiologyMusculoskeletalSystem2017 

"The entire, curved proximal surface of the cuboid articulates with the calcaneus (see Fig. 14.4). The medial surface has an oval facet for articulation with the lateral cuneiform and a small facet for articulation with the navicular. A distinct groove runs across the plantar surface of the cuboid, which in life is occupied by the tendon of the fibularis longus muscle (see Fig. 14.5)." @neumannKinesiologyMusculoskeletalSystem2017

# Joints

> "An understanding of the shape of the talus is crucial to understanding much of the kinesiology of the ankle and foot" @neumannKinesiologyMusculoskeletalSystem2017

"As will be described, the talus is mechanically involved with all three of these joints. The multiple articulations made by the talus help to explain the bone’s complex shape, with nearly 70% of its surface covered with articular cartilage. An understanding of the shape of the talus is crucial to understanding much of the kinesiology of the ankle and foot." @neumannKinesiologyMusculoskeletalSystem2017

# Palpation

The cuboid bone can be palpated by moving distally approximately one finger-breadth from the sinus tarsi @duttonDuttonOrthopaedicExamination2020 