---
title: Hip External Rotator Muscles
---

:::{layout-ncol="2"}


### Primary

- [Gluteus Maximus]({{< var ref-gluteus-maximus.path >}}) @neumannKinesiologyMusculoskeletalSystem2017
- [Piriformis]({{< var ref-piriformis.path >}}) @neumannKinesiologyMusculoskeletalSystem2017
- [Superior Gemellus]({{< var ref-superior-gemellus.path >}}) @neumannKinesiologyMusculoskeletalSystem2017
- [Obturator Internus]({{< var ref-obturator-internus.path >}}) @neumannKinesiologyMusculoskeletalSystem2017
- [Inferior Gemellus]({{< var ref-inferior-gemellus.path >}}) @neumannKinesiologyMusculoskeletalSystem2017
- [Quadratus Femoris]({{< var ref-quadratus-femoris.path >}}) @neumannKinesiologyMusculoskeletalSystem2017

### Secondary

- [Gluteus Medius]({{< var ref-gluteus-medius.path >}}) (posterior fiberes) @neumannKinesiologyMusculoskeletalSystem2017
- [Gluteus Minimus]({{< var ref-gluteus-minimus.path >}}) (post) @neumannKinesiologyMusculoskeletalSystem2017
- [Sartorius]({{< var ref-sartorius.path >}})  @neumannKinesiologyMusculoskeletalSystem2017
- [Obturator Externus]({{< var ref-obturator-externus.path >}}) @neumannKinesiologyMusculoskeletalSystem2017
- [Biceps Femoris Long Head]({{< var ref-biceps-femoris-long-head.path >}}) @neumannKinesiologyMusculoskeletalSystem2017

:::

# Primary

| Muscle  | Origin | Insertion | Nerve | Action |
|------|--------|-------|----------|--------|
| [Gluteus Maximus]({{< var ref-gluteus-maximus.path >}}) | {{< var ref-gluteus-maximus.origin >}} | {{< var ref-gluteus-maximus.insertion >}} | {{< var ref-gluteus-maximus.nerve >}} | {{< var ref-gluteus-maximus.action >}} |
| [Piriformis]({{< var ref-piriformis.path >}}) | {{< var ref-piriformis.origin >}} | {{< var ref-piriformis.insertion >}} | {{< var ref-piriformis.nerve >}} | {{< var ref-piriformis.action >}} |
| [Obturator Internus]({{< var ref-obturator-internus.path >}}) | {{< var ref-obturator-internus.origin >}} | {{< var ref-obturator-internus.insertion >}} | {{< var ref-obturator-internus.nerve >}} | {{< var ref-obturator-internus.action >}} |
| [Superior Gemellus]({{< var ref-superior-gemellus.path >}}) | {{< var ref-superior-gemellus.origin >}} | {{< var ref-superior-gemellus.insertion >}} | {{< var ref-superior-gemellus.nerve >}} | {{< var ref-superior-gemellus.action >}} |
| [Inferior Gemellus]({{< var ref-inferior-gemellus.path >}}) | {{< var ref-inferior-gemellus.origin >}} | {{< var ref-inferior-gemellus.insertion >}} | {{< var ref-inferior-gemellus.nerve >}} | {{< var ref-inferior-gemellus.action >}} |
| [Quadratus Femoris]({{< var ref-quadratus-femoris.path >}}) | {{< var ref-quadratus-femoris.origin >}} | {{< var ref-quadratus-femoris.insertion >}} | {{< var ref-quadratus-femoris.nerve >}} | {{< var ref-quadratus-femoris.action >}} |
: {.striped .hover}

# Secondary

| Muscle  | Origin | Insertion | Nerve | Action |
|------|--------|-------|----------|--------|
| [Gluteus Medius]({{< var ref-gluteus-medius.path >}}) | {{< var ref-gluteus-medius.origin >}} | {{< var ref-gluteus-medius.insertion >}} | {{< var ref-gluteus-medius.nerve >}} | {{< var ref-gluteus-medius.action >}} |
| [Gluteus Minimus]({{< var ref-gluteus-minimus.path >}}) | {{< var ref-gluteus-minimus.origin >}} | {{< var ref-gluteus-minimus.insertion >}} | {{< var ref-gluteus-minimus.nerve >}} | {{< var ref-gluteus-minimus.action >}} |
| [Obturator Externus]({{< var ref-obturator-externus.path >}}) | {{< var ref-obturator-externus.origin >}} | {{< var ref-obturator-externus.insertion >}} | {{< var ref-obturator-externus.nerve >}} | {{< var ref-obturator-externus.action >}} |
| [Sartorius]({{< var ref-sartorius.path >}}) | {{< var ref-sartorius.origin >}} | {{< var ref-sartorius.insertion >}} | {{< var ref-sartorius.nerve >}} | {{< var ref-sartorius.action >}} |
| [Biceps Femoris Long Head]({{< var ref-biceps-femoris-long-head.path >}}) | {{< var ref-biceps-femoris-long-head.origin >}} | {{< var ref-biceps-femoris-long-head.insertion >}} | {{< var ref-biceps-femoris-long-head.nerve >}} | {{< var ref-biceps-femoris-long-head.action >}} |
: Secondary External Rotators of the Hip {.striped .hover}

# Deep Rotators of the Hip

The deep rotators of the hip are nicknamed the "rotator cuff" of the hip

| Muscle  | Origin | Insertion | Nerve | Action |
|------|--------|-------|----------|--------|
| [Piriformis]({{< var ref-piriformis.path >}}) | {{< var ref-piriformis.origin >}} | {{< var ref-piriformis.insertion >}} | {{< var ref-piriformis.nerve >}} | {{< var ref-piriformis.action >}} |
| [Obturator Internus]({{< var ref-obturator-internus.path >}}) | {{< var ref-obturator-internus.origin >}} | {{< var ref-obturator-internus.insertion >}} | {{< var ref-obturator-internus.nerve >}} | {{< var ref-obturator-internus.action >}} |
| [Superior Gemellus]({{< var ref-superior-gemellus.path >}}) | {{< var ref-superior-gemellus.origin >}} | {{< var ref-superior-gemellus.insertion >}} | {{< var ref-superior-gemellus.nerve >}} | {{< var ref-superior-gemellus.action >}} |
| [Inferior Gemellus]({{< var ref-inferior-gemellus.path >}}) | {{< var ref-inferior-gemellus.origin >}} | {{< var ref-inferior-gemellus.insertion >}} | {{< var ref-inferior-gemellus.nerve >}} | {{< var ref-inferior-gemellus.action >}} |
| [Quadratus Femoris]({{< var ref-quadratus-femoris.path >}}) | {{< var ref-quadratus-femoris.origin >}} | {{< var ref-quadratus-femoris.insertion >}} | {{< var ref-quadratus-femoris.nerve >}} | {{< var ref-quadratus-femoris.action >}} |
| [Obturator Externus]({{< var ref-obturator-externus.path >}}) | {{< var ref-obturator-externus.origin >}} | {{< var ref-obturator-externus.insertion >}} | {{< var ref-obturator-externus.nerve >}} | {{< var ref-obturator-externus.action >}} |
: Deep Rotators of the Hip {.striped .hover}

# Notes

“The primary external rotator muscles of the hip include the gluteus maximus and five of the six “short external rotators.” In the anatomic position, muscles considered to be secondary exter­ nal rotators are the posterior fibers of the gluteus medius and minimus, obturator externus, sartorius, and long head of the biceps femoris.162 The obturator externus is considered a second­ ary rotator because in the anatomic position its line of force lies only a few millimeters posterior to the longitudinal axis of rota­ tion (see Fig. 12.35). ” @neumannKinesiologyMusculoskeletalSystem2017

# Functional Anatomy of the “Short External Rotators”
“The six “short external rotators” of the hip are the piriformis, obturator internus, gemellus superior, gemellus inferior, quadratus femoris, and obturator externus (see Figs. 12.14, 12.39, and 12.43). The lines of force of these muscles are oriented primarily in the horizontal plane. This orientation is optimal for producing external rotation torque, because most of the force component of each muscle has a perpendicular intersection with the vertical axis of rotation. In a manner similar to the infraspinatus and teres minor at the shoulder, the short external rotators are also well aligned to compress and thereby help stabilize the articulation.”
“The piriformis attaches proximally on the anterior surface of the sacrum, between the nerve roots emanating from the three most cranial ventral sacral foramina (see Figs. 12.1 and 12.26). Exiting the pelvis posteriorly through the greater sciatic foramen, the piriformis attaches via a tendon to the superior aspect of the greater trochanter (see Fig. 12.43).1 In addition to the action of external rotation, the piriformis is a secondary hip abductor.162 Both actions are apparent by the muscle’s line of force relative to the axes of rotation at the hip (see Figs. 12.30 and 12.35).”  @neumannKinesiologyMusculoskeletalSystem2017
“The sciatic nerve usually exits the pelvis inferior to the pirifor­ mis. As described earlier in this chapter, the sciatic nerve may pass through the belly of the piriformis. A shortened, thickened, or “tight” piriformis may compress and irritate the sciatic nerve, a condition known as “piriformis syndrome.”
“The obturator	 internus is a fan­shaped muscle that originates from the internal surface of the obturator membrane and from the adjacent bone surrounding the obturator foramen (see Fig. 12.43). Although not visible in Fig. 12.43, much of the muscle’s proximal attachment extends superiorly and slightly posteriorly on the internal surface of the ischium, about 2–3 cm above the ischial spine. From this extensive origin, muscle fibers converge to a tendon after exiting the pelvis through the lesser sciatic foramen. The lesser sciatic notch, which is lined with hyaline cartilage, functions as a pulley by deflecting the tendon of the obturator internus by about 130 degrees on its approach to the medial surface of the greater trochanter (Fig. 12.46A). With the femur firmly fixed during standing, strong contraction of a right obturator internus, for example, can rotate the pelvis (and super­ imposed trunk) contralaterally to the left relative to the femoral head (see Fig. 12.46B). In addition to rotating the pelvis, the force produced by the nearly horizontally­running obturator internus should also effectively compress the joint. Hodges and colleagues performed a fine­wire, ultrasound­guided EMG analysis of the obturator internus and several other external rotator muscles in 10 human subjects.98 The obturator internus was usually the first muscle to become active during a gradually increasing isometric effort to abduct and externally rotate the hip. This early activation may reflect the muscle’s role in fine­tuning the positional stability of the joint just before the activation of the other muscles.”
“A relatively dense layer of connective tissue covers and adheres to part of the medial (intrapelvic) surface of the obturator internus muscle, often described as the obturator	fascia.216 This fascia serves as part of the attachment of the levator ani, the main muscle of the pelvic floor. (Refer to Appendix IV, Part F, for attachments, innervation, and actions of the muscles of the pelvic floor.) Because of this direct anatomic connection, some treatments for pelvic	floor	pain	syndrome	or	dysfunction incorporate methods that alter the active or passive tension in the obturator internus.”  @neumannKinesiologyMusculoskeletalSystem2017

# Overall Function

“Overall Function The functional potential of the external rotators is most evident during pelvic­on­femoral rotation. Consider, for example, the external rotator muscles contracting to rotate the pelvis over the femur (Fig. 12.47). With the right lower extremity firmly in contact with the ground, contraction of the right external rotators accelerates the anterior side of the pelvis and attached trunk to the left—contralateral to the fixed femur. This action of planting a foot and “cutting” to the opposite side is the natural way to abruptly change direction while running. As indicated in Fig. 12.47, activation of the right gluteus maximus, for instance, is very capable of imparting both the extension and the external rotation thrust to the hip during this action. If needed, the exter­ nal rotation torque can be decelerated by eccentric action of internal rotator muscles. Sudden eccentric activation of the adductor longus or brevis, for example, might arise to decelerate the pelvis as it swings to face contralaterally—an action that may cause “strain” injury to these muscles. The mechanism of injury may partially explain the relatively high incidence of adductor muscle strain during many sporting activities that involve rapid rotation of the pelvis and trunk while running.” @neumannKinesiologyMusculoskeletalSystem2017
