---
title: Hip Extensor Muscles
---

:::{layout-ncol="2"}

Gluteus maximus Biceps femoris (long head) Semitendinosus Semimembranosus Adductor magnus (posterior head)

### Primary

- Glute max (lower and upper fibers) @neumannKinesiologyMusculoskeletalSystem2017
- Biceps Femoris Long Head @neumannKinesiologyMusculoskeletalSystem2017
- Adductor magnus (Posterior fibers) @neumannKinesiologyMusculoskeletalSystem2017

### Secondary

- Glute med (Posterior fibers) @neumannKinesiologyMusculoskeletalSystem2017
- Adductor magnus (ant head) @neumannKinesiologyMusculoskeletalSystem2017
:::

# Primary

| Muscle  | Origin | Insertion | Nerve | Action |
|------|--------|-------|----------|--------|
| [Gluteus Maximus]({{< var ref-gluteus-maximus.path >}}) | {{< var ref-gluteus-maximus.origin >}} | {{< var ref-gluteus-maximus.insertion >}} | {{< var ref-gluteus-maximus.nerve >}} | {{< var ref-gluteus-maximus.action >}} |
| [Adductor Magnus]({{< var ref-adductor-magnus.path >}}) | {{< var ref-adductor-magnus.origin >}} | {{< var ref-adductor-magnus.insertion >}} | {{< var ref-adductor-magnus.nerve >}} | {{< var ref-adductor-magnus.action >}} |
| [Biceps Femoris Long Head]({{< var ref-biceps-femoris-long-head.path >}}) | {{< var ref-biceps-femoris-long-head.origin >}} | {{< var ref-biceps-femoris-long-head.insertion >}} | {{< var ref-biceps-femoris-long-head.nerve >}} | {{< var ref-biceps-femoris-long-head.action >}} |
: {.striped .hover}

# Secondary

| Muscle  | Origin | Insertion | Nerve | Action |
|------|--------|-------|----------|--------|
| [Gluteus Medius]({{< var ref-gluteus-medius.path >}}) | {{< var ref-gluteus-medius.origin >}} | {{< var ref-gluteus-medius.insertion >}} | {{< var ref-gluteus-medius.nerve >}} | {{< var ref-gluteus-medius.action >}} |
| [Adductor Magnus]({{< var ref-adductor-magnus.path >}}) | {{< var ref-adductor-magnus.origin >}} | {{< var ref-adductor-magnus.insertion >}} | {{< var ref-adductor-magnus.nerve >}} | {{< var ref-adductor-magnus.action >}} |
: {.striped .hover}


# Anatomy and Individual Actions
“The primary hip extensors are the gluteus maximus, the ham­ strings (i.e., the long head of the biceps femoris, the semitendi­ nosus, and the semimembranosus), and the posterior head of the adductor magnus (Fig. 12.39).57 The middle and posterior fibers of the gluteus medius and the anterior fibers of the adductor magnus are secondary extensors.162 With the hip flexed to at least about 70 degrees and beyond, most adductors muscles (with the possible exception of the pectineus) are capable of assisting with hip extension.” @neumannKinesiologyMusculoskeletalSystem2017

# Function
## Overall Function
### Pelvic-on-Femoral Hip Extension
“The following sections describe two different situations in which the hip extensor muscles control pelvic­on­femoral extension. Hip Extensors Performing a Posterior Pelvic Tilt. With the supralumbar trunk held relatively stationary, the hip extensor and abdominal muscles act as a force­couple to posteriorly tilt the pelvis (Fig. 12.40). The posterior tilt extends the hip joints slightly and reduces the lumbar lordosis.” @neumannKinesiologyMusculoskeletalSystem2017

“The muscular mechanics involved with posterior tilting of the pelvis are generally similar to those described for the anterior tilting of the pelvis (compare Figs. 12.28 and 12.40). In both tilting actions, the hip and trunk muscles form a force­couple for rotating the pelvis through a relatively short arc around the femoral heads. During standing, tensions exerted by the hip’s capsular ligaments and by hip flexor muscles normally determine the end range of the posterior pelvic movement, in stark contrast to how the lumbar spine restricts the end range of an anterior pelvic tilt.”  @neumannKinesiologyMusculoskeletalSystem2017

## Control Forward Lean
“Leaning forward while standing is a very common activity. Con­ sider, for example, the forward lean used when brushing your teeth over a sink. The muscular support at the hip for this near static posture is primarily the responsibility of the hamstring muscles. Consider two phases of a forward lean shown in Fig. 12.41. During a slight forward lean (see Fig. 12.41A), body weight is displaced just anterior to the medial­lateral axis of rotation at the hips. This slightly flexed posture is restrained by minimal activation from the gluteus maximus and hamstring muscles. A more significant forward lean, however, displaces body weight farther in front of the hips (see Fig. 12.41B). Supporting this markedly flexed posture requires greater muscle activation from the hamstring muscles. The gluteus maximus, however, remains relatively inactive in this position—a point verifiable by palpation and inferred from electromyographic data.70 The appar­ ent increased responsibility of the hamstrings (in contrast to the gluteus maximus) can be explained biomechanically and physi­ ologically. Forward leaning increases the hip extension moment arm of the hamstring muscles whereas it decreases the hip exten­ sor moment arm of the gluteus maximus.185 (Compare the 15­degree and 30­degree points in the graph in Fig. 12.41.) Leaning forward, therefore, mechanically optimizes the extension torque potential of the hamstrings.103 A significant forward lean also elongates the hamstring muscles across both the hip and the knee joints. The resulting increased passive tension in these elon­ gated biarticular muscles helps support the partially flexed posi­ tion of the hips. For these reasons the hamstrings appear uniquely equipped to support the hip during a forward lean. Apparently the nervous system holds the gluteus maximus partially in reserve for more powerful hip extension activities, such as rapidly climb­ ing a flight of stairs.” @neumannKinesiologyMusculoskeletalSystem2017

## Femoral-on-Pelvic Hip Extension
“As a group, the hip extensor muscles are frequently required to produce large and powerful femoral­on­pelvic hip extension torque to rapidly accelerate the body forward and upward. Con­ sider, for example, the demands placed on the right hip extensors while one climbs a steep hill (Fig. 12.42). The flexed position of the right hip while the climber is carrying a heavy pack imposes a large external (flexion) torque at the hip. The flexed position, however, favors greater extension torque generation from the hip extensor muscles. Furthermore, with the hip mark­ edly flexed, many of the adductor muscles can produce an exten­ sion torque, thereby assisting the primary hip extensors. Activation of the low back extensor muscles helps support the flexed trunk, and also stabilizes the pelvis so that the strongly activated hip extensor muscles have a secure proximal attachment.” neumann
“Fig 12.42 underscores the functional interdependence among many of the muscles of the lower extremity, particularly those involved with activities that combine hip­and­knee extension and ankle plantar flexion, such as climbing, sprinting, cycling, or jumping. Consider, for instance, the kinetic interaction between the rectus femoris and the gluteus maximus—two principle muscles necessary to perform the climbing activity depicted in Fig. 12.42. Large knee extension torque is required from the rectus femoris to offset the large knee flexion torques produced not only by body weight (and the supported external load) but also by large active knee flexion torques generated by the simultaneously activated hamstring and gastrocnemius muscles. Because of the biarticular arrangement of the rectus femoris, large forces produced by this muscle to extend the knee will, by necessity, also contribute to a large hip	flexion torque: a torque that appears mechanically counterproductive to the movement of hip extension. Such muscles as the gluteus maximus and adductor magnus must thus match and exceed the hip flexion torque created by the active rectus femoris. Only then will the hip extensors accelerate the body upward and forward.” @neumannKinesiologyMusculoskeletalSystem2017
