---
title: Hip Abductor Muscles
---

![Muscles of the Hip Schematic @gilroyAtlasAnatomy2020 </br> 1: Psoas major </br> 2: Iliacus </br> 3: Iliopsoas </br> 4: Gluteus Maximus </br> 5: Gluteus Medius </br> 6: Gluteus Minimus </br> 7: Tensor Fascia Latae </br> 8: Piriformis </br> 9: Obturator internus </br> 10: Gemelli </br> 11: Quadratus Femoris](/The Archive/Anatomy/Skeletal Muscles/Lower limb muscles/images/gilroyatlas fig31.18 muscles of the hip schematic.png)

# Anatomy and Individual Actions


- “The gluteus	medius is a broad, fan­shaped muscle that attaches on the external surface of the ilium above the anterior gluteal line. The distal, more tendinous, part of the muscle attaches to the greater trochanter (see Fig. 12.39), more specifically to its superior-posterior and lateral facets (see Fig. 12.6).101,194 The distal attachment to the laterally­projected greater trochanter provides the gluteus medius with excellent leverage to perform hip abduc­ tion (see Fig. 12.30). The gluteus medius is the largest of the hip abductor muscles, occupying about 60–65% of the primary abductor cross­sectional area.43,72 The broad and fan­shaped gluteus medius has been considered as having three functional sets of fibers: anterior, middle, and posterior.204 All fibers contribute to abduction of the hip; however, from the anatomic position, the anterior and posterior fibers are antagonists in their horizontal plane actions. Leverage for some of these actions may change considerably when muscle activation is initiated from well outside the anatomic position.” @neumannKinesiologyMusculoskeletalSystem2017
- “The gluteus	 minimus lies deep and slightly anterior to the gluteus medius (Fig. 12.43). The gluteus minimus attaches proxi­ mally on the ilium—between the anterior and inferior gluteal lines—and distally on anterior	facet of the greater trochanter (see Fig. 12.6).72 The distal attachment also blends with the capsule of the hip joint.101,238 These muscular attachments may retract this part of the capsule away from the joint during motion—a mecha­ nism that may prevent capsular impingement.” @neumannKinesiologyMusculoskeletalSystem2017
- “The gluteus minimus is smaller than the gluteus medius, occupying about 20–30% of the cross­sectional area of the primary hip abductors.43,72 Although smaller than the gluteus medius, the gluteus minimus is equally respected for its role in stabilizing the hip in the stance phase of walking. All fibers of the gluteus minimus contribute to abduction. The more ante­ rior fibers also contribute to internal rotation and flexion, and the most posterior fibers contribute to external rotation.162 Fine­ wire EMG analysis of the gluteus minimus shows that the ante­ rior and posterior fibers are most active at slightly different times in the stance phase of walking, suggesting that they have differ­ ent roles in stabilizing the hip.” @neumannKinesiologyMusculoskeletalSystem2017
- “The tensor fascia latae is the smallest of the three primary hip abductors, occupying only about 4–10% of the primary abductor cross­sectional area.43,72 The anatomy of the tensor fasciae latae are discussed earlier in this chapter.” @neumannKinesiologyMusculoskeletalSystem2017
- “It is interesting to note that all the hip abductor muscles have an action as either internal or external rotators of the hip. The production of a pure frontal plane abduction torque therefore requires that the abductors completely neutralize one another’s horizontal plane torque potential.” @neumannKinesiologyMusculoskeletalSystem2017

# Primary Hip Abductors

- gluteus medius @neumannKinesiologyMusculoskeletalSystem2017
- gluteus minimus @neumannKinesiologyMusculoskeletalSystem2017
- TFL @neumannKinesiologyMusculoskeletalSystem2017

# Secondary Hip Abductors

- Piriformis @neumannKinesiologyMusculoskeletalSystem2017
- Sartorius @neumannKinesiologyMusculoskeletalSystem2017
- Rectus Femoris @neumannKinesiologyMusculoskeletalSystem2017
- Anterior (superior) fibers of the glut max @neumannKinesiologyMusculoskeletalSystem2017


# Hip Abductor Mechanism: Control of Frontal Plane Stability of the Pelvis during Walking
“The abduction torque produced by the hip abductor muscles is essential to the control of the frontal plane pelvic­on­femoral kinematics during walking. During most of the stance phase, the hip abductors stabilize the pelvis over the relatively fixed femur (see Fig. 12.36). During the stance phase, therefore, the hip abductor muscles have a role in controlling the pelvis in the frontal plane and, as discussed earlier, the horizontal plane.”
“The abduction torque produced by the hip abductor muscles is particularly important during the single­limb–support phase of gait. During this phase the opposite leg is off the ground and swinging forward. Without adequate abduction torque on the stance limb, the pelvis and trunk may drop uncontrollably toward the side of the swinging limb. The activation of the hip abductor muscle can be easily appreciated by palpating the gluteus medius just superior to the greater trochanter. The right gluteus medius, for example, becomes firm as the left leg lifts off the ground.”
“The frontal plane stabilizing function of hip abductor muscles is a very important component of walking. Furthermore, the force produced by the abductors during stance accounts for most of the compressive forces generated between the acetabulum and femoral head.”

# Dominant Role in the Production of Compression Force at the Hip


“Fig. 12.44 shows the major factors involved with maintaining frontal plane stability of the right hip during single­limb support, similar to that required during the midstance phase of walking. The forces created by active hip abductors and body weight create opposing torques that control the position and stability of the pelvis (within the frontal plane) over the femoral head. During single­limb support, the pelvis is comparable to a seesaw, with its fulcrum represented by the femoral head. When the seesaw is balanced, the counterclockwise (internal) torque produced by the right hip abductor force (HAF) equals the clockwise (external) torque caused by body weight (BW). This balance of opposing torques is called static rotary	equilibrium.”
“During single­limb support, the hip abductor muscles—in par­ ticular the gluteus medius—produce most of the vertical compres­ sion force across the hip.47 This important point is demonstrated by the model in Fig. 12.44.165,167 Note that the internal moment arm (D) used by the hip abductor muscles is about half the length of the external moment arm (D1) used by body weight.172 Given this length disparity, the hip abductor muscles must produce a force twice that of body weight in order to achieve stability during single­limb support. On every step, therefore, the acetabulum is pulled against the femoral head by the combined forces produced by the hip abductor muscles and the gravitational pull of body weight. To achieve static linear equilibrium, this downward force is counteracted by a joint reaction force (JRF) of equal magnitude but oriented in nearly the opposite direction (see Fig. 12.44). The joint reaction force is directed 10 to 15 degrees from vertical—an angle that is strongly influenced by the orientation of the hip abductor muscle force vector.” 
“The sample data supplied in Fig. 12.44 show how to estimate the approximate magnitude of the hip abductor force and hip joint reaction force. (For simplicity, all forces are assumed to act vertically, as shown in the seesaw model.) As shown in the calcula­ tions, an upward­directed joint reaction force (JRF) of 1873.8 N (421.3 lb) occurs when a person weighing 760.6 N (171 lb) is in single­limb support over the right limb. This reaction force is about 2.5 times body weight, 66%	 of	 which	 comes	 from	 the	 hip	 abductor	muscles. During walking, the joint reaction force is even greater because of the acceleration of the pelvis over the femoral head. Data based on three­dimensional computer modeling or direct measurements from strain gauges implanted into a hip prosthesis show that joint compression forces reach three to almost four times body weight during walking.36,47,217 These forces can increase to at least five or six times body weight while running or ascending and descending stairs or ramps.196 Joint reaction forces increase with increasing walking speed or when associated with significant gait deviations” 
“Although the hip abductor muscles contribute significantly to compression force while in single­limb support, these and other muscles also contribute significantly to hip joint forces during nonambulatory activities. Actively lifting the lower limb with the knee extended from a supine position (i.e., the “straight­leg raise”) has been shown to generate hip joint reaction forces of about 1.4 times body weight, or about 50% of the joint force naturally produced while walking on a level surface.201 Furthermore, per­ forming a unilateral (supine) hip “bridging” exercise generates a hip joint reaction force of about three times body weight, similar to forces produced while walking. The magnitudes of these forces must be kept in mind when prescribing exercises for patients fol­ lowing hip surgery, such as a total hip arthroplasty or fracture repair.”
“In most situations, the forces produced on the healthy hip by hip abductors or other muscles serve important physiologic func­ tions, such as stabilizing the femoral head within the acetabulum, assisting in the nutrition of the articular cartilage, and providing stimuli for normal development and shaping of joint structure in the growing child. The articular cartilage and trabecular bone normally protect the joint by safely dispersing large forces. A hip with arthritis, however, may no longer be able to provide this protection.”

# Weakness
“Several medical conditions are associated with weakness of the hip abductor muscles. These may include muscular dystrophy, Guillain-Barré syndrome, incomplete spinal cord injury, greater trochanteric pain syndrome, hip arthritis or degeneration, poliomyelitis, low back pain, or undefined pathology. A person with a painful or unstable hip often experiences “disuse” weakness and atrophy in the abductor muscles—a consequence of purposely avoiding their strong muscular activation as a way to minimize the associated compression force across the joint.” neuman
“The classic indicator of hip abductor weakness is the Trendelenburg sign.85 The patient is asked to stand in single-limb support over the suspected weak hip. The sign is positive if the pelvis drops to the side of the unsupported limb; in other words, the weak hip “falls” into pelvic-on-femoral adduction (see Fig. 12.22B). The clinician needs to be cautious, however, in interpreting and documenting the results of this test. The patient with a weak right hip abductor muscle, for example, may indeed drop the left side of the pelvis when asked to stand only on the right limb. The weakness may be masked, however, by a compensatory lean of the trunk to the right, especially if the weakness is marked. Leaning the trunk to the side of the weakness reduces the external torque demand on the abductor muscles by reducing the length of the external moment arm (see Fig. 12.44, D1). When observed while a person is walking, this compensatory lean to the side of weakness is referred to as a “gluteus medius limp” or “compensated Trendelenburg gait.” Using a cane in the hand opposite the weakened hip abductors can significantly improve this abnormal gait pattern” Neumann
“For often unexplained reasons, weakness of the hip abductor muscles often persists longer than in other muscle groups following hip surgery or hip pathology. This phenomenon occurs regardless of whether the gluteus medius and minimus are incised during surgery. The persistence of hip abductor weakness is similar to the often prolonged weakness of the quadriceps muscle at the knee following repair or injury of the anterior cruciate ligament (see Chapter 13). Neuman
“Regardless of the cause, the functional and pathomechanical implications of prolonged hip abductor weakness can be widereaching, especially considering their important kinesiologic significance in upright, weight-bearing activities.232 Prolonged weakness of the hip abductor muscles has been associated with many impairments or conditions, including gait deviations, difficulty standing on one limb, postural instability, patellofemoral pain syndrome, low back pain, increased risk of ankle sprain, knee instability, and falling in the elderly” neuman
“As a result of these and still other associations, significant EMG research has been devoted to discover which exercises most specifically target and thereby potentially strengthen the hip abductors, particularly the gluteus medius. Exercises that generate the most robust EMG response from the gluteus medius are assumed to reflect larger demands on this muscle. Research data clearly show that the higher “demand” exercises are those that specifically involve hip abduction (from femoral-on-pelvic or pelvic-on-femoral perspectives) performed with hip extension, internal or external rotation.180,202 These results are expected based on the primary or secondary actions of the various fibers of the gluteus medius listed in Table 12.3. Note, however, that Philippon and colleagues reported that a single-leg “bridging exercise” (with contralateral lower limb held in a “straight-leg raised” position) generated slightly higher EMG levels from the gluteus medius than any exercise involving side-lying hip abduction.180 The surprisingly high demands placed on the gluteus medius during the single-leg bridging exercise may provide insight into the muscular complexity of performing this seemingly simple, single plane action. Assume for the sake of discussion that the single-leg bridging exercise is powered by the right hip while the left lower extremity is held in a “straight-leg-raised” position. This exercise challenges the middle and posterior fibers of the right gluteus medius for extension support, while the middle fibers offset the strong adduction action of the right adductor magnus. Furthermore, the anterior fibers of the right gluteus medius are challenged to help offset both the external rotation potential of the right gluteus maximus as well as the external rotation (pelvic-onfemoral) gravitation torque placed on the right hip. Interestingly, this same EMG study reported far less gluteus medius activation during a bilateral bridging exercise. Dividing the hip extension torque across both hips reduces the demand on each individual gluteus medius to only 11% of maximum voluntary contraction (compared to 35% for a unilateral bridging exercise)” neuman

# Dysfunction
Greater trochanteric Pain syndrome (GTPS)
