---
title: Skeletal Muscle
---



# Exercise

The final common determinant of success in athletic events is what the muscles can do for you—that is, what strength they can give when it is needed, what power they can achieve in the performance of work, and how long they can continue their activity. 

# Muscular Strength

"The strength of a muscle is determined mainly by its size, with a maximal contractile force between 3 and 4 kg/cm2 of muscle cross-sectional area. Thus, a person who has enlarged his or her muscles through an exercise training program will have correspondingly increased muscle strength." @hallGuytonHallTextbook2021 

"To give an example of muscle strength, a world-class male weight lifter might have a quadriceps muscle with a cross-sectional area as great as 150 square centimeters. This measurement would translate into a maximal contractile strength of 525 kilograms (or 1155 pounds), with all this force applied to the patellar tendon. Therefore, one can readily understand how it is possible for this tendon at times to be ruptured or actually to be avulsed from its insertion into the tibia below the knee. Also, when such forces occur in tendons that span a joint, similar forces are applied to the surfaces of the joint or sometimes to ligaments spanning the joints, thus accounting for such happenings as displaced cartilages, compression fractures about the joint, and torn ligaments." @hallGuytonHallTextbook2021 

## Holding Strength

"The holding strength of muscles is about 40% greater than the contractile strength. That is, if a muscle is already contracted and a force then attempts to stretch out the muscle, as occurs when landing after a jump, this action requires about 40% more force than can be achieved by a shortening contraction. Therefore, the force of 525 kilograms previously calculated for the patellar tendon during muscle contraction becomes 735 kilograms (1617 pounds) during holding contractions, which further compounds the problems of the tendons, joints, and ligaments. It can also lead to internal tearing in the muscle. In fact, forceful stretching of a maximally contracted muscle is one of the surest ways to create the highest degree of muscle soreness." @hallGuytonHallTextbook2021 

# Mechanical Work

"Mechanical work performed by a muscle is the amount of force applied by the muscle multiplied by the distance over which the force is applied. The power of muscle contraction is different from muscle strength because power is a measure of the total amount of work that the muscle performs in a unit period of time. Power is therefore determined not only by the strength of muscle contraction but also by its distance of contraction and the number of times that it contracts each minute. Muscle power is generally measured in kilogram meters (kg-m) per minute. That is, a muscle that can lift 1-kilogram weight to a height of 1 meter or that can move some object laterally against a force of 1 kilogram for a distance of 1 meter in 1 minute is said to have a power of 1 kg-m/min. The maximal power achievable by all the muscles in the body of a highly trained athlete with all the muscles working together is approximately the following:"

# Muscular Power 



# Skeletal Muscle Degredation

## Facilitory

- Myostatin / Growth Differentiation Factor 8 (MSTN) @shahidiParaspinalMusclesIndividuals2024
- Tripartite Motif Containing 63/E3 Ubiquitin Ligase (TRIM63) @shahidiParaspinalMusclesIndividuals2024
- Forkhead Box O3 (FOXO3) @shahidiParaspinalMusclesIndividuals2024
- F-box only protein 32 (FBXO32) @shahidiParaspinalMusclesIndividuals2024
- Caspase-3 (CASP3) @shahidiParaspinalMusclesIndividuals2024
- Caspase-1 (CASP1) @shahidiParaspinalMusclesIndividuals2024

## Inhibitory

- Activin Receptor 2B (ACVR2B) @shahidiParaspinalMusclesIndividuals2024
