---
title: Sensitivity
subtitle: Measure of the true-positive rate
---

Sensitivity is a psychometric measure that quantifies the rate of true positives to total positives @monaghanFoundationalStatisticalPrinciples2021.
Sensitivity can apply to clinical tests that output a binary result: Normal vs Abnormal




# Calculation

Sensitivity quantifies true positive rate by finding the percent of people with disease who tested positive divided by total disease population.

$$
\textrm{Sensitivity} = \frac{(\textrm{True Positive})}{(\textrm{True Positive} + \textrm{False Negative})} = \frac{(\textrm{True Positive})}{(\textrm{Total Positive})}
$$


# Clinical Relevance

One should use sensitivity (and specificity) as a way to assess the performance of a diagnostic test @monaghanFoundationalStatisticalPrinciples2021.
To predict whether a particular person will truly have the disease based on a positive or negative test result, one should use [Positive predicitve value (PPV)]({{< var ref-psychometric.predictive-value.positive >}}) and [Negative predictive value (NPV)]({{< var ref-psychometric.predictive-value.negative >}}) @monaghanFoundationalStatisticalPrinciples2021.