---
title: "OIANs of all the muscles"
---

# Back

## Suboccipitals

| Muscle  | Origin  | Insertion | Nerve | Action |
|-|-|-|-|-|
| [Rectus Capitis Posterior Major]({{< var ref-rectus-capitis-posterior-major.path >}}) | {{< var ref-rectus-capitis-posterior-major.origin >}} | {{< var ref-rectus-capitis-posterior-major.insertion >}} | {{< var ref-rectus-capitis-posterior-major.nerve >}} | {{< var ref-rectus-capitis-posterior-major.action >}} |
|[Rectus Capitis Posterior Minor]({{< var ref-rectus-capitis-posterior-minor.path >}}) | {{< var ref-rectus-capitis-posterior-minor.origin >}} | {{< var ref-rectus-capitis-posterior-minor.insertion >}} | {{< var ref-rectus-capitis-posterior-minor.nerve >}} | {{< var ref-rectus-capitis-posterior-minor.action >}} |
| [Obliquus Capitis Superior]({{< var ref-obliquus-capitis-superior.path >}}) | {{< var ref-obliquus-capitis-superior.origin >}} | {{< var ref-obliquus-capitis-superior.insertion >}} | {{< var ref-obliquus-capitis-superior.nerve >}} | {{< var ref-obliquus-capitis-superior.action >}} |
| [Obliquus Capitis Inferior]({{< var ref-obliquus-capitis-inferior.path >}}) | {{< var ref-obliquus-capitis-inferior.origin >}} | {{< var ref-obliquus-capitis-inferior.insertion >}} | {{< var ref-obliquus-capitis-inferior.nerve >}} | {{< var ref-obliquus-capitis-inferior.action >}} |
: Suboccipital muscle group {.striped .hover }

## Prevertebral Muscles
- [Longus capitis]({{< var ref-longus-capitis.path >}})
- [Longus Colli Cervicis]({{< var ref-longus-colli-cervicis.path >}})
- [Rectus Capitis anterior]({{< var ref-rectus-capitis-anterior.path >}})
- [Rectus Capitis Lateralis]({{< var ref-rectus-capitis-lateralis.path >}})

| Muscle  | Origin  | Insertion | Nerve | Action |
|--------|----------|-----------|-------|--------|
| [Longus Capitis]({{< var ref-longus-capitis.path >}}) | {{< var ref-longus-capitis.origin >}} | {{< var ref-longus-capitis.insertion >}} | {{< var ref-longus-capitis.nerve >}} | {{< var ref-longus-capitis.action >}} |
| [Longus colli cervicis]({{< var ref-longus-colli-cervicis.path >}}) | {{< var ref-longus-colli-cervicis.origin >}} | {{< var ref-longus-colli-cervicis.insertion >}} | {{< var ref-longus-colli-cervicis.nerve >}} | {{< var ref-longus-colli-cervicis.action >}} |
| [Rectus Capitis Anterior]({{< var ref-rectus-capitis-anterior.path >}}) | {{< var ref-rectus-capitis-anterior.origin >}} | {{< var ref-rectus-capitis-anterior.insertion >}} | {{< var ref-rectus-capitis-anterior.nerve >}} | {{< var ref-rectus-capitis-anterior.action >}} |
| [Rectus Capitis Lateralis]({{< var ref-rectus-capitis-lateralis.path >}}) | {{< var ref-rectus-capitis-lateralis.origin >}} | {{< var ref-rectus-capitis-lateralis.insertion >}} | {{< var ref-rectus-capitis-lateralis.nerve >}} | {{< var ref-rectus-capitis-lateralis.action >}} |

: Prevertebral muscle group {.striped .hover}



## Superficial intrinsic back Muscles
- [Serratus posterior superior]({{< var ref-serratus-posterior-superior.path >}})
- [Serratus posterior inferior]({{< var ref-serratus-posterior-inferior.path >}})
- [Splenius capitis]({{< var ref-splenius-capitis.path >}})
- [Splenius cervicis]({{< var ref-splenius-cervicis.path >}})

| Muscle  | Origin  | Insertion | Nerve | Action |
|--------|----------|-----------|-------|--------|
|[Serratus Posterior Superior]({{< var ref-serratus-posterior-superior.path >}}) | {{< var ref-serratus-posterior-superior.origin >}} | {{< var ref-serratus-posterior-superior.insertion >}} | {{< var ref-serratus-posterior-superior.nerve >}} | {{< var ref-serratus-posterior-superior.action >}} |
|[Serratus Posterior Inferior]({{< var ref-serratus-posterior-inferior.path >}}) | {{< var ref-serratus-posterior-inferior.origin >}} | {{< var ref-serratus-posterior-inferior.insertion >}} | {{< var ref-serratus-posterior-inferior.nerve >}} | {{< var ref-serratus-posterior-inferior.action >}} |
|[Splenius Capitis]({{< var ref-splenius-capitis.path >}}) | {{< var ref-splenius-capitis.origin >}} | {{< var ref-splenius-capitis.insertion >}} | {{< var ref-splenius-capitis.nerve >}} | {{< var ref-splenius-capitis.action >}} |
|[Splenius Cervicis]({{< var ref-splenius-cervicis.path >}}) | {{< var ref-splenius-cervicis.origin >}} | {{< var ref-splenius-cervicis.insertion >}} | {{< var ref-splenius-cervicis.nerve >}} | {{< var ref-splenius-cervicis.action >}} |

: Superficial intrinsic back Muscles OIANs {.striped .hover}

## Intermediate intrinsic back muscles (Erector Spinae)
- Iliocostalis
    - [Iliocostalis Cervicis]({{< var ref-iliocostalis-cervicis.path >}})
    - [Iliocostalis Thoracis]({{< var ref-iliocostalis-thoracis.path >}})
    - [Iliocostalis lumborum]({{< var ref-iliocostalis-lumborum.path >}})
- Longissimus
    - [Longissimus Capitis]({{< var ref-longissimus-capitis.path >}})
    - [Longissimus Cervicis]({{< var ref-longissimus-cervicis.path >}})
    - [Longissimus Thoracis]({{< var ref-longissimus-thoracis.path >}})
- Spinalis
    - [Spinalis Cervicis]({{< var ref-spinalis-cervicis.path >}})
    - [Spinalis Thoracis]({{< var ref-spinalis-thoracis.path >}})

| Muscle  | Origin | Insertion | Nerve | Action |
|------|--------|-------|----------|--------|
| [Iliocostalis cervicis]({{< var ref-iliocostalis-cervicis.path >}}) | {{< var ref-iliocostalis-cervicis.origin >}} | {{< var ref-iliocostalis-cervicis.insertion >}} | {{< var ref-iliocostalis-cervicis.nerve >}} | {{< var ref-iliocostalis-cervicis.action >}} |
| [Iliocostalis thoracis]({{< var ref-iliocostalis-thoracis.path >}}) | {{< var ref-iliocostalis-thoracis.origin >}} | {{< var ref-iliocostalis-thoracis.insertion >}} | {{< var ref-iliocostalis-thoracis.nerve >}} | {{< var ref-iliocostalis-thoracis.action >}} |
| [Iliocostalis lumborum]({{< var ref-iliocostalis-lumborum.path >}}) | {{< var ref-iliocostalis-lumborum.origin >}} | {{< var ref-iliocostalis-lumborum.insertion >}} | {{< var ref-iliocostalis-lumborum.nerve >}}  | {{< var ref-iliocostalis-lumborum.action >}} |
| [Longissimus Capitis]({{< var ref-longissimus-capitis.path >}}) | {{< var ref-longissimus-capitis.origin >}} | {{< var ref-longissimus-capitis.insertion >}} | {{< var ref-longissimus-capitis.nerve >}} | {{< var ref-longissimus-capitis.action >}} |
| [Longissimus Cervicis]({{< var ref-longissimus-cervicis.path >}}) | {{< var ref-longissimus-cervicis.origin >}} | {{< var ref-longissimus-cervicis.insertion >}} | {{< var ref-longissimus-cervicis.nerve >}} | {{< var ref-longissimus-cervicis.action >}} |
| [Longissimus Thoracis]({{< var ref-longissimus-thoracis.path >}}) | {{< var ref-longissimus-thoracis.origin >}} | {{< var ref-longissimus-thoracis.insertion >}} | {{< var ref-longissimus-thoracis.nerve >}}  | {{< var ref-longissimus-thoracis.action >}} |
| [Spinalis Cervicis]({{< var ref-spinalis-cervicis.path >}}) | {{< var ref-spinalis-cervicis.origin >}} | {{< var ref-spinalis-cervicis.insertion >}} | {{< var ref-spinalis-cervicis.nerve >}} | {{< var ref-spinalis-cervicis.action >}} |
| [Spinalis Thoracis]({{< var ref-spinalis-thoracis.path >}}) | {{< var ref-spinalis-thoracis.origin >}} | {{< var ref-spinalis-thoracis.insertion >}} | {{< var ref-spinalis-thoracis.nerve >}} | {{< var ref-spinalis-thoracis.action >}} |

: Erector Spinae OIAN {.striped .hover}


## Transversospinalis Muscles 

| Muscle | Origin | Insertion | Nerve | Action |
|------|--------|-------|----------|--------|
| [Rotatores Breves]({{< var ref-rotatores-breves.path >}}) | {{< var ref-rotatores-breves.origin >}} | {{< var ref-rotatores-breves.insertion >}} | {{< var ref-rotatores-breves.nerve >}} | {{< var ref-rotatores-breves.action >}} |
| [Rotatores Longi]({{< var ref-rotatores-longi.path >}}) | {{< var ref-rotatores-longi.origin >}} | {{< var ref-rotatores-longi.insertion >}} | {{< var ref-rotatores-longi.nerve >}} | {{< var ref-rotatores-longi.action >}} |
| [Multifidi]({{< var ref-multifidi.path >}}) | {{< var ref-multifidi.origin >}} | {{< var ref-multifidi.insertion >}} | {{< var ref-multifidi.nerve >}} | {{< var ref-multifidi.action >}} |
| [Semispinalis Capitis]({{< var ref-semispinalis-capitis.path >}}) | {{< var ref-semispinalis-capitis.origin >}} | {{< var ref-semispinalis-capitis.insertion >}} | {{< var ref-semispinalis-capitis.nerve >}} | {{< var ref-semispinalis-capitis.action >}} |
| [Semispinalis Cervicis]({{< var ref-semispinalis-cervicis.path >}}) | {{< var ref-semispinalis-cervicis.origin >}} | {{< var ref-semispinalis-cervicis.insertion >}} | {{< var ref-semispinalis-cervicis.nerve >}} | {{< var ref-semispinalis-cervicis.action >}} |
| [Semispinalis Thoracis]({{< var ref-semispinalis-thoracis.path >}}) | {{< var ref-semispinalis-thoracis.origin >}} | {{< var ref-semispinalis-thoracis.insertion >}} | {{< var ref-semispinalis-thoracis.nerve >}} | {{< var ref-semispinalis-thoracis.action >}} |

: Transversospinalis Muscles OIAN {.striped .hover}


## Deep Segmental Back Muscles 

| Muscle  | Origin | Insertion | Nerve | Action |
|------|--------|-------|----------|--------|
| [Interspinales Cervicis]({{< var ref-interspinales-cervicis.path >}}) | {{< var ref-interspinales-cervicis.origin >}} | {{< var ref-interspinales-cervicis.insertion >}} | {{< var ref-interspinales-cervicis.nerve >}} | {{< var ref-interspinales-cervicis.action >}} |
| [Interspinales Lumbora]({{< var ref-interspinales-lumbora.path >}}) | {{< var ref-interspinales-lumbora.origin >}} | {{< var ref-interspinales-lumbora.insertion >}} | {{< var ref-interspinales-lumbora.nerve >}} | {{< var ref-interspinales-lumbora.action >}} |

: Deep Segmental Back Muscles OIAN {.striped .hover}

# Head and Neck

## Muscles of Facial Expression


| Muscle  | Origin | Insertion | Nerve | Action |
|----------|--------|-------|-----|--------|
| **Calvaria** | | | | |
| [Occipitofrontalis (Frontal belly)]({{< var ref-occipitofrontalis.path >}}) | {{< var ref-occipitofrontalis.origin >}} | {{< var ref-occipitofrontalis.insertion >}} | {{< var ref-occipitofrontalis.nerve >}} | {{< var ref-occipitofrontalis.action >}} |
| **Palpebral Fissure and Nose** | | | | |
| [Procerus]({{< var ref-procerus.path >}}) | {{< var ref-procerus.origin >}} | {{< var ref-procerus.insertion >}} | {{< var ref-procerus.nerve >}} | {{< var ref-procerus.action >}} |
| [Orbicularis Oculi]({{< var ref-orbicularis-oculi.path >}}) | {{< var ref-orbicularis-oculi.origin >}} | {{< var ref-orbicularis-oculi.insertion >}} | {{< var ref-orbicularis-oculi.nerve >}} | {{< var ref-orbicularis-oculi.action >}} |
| [Nasalis]({{< var ref-nasalis.path >}}) | {{< var ref-nasalis.origin >}} | {{< var ref-nasalis.insertion >}} | {{< var ref-nasalis.nerve >}} | {{< var ref-nasalis.action >}} |
| [Levator Labii superioris alaeque nasi]({{< var ref-levator-labii-superioris-alaeque-nasi.path >}}) | {{< var ref-levator-labii-superioris-alaeque-nasi.origin >}} | {{< var ref-levator-labii-superioris-alaeque-nasi.insertion >}} | {{< var ref-levator-labii-superioris-alaeque-nasi.nerve >}} | {{< var ref-levator-labii-superioris-alaeque-nasi.action >}} |
| **Ear** | | | | |
| [Anterior Auricular Muscle]({{< var ref-anterior-auricular-muscle.path >}}) | {{< var ref-anterior-auricular-muscle.origin >}} | {{< var ref-anterior-auricular-muscle.insertion >}} | {{< var ref-anterior-auricular-muscle.nerve >}} | {{< var ref-anterior-auricular-muscle.action >}} |
| Muscle  | Origin | Insertion | Nerve | Action |
|------|--------|-------|----------|--------|
| [Superior Auricular Muscle]({{< var ref-superior-auricular-muscle.path >}}) | {{< var ref-superior-auricular-muscle.origin >}} | {{< var ref-superior-auricular-muscle.insertion >}} | {{< var ref-superior-auricular-muscle.nerve >}} | {{< var ref-superior-auricular-muscle.action >}} |
| [Posterior Auricular Muscle]({{< var ref-posterior-auricular-muscle.path >}}) | {{< var ref-posterior-auricular-muscle.origin >}} | {{< var ref-posterior-auricular-muscle.insertion >}} | {{< var ref-posterior-auricular-muscle.nerve >}} | {{< var ref-posterior-auricular-muscle.action >}} |
| **Mouth** | | | | |
| [Zygomaticus major]({{< var ref-zygomaticus-major.path >}}) | {{< var ref-zygomaticus-major.origin >}} | {{< var ref-zygomaticus-major.insertion >}} | {{< var ref-zygomaticus-major.nerve >}} | {{< var ref-zygomaticus-major.action >}} |
| [Zygomaticus Minor]({{< var ref-zygomaticus-minor.path >}}) | {{< var ref-zygomaticus-minor.origin >}} | {{< var ref-zygomaticus-minor.insertion >}} | {{< var ref-zygomaticus-minor.nerve >}} | {{< var ref-zygomaticus-minor.action >}} |
| [Levator Labii superioris alaeque nasi]({{< var ref-levator-labii-superioris-alaeque-nasi.path >}}) | {{< var ref-levator-labii-superioris-alaeque-nasi.origin >}} | {{< var ref-levator-labii-superioris-alaeque-nasi.insertion >}} | {{< var ref-levator-labii-superioris-alaeque-nasi.nerve >}} | {{< var ref-levator-labii-superioris-alaeque-nasi.action >}} |
| [Levator Labii superioris]({{< var ref-levator-labii-superioris.path >}}) | {{< var ref-levator-labii-superioris.origin >}} | {{< var ref-levator-labii-superioris.insertion >}} | {{< var ref-levator-labii-superioris.nerve >}} | {{< var ref-levator-labii-superioris.action >}} |
| [Depressor labii inferioris]({{< var ref-depressor-labii-inferioris.path >}}) | {{< var ref-depressor-labii-inferioris.origin >}} | {{< var ref-depressor-labii-inferioris.insertion >}} | {{< var ref-depressor-labii-inferioris.nerve >}} | {{< var ref-depressor-labii-inferioris.action >}} |
| [Levator Anguli Oris]({{< var ref-levator-anguli-oris.path >}}) | {{< var ref-levator-anguli-oris.origin >}} | {{< var ref-levator-anguli-oris.insertion >}} | {{< var ref-levator-anguli-oris.nerve >}} | {{< var ref-levator-anguli-oris.action >}} |
| [Depressor Anguli Oris]({{< var ref-depressor-anguli-oris.path >}}) | {{< var ref-depressor-anguli-oris.origin >}} | {{< var ref-depressor-anguli-oris.insertion >}} | {{< var ref-depressor-anguli-oris.nerve >}} | {{< var ref-depressor-anguli-oris.action >}} |
| [Buccinator]({{< var ref-buccinator.path >}}) | {{< var ref-buccinator.origin >}} | {{< var ref-buccinator.insertion >}} | {{< var ref-buccinator.nerve >}} | {{< var ref-buccinator.action >}} |
| [Orbicularis Oris]({{< var ref-orbicularis-oris.path >}}) | {{< var ref-orbicularis-oris.origin >}} | {{< var ref-orbicularis-oris.insertion >}} | {{< var ref-orbicularis-oris.nerve >}} | {{< var ref-orbicularis-oris.action >}} |
| [Risorius]({{< var ref-risorius.path >}}) | {{< var ref-risorius.origin >}} | {{< var ref-risorius.insertion >}} | {{< var ref-risorius.nerve >}} | {{< var ref-risorius.action >}} |
| [Mentalis muscle]({{< var ref-mentalis-muscle.path >}}) | {{< var ref-mentalis-muscle.origin >}} | {{< var ref-mentalis-muscle.insertion >}} | {{< var ref-mentalis-muscle.nerve >}} | {{< var ref-mentalis-muscle.action >}} |
| **Neck** | | | | |
| [Platysma muscle]({{< var ref-platysma.path >}}) | {{< var ref-platysma.origin >}} | {{< var ref-platysma.insertion >}} | {{< var ref-platysma.nerve >}} | {{< var ref-platysma.action >}} |

: Muscles of Facial Expression OIAN {.striped .hover}



::: {.callout-note collapse="true"}

## Muscles of Mastication

| Muscle  | Origin | Insertion | Nerve | Action |
|----------|--------|-------|-----|--------|
| [Masseter muscle]({{< var ref-masseter.path >}}) | {{< var ref-masseter.origin >}} | {{< var ref-masseter.insertion >}} | {{< var ref-masseter.nerve >}} | {{< var ref-masseter.action >}} |
| [Temporalis muscle]({{< var ref-temporalis.path >}}) | {{< var ref-temporalis.origin >}} | {{< var ref-temporalis.insertion >}} | {{< var ref-temporalis.nerve >}} | {{< var ref-temporalis.action >}} |
| [Lateral Pterygoid]({{< var ref-lateral-pterygoid.path >}}) | {{< var ref-lateral-pterygoid.origin >}} | {{< var ref-lateral-pterygoid.insertion >}} | {{< var ref-lateral-pterygoid.nerve >}} | {{< var ref-lateral-pterygoid.action >}} |
| [Medial Pterygoid]({{< var ref-medial-pterygoid.path >}}) | {{< var ref-medial-pterygoid.origin >}} | {{< var ref-medial-pterygoid.insertion >}} | {{< var ref-medial-pterygoid.nerve >}} | {{< var ref-medial-pterygoid.action >}} |
: Muscles of Mastication OIAN {.striped .hover}


## Muscles of the Neck

### Superficial Neck Muscles

- Platysma
- Sternocleidomastoid
- Trapezius

### Nuchal muscles (Intrinsic back muscles)

| Muscle  | Origin  | Insertion | Nerve | Action |
|--------|----------|-----------|-------|--------|
| [Semispinalis Capitis]({{< var ref-semispinalis-capitis.path >}}) | {{< var ref-semispinalis-capitis.origin >}} | {{< var ref-semispinalis-capitis.insertion >}} | {{< var ref-semispinalis-capitis.nerve >}} | {{< var ref-semispinalis-capitis.action >}} |
| [Semispinalis Cervicis]({{< var ref-semispinalis-cervicis.path >}}) | {{< var ref-semispinalis-cervicis.origin >}} | {{< var ref-semispinalis-cervicis.insertion >}} | {{< var ref-semispinalis-cervicis.nerve >}} | {{< var ref-semispinalis-cervicis.action >}} |
|[Splenius Capitis]({{< var ref-splenius-capitis.path >}}) | {{< var ref-splenius-capitis.origin >}} | {{< var ref-splenius-capitis.insertion >}} | {{< var ref-splenius-capitis.nerve >}} | {{< var ref-splenius-capitis.action >}} |
|[Splenius Cervicis]({{< var ref-splenius-cervicis.path >}}) | {{< var ref-splenius-cervicis.origin >}} | {{< var ref-splenius-cervicis.insertion >}} | {{< var ref-splenius-cervicis.nerve >}} | {{< var ref-splenius-cervicis.action >}} |
| [Longissimus Capitis]({{< var ref-longissimus-capitis.path >}}) | {{< var ref-longissimus-capitis.origin >}} | {{< var ref-longissimus-capitis.insertion >}} | {{< var ref-longissimus-capitis.nerve >}} | {{< var ref-longissimus-capitis.action >}} |
| [Longissimus Cervicis]({{< var ref-longissimus-cervicis.path >}}) | {{< var ref-longissimus-cervicis.origin >}} | {{< var ref-longissimus-cervicis.insertion >}} | {{< var ref-longissimus-cervicis.nerve >}} | {{< var ref-longissimus-cervicis.action >}} |
| [Iliocostalis cervicis]({{< var ref-iliocostalis-cervicis.path >}}) | {{< var ref-iliocostalis-cervicis.origin >}} | {{< var ref-iliocostalis-cervicis.insertion >}} | {{< var ref-iliocostalis-cervicis.nerve >}} | {{< var ref-iliocostalis-cervicis.action >}} |
| [Rectus Capitis Posterior Major]({{< var ref-rectus-capitis-posterior-major.path >}}) | {{< var ref-rectus-capitis-posterior-major.origin >}} | {{< var ref-rectus-capitis-posterior-major.insertion >}} | {{< var ref-rectus-capitis-posterior-major.nerve >}} | {{< var ref-rectus-capitis-posterior-major.action >}} |
|[Rectus Capitis Posterior Minor]({{< var ref-rectus-capitis-posterior-minor.path >}}) | {{< var ref-rectus-capitis-posterior-minor.origin >}} | {{< var ref-rectus-capitis-posterior-minor.insertion >}} | {{< var ref-rectus-capitis-posterior-minor.nerve >}} | {{< var ref-rectus-capitis-posterior-minor.action >}} |
| [Obliquus Capitis Superior]({{< var ref-obliquus-capitis-superior.path >}}) | {{< var ref-obliquus-capitis-superior.origin >}} | {{< var ref-obliquus-capitis-superior.insertion >}} | {{< var ref-obliquus-capitis-superior.nerve >}} | {{< var ref-obliquus-capitis-superior.action >}} |
| [Obliquus Capitis Inferior]({{< var ref-obliquus-capitis-inferior.path >}}) | {{< var ref-obliquus-capitis-inferior.origin >}} | {{< var ref-obliquus-capitis-inferior.insertion >}} | {{< var ref-obliquus-capitis-inferior.nerve >}} | {{< var ref-obliquus-capitis-inferior.action >}} |

: Nuchal muscles (Intrinsic back muscles) {.striped .hover}


# Thoracoappendicular

## Anterior Axioappendicular

| Muscle  | Origin | Insertion | Nerve | Action |
|------|--------|-------|----------|--------|
| [Pectoralis Major]({{< var ref-pectoralis-major.path >}}) | {{< var ref-pectoralis-major.origin >}} | {{< var ref-pectoralis-major.insertion >}} | {{< var ref-pectoralis-major.nerve >}} | {{< var ref-pectoralis-major.action >}} |
| [Pectoralis Minor]({{< var ref-pectoralis-minor.path >}}) | {{< var ref-pectoralis-minor.origin >}} | {{< var ref-pectoralis-minor.insertion >}} | {{< var ref-pectoralis-minor.nerve >}} | {{< var ref-pectoralis-minor.action >}} |
| [Subclavius]({{< var ref-subclavius.path >}}) | {{< var ref-subclavius.origin >}} | {{< var ref-subclavius.insertion >}} | {{< var ref-subclavius.nerve >}} | {{< var ref-subclavius.action >}} |
| [Serratus Anterior]({{< var ref-serratus-anterior.path >}}) | {{< var ref-serratus-anterior.origin >}} | {{< var ref-serratus-anterior.insertion >}} | {{< var ref-serratus-anterior.nerve >}} | {{< var ref-serratus-anterior.action >}} |
: Anterior Axioappendicular Muscles {.striped .hover}

## Posterior Axioappendicular

| Muscle  | Origin | Insertion | Nerve | Action |
|------|--------|-------|----------|--------|
| [Upper Trapezius]({{< var ref-upper-trapezius.path >}}) | {{< var ref-upper-trapezius.origin >}} | {{< var ref-upper-trapezius.insertion >}} | {{< var ref-upper-trapezius.nerve >}} | {{< var ref-upper-trapezius.action >}} |
| [Middle Trapezius]({{< var ref-middle-trapezius.path >}}) | {{< var ref-middle-trapezius.origin >}} | {{< var ref-middle-trapezius.insertion >}} | {{< var ref-middle-trapezius.nerve >}} | {{< var ref-middle-trapezius.action >}} |
| [Lower Trapezius]({{< var ref-lower-trapezius.path >}}) | {{< var ref-lower-trapezius.origin >}} | {{< var ref-lower-trapezius.insertion >}} | {{< var ref-lower-trapezius.nerve >}} | {{< var ref-lower-trapezius.action >}} |
| [Latissimus Dorsi]({{< var ref-latissimus-dorsi.path >}}) | {{< var ref-latissimus-dorsi.origin >}} | {{< var ref-latissimus-dorsi.insertion >}} | {{< var ref-latissimus-dorsi.nerve >}} | {{< var ref-latissimus-dorsi.action >}} |
: Superficial Posterior Axioappendicular Muscles {.striped .hover}



| Muscle  | Origin | Insertion | Nerve | Action |
|------|--------|-------|----------|--------|
| [Levator Scapulae]({{< var ref-levator-scapulae.path >}}) | {{< var ref-levator-scapulae.origin >}} | {{< var ref-levator-scapulae.insertion >}} | {{< var ref-levator-scapulae.nerve >}} | {{< var ref-levator-scapulae.action >}} |
| [Rhomboid Major]({{< var ref-rhomboid-major.path >}}) | {{< var ref-rhomboid-major.origin >}} | {{< var ref-rhomboid-major.insertion >}} | {{< var ref-rhomboid-major.nerve >}} | {{< var ref-rhomboid-major.action >}} |
| [Rhomboid Minor]({{< var ref-rhomboid-minor.path >}}) | {{< var ref-rhomboid-minor.origin >}} | {{< var ref-rhomboid-minor.insertion >}} | {{< var ref-rhomboid-minor.nerve >}} | {{< var ref-rhomboid-minor.action >}} |
: Deep Posterior Axioappendicular Muscles  {.striped .hover}

# Scapulohumeral

Scapulohumeral muscles AKA intrinsic shoulder muscles

| Muscle  | Origin | Insertion | Nerve | Action |
|------|--------|-------|----------|--------|
| [Deltoid]({{< var ref-deltoid.path >}}) | {{< var ref-deltoid.origin >}} | {{< var ref-deltoid.insertion >}} | {{< var ref-deltoid.nerve >}} | {{< var ref-deltoid.action >}} |
| [Deltoid (*anterior head*)]({{< var ref-deltoid-muscle-anterior.path >}}) | {{< var ref-deltoid-muscle-anterior.origin >}} | {{< var ref-deltoid-muscle-anterior.insertion >}} | {{< var ref-deltoid-muscle-anterior.nerve >}} | {{< var ref-deltoid-muscle-anterior.action >}} |
| [Deltoid (*lateral head*)]({{< var ref-deltoid-muscle-lateral.path >}}) | {{< var ref-deltoid-muscle-lateral.origin >}} | {{< var ref-deltoid-muscle-lateral.insertion >}} | {{< var ref-deltoid-muscle-lateral.nerve >}} | {{< var ref-deltoid-muscle-lateral.action >}} |
| [Deltoid (*posterior head*)]({{< var ref-deltoid-muscle-posterior.path >}}) | {{< var ref-deltoid-muscle-posterior.origin >}} | {{< var ref-deltoid-muscle-posterior.insertion >}} | {{< var ref-deltoid-muscle-posterior.nerve >}} | {{< var ref-deltoid-muscle-posterior.action >}} |
| [Teres Major]({{< var ref-teres-major.path >}}) | {{< var ref-teres-major.origin >}} | {{< var ref-teres-major.insertion >}} | {{< var ref-teres-major.nerve >}} | {{< var ref-teres-major.action >}} |
| [Supraspinatus]({{< var ref-supraspinatus.path >}}) | {{< var ref-supraspinatus.origin >}} | {{< var ref-supraspinatus.insertion >}} | {{< var ref-supraspinatus.nerve >}} | {{< var ref-supraspinatus.action >}} |
| [Infraspinatus]({{< var ref-infraspinatus.path >}}) | {{< var ref-infraspinatus.origin >}} | {{< var ref-infraspinatus.insertion >}} | {{< var ref-infraspinatus.nerve >}} | {{< var ref-infraspinatus.action >}} |
| [Teres Minor]({{< var ref-teres-minor.path >}}) | {{< var ref-teres-minor.origin >}} | {{< var ref-teres-minor.insertion >}} | {{< var ref-teres-minor.nerve >}} | {{< var ref-teres-minor.action >}} |
| [Subscapularis]({{< var ref-subscapularis.path >}}) | {{< var ref-subscapularis.origin >}} | {{< var ref-subscapularis.insertion >}} | {{< var ref-subscapularis.nerve >}} | {{< var ref-subscapularis.action >}} |
: {.striped .hover}

# Arm

## Anterior Arm

| Muscle  | Origin | Insertion | Nerve | Action |
|------|--------|-------|----------|--------|
| [Biceps Brachii (Long head)]({{< var ref-biceps-brachii-long-head.path >}}) | {{< var ref-biceps-brachii-long-head.origin >}} | {{< var ref-biceps-brachii-long-head.insertion >}} | {{< var ref-biceps-brachii-long-head.nerve >}} | {{< var ref-biceps-brachii-long-head.action >}} |
| [Biceps Brachii (Short head)]({{< var ref-biceps-brachii-short-head.path >}}) | {{< var ref-biceps-brachii-short-head.origin >}} | {{< var ref-biceps-brachii-short-head.insertion >}} | {{< var ref-biceps-brachii-short-head.nerve >}} | {{< var ref-biceps-brachii-short-head.action >}} |
| [Brachialis]({{< var ref-brachialis.path >}}) | {{< var ref-brachialis.origin >}} | {{< var ref-brachialis.insertion >}} | {{< var ref-brachialis.nerve >}} | {{< var ref-brachialis.action >}} |
| [Coracobrachialis]({{< var ref-coracobrachialis.path >}}) | {{< var ref-coracobrachialis.origin >}} | {{< var ref-coracobrachialis.insertion >}} | {{< var ref-coracobrachialis.nerve >}} | {{< var ref-coracobrachialis.action >}} |
: Muscles of the Anterior Compartment of the Arm {.striped .hover}


## Posterior Arm


| Muscle  | Origin | Insertion | Nerve | Action |
|------|--------|-------|----------|--------|
| [Triceps brachii (Long head)]({{< var ref-triceps-brachii-long-head.path >}}) | {{< var ref-triceps-brachii-long-head.origin >}} | {{< var ref-triceps-brachii-long-head.insertion >}} | {{< var ref-triceps-brachii-long-head.nerve >}} | {{< var ref-triceps-brachii-long-head.action >}} |
| [Triceps brachii (Medial head)]({{< var ref-triceps-brachii-medial-head.path >}}) | {{< var ref-triceps-brachii-medial-head.origin >}} | {{< var ref-triceps-brachii-medial-head.insertion >}} | {{< var ref-triceps-brachii-medial-head.nerve >}} | {{< var ref-triceps-brachii-medial-head.action >}} |
| [Triceps brachii (Lateral head)]({{< var ref-triceps-brachii-lateral-head.path >}}) | {{< var ref-triceps-brachii-lateral-head.origin >}} | {{< var ref-triceps-brachii-lateral-head.insertion >}} | {{< var ref-triceps-brachii-lateral-head.nerve >}} | {{< var ref-triceps-brachii-lateral-head.action >}} |
| [Anconeus]({{< var ref-anconeus.path >}}) | {{< var ref-anconeus.origin >}} | {{< var ref-anconeus.insertion >}} | {{< var ref-anconeus.nerve >}} | {{< var ref-anconeus.action >}} |
: Muscles of the Posterior Compartment of the Arm {.striped .hover}


# Forearm

## Anterior Forearm

| Muscle  | Origin | Insertion | Nerve | Action |
|------|--------|-------|----------|--------|
| [Pronator Teres]({{< var ref-pronator-teres.path >}}) | {{< var ref-pronator-teres.origin >}} | {{< var ref-pronator-teres.insertion >}} | {{< var ref-pronator-teres.nerve >}} | {{< var ref-pronator-teres.action >}} |
| [Flexor Carpi Radialis]({{< var ref-flexor-carpi-radialis.path >}}) | {{< var ref-flexor-carpi-radialis.origin >}} | {{< var ref-flexor-carpi-radialis.insertion >}} | {{< var ref-flexor-carpi-radialis.nerve >}} | {{< var ref-flexor-carpi-radialis.action >}} |
| [Palmaris Longus]({{< var ref-palmaris-longus.path >}}) | {{< var ref-palmaris-longus.origin >}} | {{< var ref-palmaris-longus.insertion >}} | {{< var ref-palmaris-longus.nerve >}} | {{< var ref-palmaris-longus.action >}} |
| [Flexor Carpi Ulnaris]({{< var ref-flexor-carpi-ulnaris.path >}}) | {{< var ref-flexor-carpi-ulnaris.origin >}} | {{< var ref-flexor-carpi-ulnaris.insertion >}} | {{< var ref-flexor-carpi-ulnaris.nerve >}} | {{< var ref-flexor-carpi-ulnaris.action >}} |
: Superficial {.striped .hover}

| Muscle  | Origin | Insertion | Nerve | Action |
|------|--------|-------|----------|--------|
| [Flexor Digitorum Superficialis]({{< var ref-flexor-digitorum-superficialis.path >}}) | {{< var ref-flexor-digitorum-superficialis.origin >}} | {{< var ref-flexor-digitorum-superficialis.insertion >}} | {{< var ref-flexor-digitorum-superficialis.nerve >}} | {{< var ref-flexor-digitorum-superficialis.action >}} |
: Intermediate {.striped .hover}

| Muscle  | Origin | Insertion | Nerve | Action |
|------|--------|-------|----------|--------|
| [Flexor Digitorum Profundus]({{< var ref-flexor-digitorum-profundus.path >}}) | {{< var ref-flexor-digitorum-profundus.origin >}} | {{< var ref-flexor-digitorum-profundus.insertion >}} | {{< var ref-flexor-digitorum-profundus.nerve >}} | {{< var ref-flexor-digitorum-profundus.action >}} |
| [Flexor Pollicis Longus]({{< var ref-flexor-pollicis-longus.path >}}) | {{< var ref-flexor-pollicis-longus.origin >}} | {{< var ref-flexor-pollicis-longus.insertion >}} | {{< var ref-flexor-pollicis-longus.nerve >}} | {{< var ref-flexor-pollicis-longus.action >}} |
| [Pronator Quadratus]({{< var ref-pronator-quadratus.path >}}) | {{< var ref-pronator-quadratus.origin >}} | {{< var ref-pronator-quadratus.insertion >}} | {{< var ref-pronator-quadratus.nerve >}} | {{< var ref-pronator-quadratus.action >}} |
| [Brachioradialis]({{< var ref-brachioradialis.path >}}) | {{< var ref-brachioradialis.origin >}} | {{< var ref-brachioradialis.insertion >}} | {{< var ref-brachioradialis.nerve >}} | {{< var ref-brachioradialis.action >}} |
: Deep {.striped .hover}

## Posterior Forearm

| Muscle  | Origin | Insertion | Nerve | Action |
|------|--------|-------|----------|--------|
| [Extensor Carpi Radialis Longus]({{< var ref-extensor-carpi-radialis-longus.path >}}) | {{< var ref-extensor-carpi-radialis-longus.origin >}} | {{< var ref-extensor-carpi-radialis-longus.insertion >}} | {{< var ref-extensor-carpi-radialis-longus.nerve >}} | {{< var ref-extensor-carpi-radialis-longus.action >}} |
| [Extensor Carpi Radialis Brevis]({{< var ref-extensor-carpi-radialis-brevis.path >}}) | {{< var ref-extensor-carpi-radialis-brevis.origin >}} | {{< var ref-extensor-carpi-radialis-brevis.insertion >}} | {{< var ref-extensor-carpi-radialis-brevis.nerve >}} | {{< var ref-extensor-carpi-radialis-brevis.action >}} |
| [Extensor Digitorum]({{< var ref-extensor-digitorum.path >}}) | {{< var ref-extensor-digitorum.origin >}} | {{< var ref-extensor-digitorum.insertion >}} | {{< var ref-extensor-digitorum.nerve >}} | {{< var ref-extensor-digitorum.action >}} |
| [Extensor Digiti Minimi]({{< var ref-extensor-digiti-minimi.path >}}) | {{< var ref-extensor-digiti-minimi.origin >}} | {{< var ref-extensor-digiti-minimi.insertion >}} | {{< var ref-extensor-digiti-minimi.nerve >}} | {{< var ref-extensor-digiti-minimi.action >}} |
| [Extensor Carpi Ulnaris]({{< var ref-extensor-carpi-ulnaris.path >}}) | {{< var ref-extensor-carpi-ulnaris.origin >}} | {{< var ref-extensor-carpi-ulnaris.insertion >}} | {{< var ref-extensor-carpi-ulnaris.nerve >}} | {{< var ref-extensor-carpi-ulnaris.action >}} |
: Posterior Forearm Muscles (Superficial layer) {.striped .hover}

| Muscle  | Origin | Insertion | Nerve | Action |
|------|--------|-------|----------|--------|
| [Extensor Indicis]({{< var ref-extensor-indicis.path >}}) | {{< var ref-extensor-indicis.origin >}} | {{< var ref-extensor-indicis.insertion >}} | {{< var ref-extensor-indicis.nerve >}} | {{< var ref-extensor-indicis.action >}} |
| [Supinator]({{< var ref-supinator.path >}}) | {{< var ref-supinator.origin >}} | {{< var ref-supinator.insertion >}} | {{< var ref-supinator.nerve >}} | {{< var ref-supinator.action >}} |
| [Abductor Pollicis Longus]({{< var ref-abductor-pollicis-longus.path >}}) | {{< var ref-abductor-pollicis-longus.origin >}} | {{< var ref-abductor-pollicis-longus.insertion >}} | {{< var ref-abductor-pollicis-longus.nerve >}} | {{< var ref-abductor-pollicis-longus.action >}} |
| [Extensor Pollicis Longus]({{< var ref-extensor-pollicis-longus.path >}}) | {{< var ref-extensor-pollicis-longus.origin >}} | {{< var ref-extensor-pollicis-longus.insertion >}} | {{< var ref-extensor-pollicis-longus.nerve >}} | {{< var ref-extensor-pollicis-longus.action >}} |
| [Extensor Pollicis Brevis]({{< var ref-extensor-pollicis-brevis.path >}}) | {{< var ref-extensor-pollicis-brevis.origin >}} | {{< var ref-extensor-pollicis-brevis.insertion >}} | {{< var ref-extensor-pollicis-brevis.nerve >}} | {{< var ref-extensor-pollicis-brevis.action >}} |
: Posterior forearm (Deep layer) {.striped .hover}


# Hand

## Thenar Muscles

| Muscle  | Origin | Insertion | Nerve | Action |
|------|--------|-------|----------|--------|
| [Opponens Pollicis]({{< var ref-opponens-pollicis.path >}}) | {{< var ref-opponens-pollicis.origin >}} | {{< var ref-opponens-pollicis.insertion >}} | {{< var ref-opponens-pollicis.nerve >}} | {{< var ref-opponens-pollicis.action >}} |
| [Abductor Pollicis Brevis]({{< var ref-abductor-pollicis-brevis.path >}}) | {{< var ref-abductor-pollicis-brevis.origin >}} | {{< var ref-abductor-pollicis-brevis.insertion >}} | {{< var ref-abductor-pollicis-brevis.nerve >}} | {{< var ref-abductor-pollicis-brevis.action >}} |
| [Flexor Pollicis Brevis]({{< var ref-flexor-pollicis-brevis.path >}}) | {{< var ref-flexor-pollicis-brevis.origin >}} | {{< var ref-flexor-pollicis-brevis.insertion >}} | {{< var ref-flexor-pollicis-brevis.nerve >}} | {{< var ref-flexor-pollicis-brevis.action >}} |
: Thenar Muscles of the Hand {.striped .hover}

## Adductor Compartment

| Muscle  | Origin | Insertion | Nerve | Action |
|------|--------|-------|----------|--------|
| [Adductor Pollicis]({{< var ref-adductor-pollicis.path >}}) | {{< var ref-adductor-pollicis.origin >}} | {{< var ref-adductor-pollicis.insertion >}} | {{< var ref-adductor-pollicis.nerve >}} | {{< var ref-adductor-pollicis.action >}} |
: Adductor Compartment of the Hand {.striped .hover}

## Hypothenar

| Muscle  | Origin | Insertion | Nerve | Action |
|------|--------|-------|----------|--------|
| [Abductor Digiti Minimi (hand)]({{< var ref-abductor-digiti-minimi-hand.path >}}) | {{< var ref-abductor-digiti-minimi-hand.origin >}} | {{< var ref-abductor-digiti-minimi-hand.insertion >}} | {{< var ref-abductor-digiti-minimi-hand.nerve >}} | {{< var ref-abductor-digiti-minimi-hand.action >}} |
| [Flexor Digiti Minimi Brevis (Hand)]({{< var ref-flexor-digiti-minimi-brevis-hand.path >}}) | {{< var ref-flexor-digiti-minimi-brevis-hand.origin >}} | {{< var ref-flexor-digiti-minimi-brevis-hand.insertion >}} | {{< var ref-flexor-digiti-minimi-brevis-hand.nerve >}} | {{< var ref-flexor-digiti-minimi-brevis-hand.action >}} |
| [Opponens Digiti Minimi]({{< var ref-opponens-digiti-minimi.path >}}) | {{< var ref-opponens-digiti-minimi.origin >}} | {{< var ref-opponens-digiti-minimi.insertion >}} | {{< var ref-opponens-digiti-minimi.nerve >}} | {{< var ref-opponens-digiti-minimi.action >}} |
: {.striped .hover}

## Short Muscles

| Muscle  | Origin | Insertion | Nerve | Action |
|------|--------|-------|----------|--------|
| [Lumbricals (Hand)]({{< var ref-lumbricals-hand.path >}}) | {{< var ref-lumbricals-hand.origin >}} | {{< var ref-lumbricals-hand.insertion >}} | {{< var ref-lumbricals-hand.nerve >}} | {{< var ref-lumbricals-hand.action >}} |
| [Dorsal Interossei]({{< var ref-dorsal-interossei-hand.path >}}) | {{< var ref-dorsal-interossei-hand.origin >}} | {{< var ref-dorsal-interossei-hand.insertion >}} | {{< var ref-dorsal-interossei-hand.nerve >}} | {{< var ref-dorsal-interossei-hand.action >}} |
| [Palmar Interossei (Hand)]({{< var ref-palmar-interossei-hand.path >}}) | {{< var ref-palmar-interossei-hand.origin >}} | {{< var ref-palmar-interossei-hand.insertion >}} | {{< var ref-palmar-interossei-hand.nerve >}} | {{< var ref-palmar-interossei-hand.action >}} |
: {.striped .hover}

# Hip & Thigh

## Iliopsoas

| Muscle  | Origin | Insertion | Nerve | Action |
|------|--------|-------|----------|--------|
| [Psoas Major]({{< var ref-psoas-major.path >}}) | {{< var ref-psoas-major.origin >}} | {{< var ref-psoas-major.insertion >}} | {{< var ref-psoas-major.nerve >}} | {{< var ref-psoas-major.action >}} |
| [Psoas Minor]({{< var ref-psoas-minor.path >}}) | {{< var ref-psoas-minor.origin >}} | {{< var ref-psoas-minor.insertion >}} | {{< var ref-psoas-minor.nerve >}} | {{< var ref-psoas-minor.action >}} |
| [Iliacus]({{< var ref-iliacus.path >}}) | {{< var ref-iliacus.origin >}} | {{< var ref-iliacus.insertion >}} | {{< var ref-iliacus.nerve >}} | {{< var ref-iliacus.action >}} |
: {.striped .hover}


## Gluteal

| Muscle  | Origin | Insertion | Nerve | Action |
|------|--------|-------|----------|--------|
| [Gluteus Maximus]({{< var ref-gluteus-maximus.path >}}) | {{< var ref-gluteus-maximus.origin >}} | {{< var ref-gluteus-maximus.insertion >}} | {{< var ref-gluteus-maximus.nerve >}} | {{< var ref-gluteus-maximus.action >}} |
| [Gluteus Medius]({{< var ref-gluteus-medius.path >}}) | {{< var ref-gluteus-medius.origin >}} | {{< var ref-gluteus-medius.insertion >}} | {{< var ref-gluteus-medius.nerve >}} | {{< var ref-gluteus-medius.action >}} |
| [Gluteus Minimus]({{< var ref-gluteus-minimus.path >}}) | {{< var ref-gluteus-minimus.origin >}} | {{< var ref-gluteus-minimus.insertion >}} | {{< var ref-gluteus-minimus.nerve >}} | {{< var ref-gluteus-minimus.action >}} |
| [Tensor Fascia Latae]({{< var ref-tensor-fascia-latae.path >}}) | {{< var ref-tensor-fascia-latae.origin >}} | {{< var ref-tensor-fascia-latae.insertion >}} | {{< var ref-tensor-fascia-latae.nerve >}} | {{< var ref-tensor-fascia-latae.action >}} |
| [Piriformis]({{< var ref-piriformis.path >}}) | {{< var ref-piriformis.origin >}} | {{< var ref-piriformis.insertion >}} | {{< var ref-piriformis.nerve >}} | {{< var ref-piriformis.action >}} |
| [Obturator Internus]({{< var ref-obturator-internus.path >}}) | {{< var ref-obturator-internus.origin >}} | {{< var ref-obturator-internus.insertion >}} | {{< var ref-obturator-internus.nerve >}} | {{< var ref-obturator-internus.action >}} |
| [Superior Gemellus]({{< var ref-superior-gemellus.path >}}) | {{< var ref-superior-gemellus.origin >}} | {{< var ref-superior-gemellus.insertion >}} | {{< var ref-superior-gemellus.nerve >}} | {{< var ref-superior-gemellus.action >}} |
| [Inferior Gemellus]({{< var ref-inferior-gemellus.path >}}) | {{< var ref-inferior-gemellus.origin >}} | {{< var ref-inferior-gemellus.insertion >}} | {{< var ref-inferior-gemellus.nerve >}} | {{< var ref-inferior-gemellus.action >}} |
| [Quadratus Femoris]({{< var ref-quadratus-femoris.path >}}) | {{< var ref-quadratus-femoris.origin >}} | {{< var ref-quadratus-femoris.insertion >}} | {{< var ref-quadratus-femoris.nerve >}} | {{< var ref-quadratus-femoris.action >}} |
: {.striped .hover}



## Medial Thigh

| Muscle  | Origin | Insertion | Nerve | Action |
|------|--------|-------|----------|--------|
| [Pectineus]({{< var ref-pectineus.path >}}) | {{< var ref-pectineus.origin >}} | {{< var ref-pectineus.insertion >}} | {{< var ref-pectineus.nerve >}} | {{< var ref-pectineus.action >}} |
| [Gracilis]({{< var ref-gracilis.path >}}) | {{< var ref-gracilis.origin >}} | {{< var ref-gracilis.insertion >}} | {{< var ref-gracilis.nerve >}} | {{< var ref-gracilis.action >}} |
| [Adductor Longus]({{< var ref-adductor-longus.path >}}) | {{< var ref-adductor-longus.origin >}} | {{< var ref-adductor-longus.insertion >}} | {{< var ref-adductor-longus.nerve >}} | {{< var ref-adductor-longus.action >}} |
| [Adductor Brevis]({{< var ref-adductor-brevis.path >}}) | {{< var ref-adductor-brevis.origin >}} | {{< var ref-adductor-brevis.insertion >}} | {{< var ref-adductor-brevis.nerve >}} | {{< var ref-adductor-brevis.action >}} |
| [Obturator Externus]({{< var ref-obturator-externus.path >}}) | {{< var ref-obturator-externus.origin >}} | {{< var ref-obturator-externus.insertion >}} | {{< var ref-obturator-externus.nerve >}} | {{< var ref-obturator-externus.action >}} |
| [Adductor Magnus]({{< var ref-adductor-magnus.path >}}) | {{< var ref-adductor-magnus.origin >}} | {{< var ref-adductor-magnus.insertion >}} | {{< var ref-adductor-magnus.nerve >}} | {{< var ref-adductor-magnus.action >}} |
: {.striped .hover}


## Anterior Thigh

| Muscle  | Origin | Insertion | Nerve | Action |
|------|--------|-------|----------|--------|
| [Sartorius]({{< var ref-sartorius.path >}}) | {{< var ref-sartorius.origin >}} | {{< var ref-sartorius.insertion >}} | {{< var ref-sartorius.nerve >}} | {{< var ref-sartorius.action >}} |
| [Rectus Femoris]({{< var ref-rectus-femoris.path >}}) | {{< var ref-rectus-femoris.origin >}} | {{< var ref-rectus-femoris.insertion >}} | {{< var ref-rectus-femoris.nerve >}} | {{< var ref-rectus-femoris.action >}} |
| [Vastus Medialis]({{< var ref-vastus-medialis.path >}}) | {{< var ref-vastus-medialis.origin >}} | {{< var ref-vastus-medialis.insertion >}} | {{< var ref-vastus-medialis.nerve >}} | {{< var ref-vastus-medialis.action >}} |
| [Vastus Lateralis]({{< var ref-vastus-lateralis.path >}}) | {{< var ref-vastus-lateralis.origin >}} | {{< var ref-vastus-lateralis.insertion >}} | {{< var ref-vastus-lateralis.nerve >}} | {{< var ref-vastus-lateralis.action >}} |
| [Vastus Intermedius]({{< var ref-vastus-intermedius.path >}}) | {{< var ref-vastus-intermedius.origin >}} | {{< var ref-vastus-intermedius.insertion >}} | {{< var ref-vastus-intermedius.nerve >}} | {{< var ref-vastus-intermedius.action >}} |
| [Articularis Genus]({{< var ref-articularis-genus.path >}}) | {{< var ref-articularis-genus.origin >}} | {{< var ref-articularis-genus.insertion >}} | {{< var ref-articularis-genus.nerve >}} | {{< var ref-articularis-genus.action >}} |
: Muscles of the Anterior Thigh {.striped .hover}


## Posterior Thigh

| Muscle  | Origin | Insertion | Nerve | Action |
|------|--------|-------|----------|--------|
| [Biceps Femoris Long Head]({{< var ref-biceps-femoris-long-head.path >}}) | {{< var ref-biceps-femoris-long-head.origin >}} | {{< var ref-biceps-femoris-long-head.insertion >}} | {{< var ref-biceps-femoris-long-head.nerve >}} | {{< var ref-biceps-femoris-long-head.action >}} |
| [Biceps Femoris Short Head]({{< var ref-biceps-femoris-short-head.path >}}) | {{< var ref-biceps-femoris-short-head.origin >}} | {{< var ref-biceps-femoris-short-head.insertion >}} | {{< var ref-biceps-femoris-short-head.nerve >}} | {{< var ref-biceps-femoris-short-head.action >}} |
| [Semitendinosus]({{< var ref-semitendinosus.path >}}) | {{< var ref-semitendinosus.origin >}} | {{< var ref-semitendinosus.insertion >}} | {{< var ref-semitendinosus.nerve >}} | {{< var ref-semitendinosus.action >}} |
| [Semimembranosus]({{< var ref-semimembranosus.path >}}) | {{< var ref-semimembranosus.origin >}} | {{< var ref-semimembranosus.insertion >}} | {{< var ref-semimembranosus.nerve >}} | {{< var ref-semimembranosus.action >}} |
: {.striped .hover}



# Knee & Lower Leg

## Anterior Compartment

| Muscle  | Origin | Insertion | Nerve | Action |
|------|--------|-------|----------|--------|
| [Tibialis Anterior]({{< var ref-tibialis-anterior.path >}}) | {{< var ref-tibialis-anterior.origin >}} | {{< var ref-tibialis-anterior.insertion >}} | {{< var ref-tibialis-anterior.nerve >}} | {{< var ref-tibialis-anterior.action >}} |
| [Extensor Hallucis Longus]({{< var ref-extensor-hallucis-longus.path >}}) | {{< var ref-extensor-hallucis-longus.origin >}} | {{< var ref-extensor-hallucis-longus.insertion >}} | {{< var ref-extensor-hallucis-longus.nerve >}} | {{< var ref-extensor-hallucis-longus.action >}} |
| [Extensor Digitorum Longus]({{< var ref-extensor-digitorum-longus.path >}}) | {{< var ref-extensor-digitorum-longus.origin >}} | {{< var ref-extensor-digitorum-longus.insertion >}} | {{< var ref-extensor-digitorum-longus.nerve >}} | {{< var ref-extensor-digitorum-longus.action >}} |
| [Fibularis Tertius]({{< var ref-fibularis-tertius.path >}}) | {{< var ref-fibularis-tertius.origin >}} | {{< var ref-fibularis-tertius.insertion >}} | {{< var ref-fibularis-tertius.nerve >}} | {{< var ref-fibularis-tertius.action >}} |
: {.striped .hover}

## Lateral Compartment

| Muscle  | Origin | Insertion | Nerve | Action |
|------|--------|-------|----------|--------|
| [Fibularis Longus]({{< var ref-fibularis-longus.path >}}) | {{< var ref-fibularis-longus.origin >}} | {{< var ref-fibularis-longus.insertion >}} | {{< var ref-fibularis-longus.nerve >}} | {{< var ref-fibularis-longus.action >}} |
| [Fibularis Brevis]({{< var ref-fibularis-brevis.path >}}) | {{< var ref-fibularis-brevis.origin >}} | {{< var ref-fibularis-brevis.insertion >}} | {{< var ref-fibularis-brevis.nerve >}} | {{< var ref-fibularis-brevis.action >}} |
: {.striped .hover}

## Posterior Compartment

| Muscle  | Origin | Insertion | Nerve | Action |
|------|--------|-------|----------|--------|
| [Gastrocnemius]({{< var ref-gastrocnemius.path >}}) | {{< var ref-gastrocnemius.origin >}} | {{< var ref-gastrocnemius.insertion >}} | {{< var ref-gastrocnemius.nerve >}} | {{< var ref-gastrocnemius.action >}} |
| [Soleus]({{< var ref-soleus.path >}}) | {{< var ref-soleus.origin >}} | {{< var ref-soleus.insertion >}} | {{< var ref-soleus.nerve >}} | {{< var ref-soleus.action >}} |
| [Plantaris]({{< var ref-plantaris.path >}}) | {{< var ref-plantaris.origin >}} | {{< var ref-plantaris.insertion >}} | {{< var ref-plantaris.nerve >}} | {{< var ref-plantaris.action >}} |
: Superficial Flexors of the Posterior Compartment {.striped .hover}


| Muscle  | Origin | Insertion | Nerve | Action |
|------|--------|-------|----------|--------|
| [Tibialis Posterior]({{< var ref-tibialis-posterior.path >}}) | {{< var ref-tibialis-posterior.origin >}} | {{< var ref-tibialis-posterior.insertion >}} | {{< var ref-tibialis-posterior.nerve >}} | {{< var ref-tibialis-posterior.action >}} |
| [Flexor Digitorum Longus]({{< var ref-flexor-digitorum-longus.path >}}) | {{< var ref-flexor-digitorum-longus.origin >}} | {{< var ref-flexor-digitorum-longus.insertion >}} | {{< var ref-flexor-digitorum-longus.nerve >}} | {{< var ref-flexor-digitorum-longus.action >}} |
| [Flexor Hallucis Longus]({{< var ref-flexor-hallucis-longus.path >}}) | {{< var ref-flexor-hallucis-longus.origin >}} | {{< var ref-flexor-hallucis-longus.insertion >}} | {{< var ref-flexor-hallucis-longus.nerve >}} | {{< var ref-flexor-hallucis-longus.action >}} |
| [Popliteus]({{< var ref-popliteus.path >}}) | {{< var ref-popliteus.origin >}} | {{< var ref-popliteus.insertion >}} | {{< var ref-popliteus.nerve >}} | {{< var ref-popliteus.action >}} |
: Deep Flexors of the Posterior Compartment {.striped .hover}

# Foot

## Dorsum of the Foot

| Muscle  | Origin | Insertion | Nerve | Action |
|------|--------|-------|----------|--------|
| [Extensor Digitorum Brevis]({{< var ref-extensor-digitorum-brevis.path >}}) | {{< var ref-extensor-digitorum-brevis.origin >}} | {{< var ref-extensor-digitorum-brevis.insertion >}} | {{< var ref-extensor-digitorum-brevis.nerve >}} | {{< var ref-extensor-digitorum-brevis.action >}} |
| [Extensor Hallucis Brevis]({{< var ref-extensor-hallucis-brevis.path >}}) | {{< var ref-extensor-hallucis-brevis.origin >}} | {{< var ref-extensor-hallucis-brevis.insertion >}} | {{< var ref-extensor-hallucis-brevis.nerve >}} | {{< var ref-extensor-hallucis-brevis.action >}} |
:  {.striped .hover}

## Superficial Intrinsic Plantar Foot muscles

| Muscle  | Origin | Insertion | Nerve | Action |
|------|--------|-------|----------|--------|
| [Abductor Hallucis]({{< var ref-abductor-hallucis.path >}}) | {{< var ref-abductor-hallucis.origin >}} | {{< var ref-abductor-hallucis.insertion >}} | {{< var ref-abductor-hallucis.nerve >}} | {{< var ref-abductor-hallucis.action >}} |
| [Flexor Digitorum Brevis]({{< var ref-flexor-digitorum-brevis.path >}}) | {{< var ref-flexor-digitorum-brevis.origin >}} | {{< var ref-flexor-digitorum-brevis.insertion >}} | {{< var ref-flexor-digitorum-brevis.nerve >}} | {{< var ref-flexor-digitorum-brevis.action >}} |
| [Abductor Digiti Minimi (foot)]({{< var ref-abductor-digiti-minimi-foot.path >}}) | {{< var ref-abductor-digiti-minimi-foot.origin >}} | {{< var ref-abductor-digiti-minimi-foot.insertion >}} | {{< var ref-abductor-digiti-minimi-foot.nerve >}} | {{< var ref-abductor-digiti-minimi-foot.action >}} |
: {.striped .hover}

## Deep Intrinsic plantar foot muscles

| Muscle  | Origin | Insertion | Nerve | Action |
|------|--------|-------|----------|--------|
| [Quadratus Plantae]({{< var ref-quadratus-plantae.path >}}) | {{< var ref-quadratus-plantae.origin >}} | {{< var ref-quadratus-plantae.insertion >}} | {{< var ref-quadratus-plantae.nerve >}} | {{< var ref-quadratus-plantae.action >}} |
| [Lumbricals (foot)]({{< var ref-foot-lumbricals.path >}}) | {{< var ref-foot-lumbricals.origin >}} | {{< var ref-foot-lumbricals.insertion >}} | {{< var ref-foot-lumbricals.nerve >}} | {{< var ref-foot-lumbricals.action >}} |
| [Flexor Hallucis Brevis]({{< var ref-flexor-hallucis-brevis.path >}}) | {{< var ref-flexor-hallucis-brevis.origin >}} | {{< var ref-flexor-hallucis-brevis.insertion >}} | {{< var ref-flexor-hallucis-brevis.nerve >}} | {{< var ref-flexor-hallucis-brevis.action >}} |
| [Adductor Hallucis]({{< var ref-adductor-hallucis.path >}}) | {{< var ref-adductor-hallucis.origin >}} | {{< var ref-adductor-hallucis.insertion >}} | {{< var ref-adductor-hallucis.nerve >}} | {{< var ref-adductor-hallucis.action >}} |
| [Flexor Digiti Minimi Brevis (Foot)]({{< var ref-flexor-digiti-minimi-brevis-foot.path >}}) | {{< var ref-flexor-digiti-minimi-brevis-foot.origin >}} | {{< var ref-flexor-digiti-minimi-brevis-foot.insertion >}} | {{< var ref-flexor-digiti-minimi-brevis-foot.nerve >}} | {{< var ref-flexor-digiti-minimi-brevis-foot.action >}} |
| [Opponens Digiti Minimi]({{< var ref-opponens-digiti-minimi.path >}}) | {{< var ref-opponens-digiti-minimi.origin >}} | {{< var ref-opponens-digiti-minimi.insertion >}} | {{< var ref-opponens-digiti-minimi.nerve >}} | {{< var ref-opponens-digiti-minimi.action >}} |
| [Plantar Interossei]({{< var ref-plantar-interossei.path >}}) | {{< var ref-plantar-interossei.origin >}} | {{< var ref-plantar-interossei.insertion >}} | {{< var ref-plantar-interossei.nerve >}} | {{< var ref-plantar-interossei.action >}} |
| [Dorsal Interossei]({{< var ref-dorsal-interossei.path >}}) | {{< var ref-dorsal-interossei.origin >}} | {{< var ref-dorsal-interossei.insertion >}} | {{< var ref-dorsal-interossei.nerve >}} | {{< var ref-dorsal-interossei.action >}} |
: {.striped .hover}