---
title: Anterior Stability Test of the Lumbar Spine
---


"The patient is in the side-lying position. To test the lower three segments (L3–5), the patient’s hips are placed in approximately 70 degrees of flexion, and the knees are flexed (Fig. 28-48A). This position is to prevent tightening of the posterior lumbar ligaments, particularly the SSL, which could stabilize the lower three segments and produce a false-negative test result. The clinician stands to face the patient, resting his or her thighs against the patient’s knees. The upper segments are stabilized using the cranial hand and the other hand over it. The inferior interspinous space is palpated. The clinician pushes with the thighs, through the patient’s knees, along the line of the femur (Fig. 28-48B). This produces a posteriorly directed force to the pelvis, sacrum, and lumbar spine. Any posterior movement of the inferior segment, which is actually a relative anterior movement of the superior segment on the inferior segment, is noted and compared with the next segmental level. There should be little or no movement. To test the upper two segments (L2 and L1), the lumbar spine is flexed by flexing the hips to approximately 100 degrees, and the procedure is repeated. A positive test is one in which there is excessive movement or pain, or both." @duttonDuttonOrthopaedicExamination2020 