---
title: Prone Instability Test
subtitle: Lumbar Spine stability Test
---


"The patient is positioned prone so that the trunk rests on the bed, and the feet rest on the floor, with the hips flexed and the trunk muscles relaxed. The clinician applies a P-A pressure (approximately 4 kg or thumbnail blanching) over the most symptomatic spinous process, and any reproduction of symptoms is noted. The clinician then releases the P-A pressure, and the patient is asked to hold onto the sides of the table and to slightly lift his or her feet off the floor (Fig. 28-50). This maneuver produces a cocontraction of the global abdominal, gluteal, and erector spinae muscles. While the patient maintains their feet off the floor, the clinician reapplies the P-A pressure over the same spinous process level. If a dramatic reduction or the complete elimination of the symptoms compared to the first application of P-A pressure is noted (the muscle activity must be able to effectively stabilize the segment), it is considered a positive prone instability test. This test has been found to have good to excellent agreement reported (k = 0.87)92 for three pairs of physical therapy raters evaluating 63 consecutive subjects currently experiencing LBP and with a previous history of LBP. According to Hicks et al.,92 patients with LBP, who present with a negative prone instability test, are unlikely to respond to a stabilization exercise program. However, it must be remembered that as an independent test, the Prone Instability Test has limited diagnostic use (+LR = 1.7[95% CI; 1.1, 2.8]; -LR = 0.48 [95% CI: 0.22, 1.1])130; as it is most useful as a component of a cluster of tests to predict response to motor control exercises." @duttonDuttonOrthopaedicExamination2020 