---
title: Superior Colliculus
---

A structure that is part of the [Corpora Quadrigemina]({{< var ref-corpora-quadrigemina.path >}}) that aids in visual orientation (head and eyes) towards light

# Pathway
## Input

Mechanoreceptor input from upper cervical segments (OA, AA, A-c3) from cervical spine muscles have direct input on the superior colliculus @kristjanssonSensorimotorFunctionDizziness2009

## Pathway

Decussate: in midbrain (Dorsal tegmental decussation)

## Output

The superior colliculus pathway terminates at:

- Pulvinar nucleus (Thalamus)
- And possibly the Lateral geniculate nucleus?


# Function

The afferent information from the superior colliculus allows 

- Visual orienting:
    - Tracking a moving object
    - Orients head & eyes (turns head away or towards flash of light)


# Clinical Significance

Mechanoreceptor input(OA, AA, A-c3) and C/S muscles to the superior colliculus can cause problems with sensorimotor control as well as cervicogenic headaches @kristjanssonSensorimotorFunctionDizziness2009.

Even stimulation of these muscle afferents (via nuck muscle vibration) can induce eye position changes, visual illusory mvmts and head mvmt illusions)