---
title: Cerebellar Ataxic Gait
subtitle: Symptomatic gait resulting from CNS Dysfunction
---



Lesions of the anterior lobe of the cerebellum can also be accompanied by a discrete impairment in gait, and those affecting the flocculonodular lobe affect equilibrium [29]. Cerebellar lesions may affect gait by causing disequilibrium and by altering limb and trunk kinematics and interlimb coordination [20]. The cerebellum does not appear to actually generate postural and gait synergies because these automatic responses, albeit very dysmetric, are present in dogs with total cerebellectomy [58]. Disturbances of gait and balance are primarily caused by lesions of the vestibulocerebellum and spinocerebellum or their connections. Lesions of the cerebellar hemispheres cause irregular timing, force, and cadence of leg movements, leading to inaccurate and variable stepping [32]. Lesions of the vestibulocerebellum, or flocculonodular lobe, can produce @brazisLocalizationClinicalNeurology2022

balance and gait disturbances that resemble those caused by vestibular lesions [20]. Tremor of the head and trunk, truncal imbalance, and swaying and falling in all directions are characteristic of vestibulocerebellar lesions. Vestibular nystagmus may be present. Although most often patients with cerebellar lesions tend to fall to the side of the lesion, some patients with lesions in the tonsillar area develop increased tone (and increased reflexes) in the ipsilateral side and fall to the contralateral side. The clinical syndrome caused by lesions of the spinocerebellum is best characterized by alcoholic cerebellar degeneration, which primarily affects the anterior lobe of the cerebellum but also involves the olivary complex and the vestibular nuclei [71]. Patients with alcoholic cerebellar degeneration have a widened base, instability of the trunk, slow and halting gait with irregular steps and superimposed lurching. The gait abnormalities are accentuated at the initiation of gait, on turning, and with changes in gait speed. These patients may have severe gait ataxia without nystagmus, dysarthria, or arm dysmetria. Even the heel-to-shin test may give little inkling of the severity of the gait disturbance. The anterior lobe of the cerebellum is exquisitely sensitive to many metabolic injuries, not just alcohol. For instance, in severe hypoxia, the anterior lobe can be severely damaged, whereas the rest of the cerebellum may be spared @brazisLocalizationClinicalNeurology2022.