---
title: Spastic gait
---

Corticospinal tract lesions give rise to a spastic gait, unilateral or hemiparetic when the lesion is unilateral and paraparetic when the lesion is bilateral. The base of support is narrow, so much so that with bilateral lesions the legs tend to cross in front of each other in a pattern that has been called “scissors gait.” The leg is externally rotated at the hip. The knee is extended and stiff, so the patient walks as if on a stilt. The foot is plantar flexed and inverted; for this reason, the patient tends to scrape the floor with the outer edge of the foot; the patient’s turns are slow. With each step the affected leg is rotated away from the body, then toward it (circumduction). There is also difficulty picking up the toes on the hemiparetic side, when instructed to walk on the heels and decrease cadence of gait. The lesion can be anywhere along the corticospinal tract. When the lesion is unilateral, the abnormality is easy to diagnose. @brazisLocalizationClinicalNeurology2022


Bilateral lesions, particularly when they cause a slowly progressive syndrome, are more difficult to diagnose early in the course of the disease. The cervical myelopathy of cervical spondylosis, a relatively common syndrome, belongs to this category. Cervical spondylosis tends to cause demyelinating lesions in the posterior columns and corticospinal tracts of the cervical spinal cord. The most common place of involvement is at the C5 C6 interspace. Severe lesions in this location result in paraparesis and clumsiness of the hand with atrophy in the small muscles of the hand. Milder lesions may only give rise to unsteadiness while walking or standing, often accompanied by a positive Romberg sign [43]. The brachioradialis reflex may be depressed, and instead, a brisk finger flexor response is elicited when percussing the brachioradialis tendon (inverted radial reflex). Careful testing of vibratory sense may reveal a sensory level in the cervical region. Sometimes, the patient perceives the stimulus better in the thumb than in the small finger. Early diagnosis is important because the myelopathy of cervical spondylosis is often progressive if untreated [59]. @brazisLocalizationClinicalNeurology2022