---
title: Middle Scalene Muscle
---


# OIAN

# Origin {#origin}
C1–C2 (transverse processes), C3–C7 (posterior tubercles of transverse processes) @gilroyAtlasAnatomy2020

### Insertion {#insertion}
1st rib (posterior to groove for subclavian a.)

### Nerve
Anterior rami of [C3]({{< var ref-nerve-root.c3 >}}), [C4]({{< var ref-nerve-root.c4 >}}), [C5]({{< var ref-nerve-root.c5 >}}), [C6]({{< var ref-nerve-root.c6 >}}), [C7]({{< var ref-nerve-root.c7 >}}), & [C8]({{< var ref-nerve-root.c8 >}}) @gilroyAtlasAnatomy2020 

### Action {#action}

- According to Atlas of Anatomy @gilroyAtlasAnatomy2020, the scalenes all have the same function:
- With ribs mobile: Elevates upper ribs (during forced inspiration) @gilroyAtlasAnatomy2020 
- With ribs fixed: Flexes cervical spine to same side (unilateral) @gilroyAtlasAnatomy2020, flexes neck (bilateral) @gilroyAtlasAnatomy2020 
:::




# Hypertonicity

## Causes
Forward head posture can cause hypertonicity and/or hypertrophy of the Middle Scalene muscle @duttonDuttonOrthopaedicExamination2020.

## Pathologies

Hypertonicity of the middle scalene can cause impingement of the [Dorsal Scapular Nerve]({{< var ref-dorsal-scapular-nerve.path >}}) @duttonDuttonOrthopaedicExamination2020

# Related pathologies

- The Middle Scalene can cause entrapment of the [C5]({{< var ref-nerve-root.c5 >}}) and [C6]({{< var ref-nerve-root.c6 >}}) since these nerves pass through this muscle @duttonDuttonOrthopaedicExamination2020.
    - This can result in problems with the [Long Thoracic Nerve]({{< var ref-long-thoracic-nerve.path >}}) @duttonDuttonOrthopaedicExamination2020.