---
title: Ranchos Los Amigos Revised Scale (RLAS-R)
---


# Levels

## Level I: No response

Level 1 is characterized by: no Response and requiring total Assistance @linRanchosAmigos2024

Patient has no response to external stimuli (visual, verbal, tactile, auditory, noxious stimuli) @linRanchosAmigos2024

## Level II: Generalized response

Level 2 is characterized by a patient requiring total assistance, but demonstrates "Generalized Response" @linRanchosAmigos2024.

Generalized response refers to a patient who responds inconsistently and non-purposefully to external stimuli. In addition, responses are often the same regardless of the stimulus

## Level III: Localized response

## Level IV: Confused-agitated

## Level V: Confused-inappropriate

## Level VI: Confused-appropriate

## Level VII: Automatic-inappropriate

Level VII: Automatic, Appropriate: Minimal Assistance for Daily Living Skills

Oriented in familiar settings
Able to perform daily routine automatically with minimal to absent confusion
Demonstrates carry over for new tasks and learning in addition to familiar tasks
Superficially aware of one’s diagnosis but unaware of specific impairments
Continues to demonstrate lack of insight, decreased judgment and safety awareness
Beginning to show interest in social and recreational activities in structured settings
Requires at least minimal supervision for learning and safety purposes.

## Level VIII: Purposeful & Appropriate

## Level IX: Standby assistance

## Level X: Modified independent

# Assessing RLAS-R Level

It is especially difficult to assess RLAS level 7-10.
Often times, the patients assume the behavior is normal and due to their personality rather than their cognitive impairment.

Often times, these are executive function impairments, such as volition, planning, purposive action, and effective performance.