---
title: Joint Capsule of the Knee Complex
---


"The capsule of the knee joint complex is composed of a thin, strong fibrous membrane, and it is the largest synovial capsule in the body. The capsule ascends anteriorly approximately 2 finger breadths above the patella to form the suprapatellar pouch. Posteriorly, it ascends to the origins of the gastrocnemius. Inferiorly, the capsule attaches to the edges of the articulating surfaces of the tibial plateaus, with the exception of the intercondylar eminence, and a small portion of the anterior intercondylar region.1 A synovial membrane lines the inner portion of the knee joint capsule. By lining the joint capsule, the synovial membrane excludes the cruciate ligaments from the interior portion of the knee joint, making them extrasynovial yet intra-articular." @duttonDuttonOrthopaedicExamination2020


"The articularis genu, located superior to the patella, is thought to function to retract the knee capsule during knee extension. Thus, it serves a similar function as the anconeus at the elbow." @duttonDuttonOrthopaedicExamination2020 